### ISSUE TITLE
[MOVIE]: Shin Ultraman (2022)

### ISSUE THREAD

**Issue by tylerbickel** [LizardByte/ThemerrDB#103]
### IMDB URL

https://www.imdb.com/title/tt10737918

### TheMovieDB URL

https://www.themoviedb.org/movie/634429-shin-urutoraman

### TheTVDB URL

https://thetvdb.com/movies/149373-

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=jNXCKtM1hkU

**Comment by ReenigneArcher** [comment]
I need to update my script before I can process this entry due to the trailing `-` on the end of TheTVDB URL. You entered the info correctly, but my script doesn't handle this url properly right now.
