### ISSUE TITLE
[MOVIE]: Ron's Gone Wrong (2021)

### ISSUE THREAD

**Issue by tylerbickel** [LizardByte/ThemerrDB#105]
### IMDB URL

https://www.imdb.com/title/tt7504818

### TheMovieDB URL

https://www.themoviedb.org/movie/482321-ron-s-gone-wrong

### TheTVDB URL

https://thetvdb.com/movies/rons-gone-wrong

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=yzoFm1JyDcg

**Comment by ReenigneArcher** [comment]
I've corrected some of the links.

imdb: from https://www.imdb.com/title/tt7504818/?ref_=nv_sr_srsg_0 to https://www.imdb.com/title/tt7504818
tmdb: from https://www.themoviedb.org/search/movie?query=Ron%27s%20Gone%20Wrong to https://www.themoviedb.org/movie/482321-ron-s-gone-wrong
