### ISSUE TITLE
[MOVIE]: The Court Jester (1955)

### ISSUE THREAD

**Issue by jjnether** [LizardByte/ThemerrDB#1057]
### TheMovieDB URL

https://www.themoviedb.org/movie/11839-the-court-jester?language=en-US

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=ILomtVLM8_w&ab_channel=DannyKaye-Topic

**Comment by ReenigneArcher** [comment]
Is there an alternative which isn't the exact beginning of the movie?

**Comment by jjnether** [comment]
My bad, I edited the link to a better one.
