### ISSUE TITLE
[MOVIE]: My Name Is Thomas (2018)

### ISSUE THREAD

**Issue by LetsGoDude** [LizardByte/ThemerrDB#107]
### IMDB URL

https://www.imdb.com/title/tt6292090

### TheMovieDB URL

https://www.themoviedb.org/movie/429710-la-chiamavano-maryam

### TheTVDB URL

https://thetvdb.com/movies/my-name-is-thomas

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=9WM7f0qnjWs

**Comment by ReenigneArcher** [comment]
I typically like to have a higher quality video.

I've changed it from https://www.youtube.com/watch?v=QB6SMlZ0LQU to https://www.youtube.com/watch?v=9WM7f0qnjWs
