### ISSUE TITLE
[MOVIE]: RRR (2022)

### ISSUE THREAD

**Issue by yashaskm11** [LizardByte/ThemerrDB#1094]
### TheMovieDB URL

https://www.themoviedb.org/movie/579974

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=MtWKhtfZ3fc

**Comment by ReenigneArcher** [comment]
@yashaskm11 Something wrong with the existing theme song for this movie? https://github.com/LizardByte/ThemerrDB/issues/636

**Comment by yashaskm11** [comment]
I felt this theme song is more apt to movie, as it plays during the titles.
The previous song plays during a character introduction in the movie.

**Comment by ReenigneArcher** [comment]
@tylerbickel any objection?

**Comment by tylerbickel** [comment]
Yes that’s fine with me!
________________________________
