### ISSUE TITLE
[MOVIE]: Captain Marvel (2019)

### ISSUE THREAD

**Issue by polzy** [LizardByte/ThemerrDB#1118]
### Database URL

https://www.themoviedb.org/movie/299537-captain-marvel

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=9fDPLQ2XGOg&ab_channel=Eredus

**Comment by ReenigneArcher** [comment]
Thanks for the submission. We generally prefer shorter themes, since Plex doesn't like if they extend much past 2:45.

Since this movie already has a theme, I will close this issue. Thank you.
