### ISSUE TITLE
[MOVIE]: Dungeons & Dragons: Honor Among Thieves (2023)

### ISSUE THREAD

**Issue by SiriosDev** [LizardByte/ThemerrDB#1133]
### Database URL

https://www.themoviedb.org/movie/493529

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=f2k1JjnY0dQ

**Comment by SiriosDev** [comment]
the before one was, strangely, region locked and this is unlocked only in USA, probably a problem of license

**Comment by ReenigneArcher** [comment]
This video is the same as what's already in the database.

Duplicate of #1036

**Comment by SiriosDev** [comment]
sorry, On the lizardbyte.dev/ThemerrDB site I checked and no sound was starting
