### ISSUE TITLE
[MOVIE]: Emancipation (2022)

### ISSUE THREAD

**Issue by OcifferAction** [LizardByte/ThemerrDB#1181]
### Database URL

https://www.themoviedb.org/movie/715931

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=1b8j7alWZfg

**Comment by jjnether** [comment]
8 minutes is a bit long for a theme, what do you think about this one instead?

https://www.youtube.com/watch?v=1b8j7alWZfg&ab_channel=LakeshoreRecords

**Comment by OcifferAction** [comment]
That works well!
