### ISSUE TITLE
[MOVIE]: Avatar (2009)

### ISSUE THREAD

**Issue by LetsGoDude** [LizardByte/ThemerrDB#121]
### IMDB URL

https://www.imdb.com/title/tt0499549

### TheMovieDB URL

https://www.themoviedb.org/movie/19995-avatar

### TheTVDB URL

https://thetvdb.com/movies/avatar

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=qo7LNrzb7_E

**Comment by ReenigneArcher** [comment]
I changed the youtube from https://www.youtube.com/watch?v=6wdS0HXvZ-0 to https://www.youtube.com/watch?v=qo7LNrzb7_E
