### ISSUE TITLE
[MOVIE]: Fate/Grand Order the Movie: Divine Realm of the Round Table: Camelot Wandering; Agateram (2020)

### ISSUE THREAD

**Issue by YP2743** [LizardByte/ThemerrDB#1211]
### Database URL

https://www.themoviedb.org/movie/637202-fate-grand-order-wandering-agateram?language=en

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=VDbwTzcjZQE

**Comment by jjnether** [comment]
Song is very low level of volume for first 30 seconds. How about this as an alternative?

https://www.youtube.com/watch?v=VDbwTzcjZQE

**Comment by YP2743** [comment]
@jjnether Yes it's ok as an alternative.

**Comment by jjnether** [comment]
> @jjnether Yes it's ok as an alternative.

Ok, please edit your link with the new one!
