### ISSUE TITLE
[MOVIE]: Made in Abyss: Dawn of the Deep Soul (2020)

### ISSUE THREAD

**Issue by YP2743** [LizardByte/ThemerrDB#1222]
### Database URL

https://www.themoviedb.org/movie/573730?language=en

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=3SEhUVLRhIg

**Comment by jjnether** [comment]
@Emiliaaah any objections to this change?

**Comment by jjnether** [comment]
@YP2743 Any particular reason for this theme change?

**Comment by YP2743** [comment]
@jjnether sorry for the late reply i don't notice the question. I want to change it because for the first 30 seconds i think the one i suggest sounds more epic and fulfilling.
