### ISSUE TITLE
[MOVIE]: Steins;Gate: The Movie - Load Region of Déjà Vu (2013)

### ISSUE THREAD

**Issue by YP2743** [LizardByte/ThemerrDB#1227]
### Database URL

https://www.themoviedb.org/movie/225745-steins-gate?language=en

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=nz28xlfvqHE

**Comment by jjnether** [comment]
That video is the extended version and a bit long, is this one ok?

https://www.youtube.com/watch?v=nz28xlfvqHE

**Comment by YP2743** [comment]
@jjnether That's ok!

**Comment by jjnether** [comment]
> @jjnether That's ok!

Great, please edit your YouTube link with the new one
