### ISSUE TITLE
[MOVIE]: The Irregular at Magic High School: Reminiscence Arc ()

### ISSUE THREAD

**Issue by YP2743** [LizardByte/ThemerrDB#1233]
### Database URL

https://www.themoviedb.org/movie/1176167-mahouka-koukou-no-rettousei-tsuioku-hen?language=en

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=kqg0ii4ioKU

**Comment by ReenigneArcher** [comment]
I had to remove this item from the database as it is no longer available, or the id changed, on TheMovieDB.
