### ISSUE TITLE
[MOVIE]: The Last of the Mohicans (1992)

### ISSUE THREAD

**Issue by OcifferAction** [LizardByte/ThemerrDB#1239]
### Database URL

https://www.themoviedb.org/movie/9361

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=BrNpnTh4Ghs

**Comment by jjnether** [comment]
Theme is a bit soft for first 20 seconds and is a bit long, is this one ok instead?

https://www.youtube.com/watch?v=BrNpnTh4Ghs

**Comment by OcifferAction** [comment]
That works great, thanks

**Comment by jjnether** [comment]
> That works great, thanks

Awesome, please edit the link with the new video, then we can continue the workflow

**Comment by OcifferAction** [comment]
> > That works great, thanks
> 
> Awesome, please edit the link with the new video, then we can continue the workflow

Done
