### ISSUE TITLE
[MOVIE]: Moonfall (2022)

### ISSUE THREAD

**Issue by OcifferAction** [LizardByte/ThemerrDB#1267]
### Database URL

https://www.themoviedb.org/movie/406759

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=J7yDbSLXAK4&ab_channel=ThomasWander-Topic

**Comment by jjnether** [comment]
The link is in the middle of a playlist, which youtube-dl will just grab the first video of rather than your video. Please edit the link with your song, not in a playlist:

i.e. https://youtu.be/J7yDbSLXAK4?si=mStWJsigqAFBePxy

**Comment by OcifferAction** [comment]
Link updated
