### ISSUE TITLE
[MOVIE]: Dogtooth (2009)

### ISSUE THREAD

**Issue by garlik82** [LizardByte/ThemerrDB#1276]
### Database URL

https://www.themoviedb.org/movie/38810

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=mzUgC43Kksc

**Comment by jjnether** [comment]
@garlik82 This video is age restricted, please edit with a video that doesn't have this restriction

**Comment by garlik82** [comment]
> @garlik82 This video is age restricted, please edit with a video that doesn't have this restriction

updated
