### ISSUE TITLE
[MOVIE]: Eternal Sunshine of the Spotless Mind (2004)

### ISSUE THREAD

**Issue by garlik82** [LizardByte/ThemerrDB#1284]
### Database URL

https://www.themoviedb.org/movie/38-eternal-sunshine-of-the-spotless-mind

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=vC0CaGSwme0

**Comment by jjnether** [comment]
@garlik82 I believe your link for the database URL is wrong. Please edit, then the workflow can run
