### ISSUE TITLE
[MOVIE]: Forrest Gump (1994)

### ISSUE THREAD

**Issue by garlik82** [LizardByte/ThemerrDB#1288]
### Database URL

https://www.themoviedb.org/movie/13-forrest-gump

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=ehu2PsWgl0A

**Comment by jjnether** [comment]
The link you have is quite long, would you be able to edit it with a shorter version, such as:

https://www.youtube.com/watch?v=ehu2PsWgl0A

**Comment by garlik82** [comment]
> The link you have is quite long, would you be able to edit it with a shorter version, such as:
> 
> https://www.youtube.com/watch?v=ehu2PsWgl0A

OK. I'll have that in mind.

**Comment by jjnether** [comment]
> > The link you have is quite long, would you be able to edit it with a shorter version, such as:
> > https://www.youtube.com/watch?v=ehu2PsWgl0A
> 
> OK. I'll have that in mind.

If you're good with the alternative I suggested, please edit with the alternate link, then we'll continue the workflow

**Comment by garlik82** [comment]
> > > The link you have is quite long, would you be able to edit it with a shorter version, such as:
> > > https://www.youtube.com/watch?v=ehu2PsWgl0A
> > 
> > 
> > OK. I'll have that in mind.
> 
> If you're good with the alternative I suggested, please edit with the alternate link, then we'll continue the workflow

Done
