### ISSUE TITLE
[MOVIE]: High Life (2018)

### ISSUE THREAD

**Issue by garlik82** [LizardByte/ThemerrDB#1291]
### Database URL

https://www.themoviedb.org/movie/376865-high-life

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=tOHFktF5E1o

**Comment by jjnether** [comment]
The current link is pretty inaudible for the beginning. Would this be ok as an alternative?

https://www.youtube.com/watch?v=tOHFktF5E1o

**Comment by garlik82** [comment]
OK by me. Thanks

**Comment by jjnether** [comment]
> OK by me. Thanks

Ok, go ahead and edit it with the new theme, then we can continue the workflow

**Comment by garlik82** [comment]
> > OK by me. Thanks
> 
> Ok, go ahead and edit it with the new theme, then we can continue the workflow
 done
