### ISSUE TITLE
[MOVIE]: The Hobbit: The Desolation of Smaug (2013)

### ISSUE THREAD

**Issue by garlik82** [LizardByte/ThemerrDB#1292]
### Database URL

https://www.themoviedb.org/movie/57158-the-hobbit-the-desolation-of-smaug

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=TZM-O-jYovU

**Comment by jjnether** [comment]
@ind0r90 any opposition to this change?

**Comment by garlik82** [comment]
The other one is region locked I think.

**Comment by ReenigneArcher** [comment]
@garlik82 thanks for that info. Our check only validates that it's available in United States and it's difficult to check anything other than that.

**Comment by garlik82** [comment]
Yeah, I really can't tell if the one I chose is region locked or not either. The ones I find that are region locked I'll just download them myself no worries.

**Comment by ReenigneArcher** [comment]
I need to add a proxy option to both the plex and jellyfin plugins to help with this.
