### ISSUE TITLE
[MOVIE]: Mass (2021)

### ISSUE THREAD

**Issue by garlik82** [LizardByte/ThemerrDB#1304]
### Database URL

https://www.themoviedb.org/movie/423333-mass

### YouTube Theme Song Video URL

https://youtu.be/cpAAiOwT88Y?si=2wVV5kwgzwnniTAz

**Comment by jjnether** [comment]
@garlik82 Audio is pretty inaudible for the first 30 seconds. Can you edit with a different version which has noticeable audio within the first 15 seconds?

**Comment by garlik82** [comment]
Updated, same song but a little louder. See if that is ok please.
