### ISSUE TITLE
[MOVIE]: Space Cowboys (2000)

### ISSUE THREAD

**Issue by OcifferAction** [LizardByte/ThemerrDB#1335]
### Database URL

https://www.themoviedb.org/movie/5551-space-cowboys

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=e89A9tM0TYk

**Comment by jjnether** [comment]
Theme is a bit long. You ok to use this instead?

https://www.youtube.com/watch?v=e89A9tM0TYk

**Comment by OcifferAction** [comment]
That works! I've updated the link on the original post.
