### ISSUE TITLE
[MOVIE]: Newsies (1992)

### ISSUE THREAD

**Issue by primetime34** [LizardByte/ThemerrDB#1338]
### Database URL

https://www.themoviedb.org/movie/15300-newsies?language=en-US

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=fHk9AG6X6sQ

**Comment by ReenigneArcher** [comment]
We normally try to avoid using scenes from the movie itself. Do you think you find an alternative one that? You can just edit your issue with the new url.

**Comment by primetime34** [comment]
I went ahead and changed it to a different video that should work. Thanks!
