### ISSUE TITLE
[MOVIE]: 2001: A Space Odyssey (1968)

### ISSUE THREAD

**Issue by garlik82** [LizardByte/ThemerrDB#1340]
### Database URL

https://www.themoviedb.org/movie/62

### YouTube Theme Song Video URL

https://youtu.be/HhYhREdQBn0?si=yODqLL_758tAZT1e

**Comment by jjnether** [comment]
I know the main theme for this is iconic, but you don't really hear any noticeable audio until 15 seconds in, which kinda defeats the purpose. How do you feel about a different song from the movie?

i.e. https://youtu.be/HhYhREdQBn0?si=yODqLL_758tAZT1e

**Comment by garlik82** [comment]
My other pick would be the blue Danube but the issue would be the same so I guess I'm OK with that song.
Updated the link.
