### ISSUE TITLE
[MOVIE]: The Amazing Spider-Man (2012)

### ISSUE THREAD

**Issue by primetime34** [LizardByte/ThemerrDB#1362]
### Database URL

https://www.themoviedb.org/movie/1930

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=gcBhJjlgCgg

**Comment by jjnether** [comment]
Theme is a bit long, any alternative that is shorter?

i.e. https://youtu.be/r2e1qUKkoCg?si=dQHPHnCNxPgsKyOq

**Comment by primetime34** [comment]
I have updated it to another video. Thanks
