### ISSUE TITLE
[MOVIE]: The Amazing Spider-Man 2 (2014)

### ISSUE THREAD

**Issue by primetime34** [LizardByte/ThemerrDB#1363]
### Database URL

https://www.themoviedb.org/movie/102382

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=x6UZfZx3ChY

**Comment by jjnether** [comment]
Theme is quite long, any alternatives you might have that are shorter? Maybe:
https://youtu.be/j3Ifhzsa4L4?si=QrpxNTvgW__HfsLt

**Comment by primetime34** [comment]
I have updated to another video. Thanks
