### ISSUE TITLE
[MOVIE]: 30 Days of Night (2007)

### ISSUE THREAD

**Issue by OcifferAction** [LizardByte/ThemerrDB#1382]
### Database URL

https://www.themoviedb.org/movie/4513-30-days-of-night

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=Rh4NipJNeWM

**Comment by OcifferAction** [comment]
Link updated with proper one.

**Comment by jjnether** [comment]
The link is kinda just ambiance, no music theme. I guess this could be the theme, but wanted to check if there's an alternative with actual music?

**Comment by OcifferAction** [comment]
> The link is kinda just ambiance, no music theme. I guess this could be the theme, but wanted to check if there's an alternative with actual music?

I've updated the link with the best one I could find. The soundtrack has a lot of ambiance.
