### ISSUE TITLE
[MOVIE]: Armored (2009)

### ISSUE THREAD

**Issue by OcifferAction** [LizardByte/ThemerrDB#1426]
### Database URL

https://www.themoviedb.org/movie/4597-armored

### YouTube Theme Song Video URL

https://youtu.be/ORLZFdzlDZs?si=1AvtTsB-9gFKBV6C

**Comment by jjnether** [comment]
Barely any audio for first 20-30 sec, would you be able to replace with something else?

i.e. https://youtu.be/ORLZFdzlDZs?si=1AvtTsB-9gFKBV6C

**Comment by OcifferAction** [comment]
> Barely any audio for first 20-30 sec, would you be able to replace with something else?
> 
> i.e. https://youtu.be/ORLZFdzlDZs?si=1AvtTsB-9gFKBV6C

That works. I've updated the link.
