### ISSUE TITLE
[MOVIE]: Awakenings (1990)

### ISSUE THREAD

**Issue by OcifferAction** [LizardByte/ThemerrDB#1435]
### Database URL

https://www.themoviedb.org/movie/11005-awakenings

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=RAS1qgSGFGM

**Comment by jjnether** [comment]
Theme is a bit long, could this be a replacement?

https://www.youtube.com/watch?v=RAS1qgSGFGM

**Comment by OcifferAction** [comment]
> Theme is a bit long, could this be a replacement?
> 
> https://www.youtube.com/watch?v=RAS1qgSGFGM

That works great. I've updated the original link.
