### ISSUE TITLE
[MOVIE]: The Abyss (1989)

### ISSUE THREAD

**Issue by OcifferAction** [LizardByte/ThemerrDB#1436]
### Database URL

https://www.themoviedb.org/movie/2756-the-abyss

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=lXFSnwZLScY

**Comment by jjnether** [comment]
Link is a bit long, would this be an ok replacement?

https://www.youtube.com/watch?v=lXFSnwZLScY

**Comment by OcifferAction** [comment]
> Link is a bit long, would this be an ok replacement?
> 
> https://www.youtube.com/watch?v=lXFSnwZLScY

That works. I've updated the original link.
