### ISSUE TITLE
[MOVIE]: Yor, the Hunter from the Future (1983)

### ISSUE THREAD

**Issue by muzzymate** [LizardByte/ThemerrDB#1468]
### Database URL

https://www.themoviedb.org/movie/38219-il-mondo-di-yor

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=UTv9EZyKsuo

**Comment by jjnether** [comment]
Link is pretty poor quality, maybe use this instead?

https://www.youtube.com/watch?v=UTv9EZyKsuo

**Comment by muzzymate** [comment]
That other works for me. I chose the first one because of the length but the other for sure better quality audio.

**Comment by jjnether** [comment]
> That other works for me. I chose the first one because of the length but the other for sure better quality audio.

Yeah in this case, audio quality takes precedence. When you have time, go ahead and edit the link with the new one, then the workflow can continue.
