### ISSUE TITLE
[MOVIE]: Eddie the Eagle (2016)

### ISSUE THREAD

**Issue by primetime34** [LizardByte/ThemerrDB#1530]
### Database URL

https://www.themoviedb.org/movie/319888

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=R0_HYQaHjqY

**Comment by jjnether** [comment]
@primetime34  Theme is quite long, can you replace with a shorter one from the movie?

**Comment by primetime34** [comment]
I changed it for a shorter song. Thanks
