### ISSUE TITLE
[MOVIE]: Beauty and the Beast (1991)

### ISSUE THREAD

**Issue by OcifferAction** [LizardByte/ThemerrDB#1551]
### Database URL

https://www.themoviedb.org/movie/10020-beauty-and-the-beast

### YouTube Theme Song Video URL

https://youtu.be/JW81PFSsNZs?si=4O0AHoyN6YFMh6rP

**Comment by jjnether** [comment]
I know that version's in the credits, but I feel the original theme is more preferable?

https://youtu.be/JW81PFSsNZs?si=4O0AHoyN6YFMh6rP

**Comment by OcifferAction** [comment]
> I know that version's in the credits, but I feel the original theme is more preferable?
> 
> https://youtu.be/JW81PFSsNZs?si=4O0AHoyN6YFMh6rP

That works perfectly. I've updated the original link.
