### ISSUE TITLE
[MOVIE]: Bright (2017)

### ISSUE THREAD

**Issue by OcifferAction** [LizardByte/ThemerrDB#1583]
### Database URL

https://www.themoviedb.org/movie/400106-bright

### YouTube Theme Song Video URL

https://youtu.be/Gj6Qg90Dtc0?si=z95Op7IlUgbb3usp

**Comment by jjnether** [comment]
Theme is a bit long and starts quite soft, would an alternative like this work?

https://youtu.be/Gj6Qg90Dtc0?si=z95Op7IlUgbb3usp

**Comment by OcifferAction** [comment]
> Theme is a bit long and starts quite soft, would an alternative like this work?
> 
> https://youtu.be/Gj6Qg90Dtc0?si=z95Op7IlUgbb3usp

That works great. I've updated the original link.
