### ISSUE TITLE
[MOVIE]: The Big Short (2015)

### ISSUE THREAD

**Issue by OcifferAction** [LizardByte/ThemerrDB#1598]
### Database URL

https://www.themoviedb.org/movie/318846-the-big-short

### YouTube Theme Song Video URL

https://youtu.be/AVYNKsBqh7E?si=rooocHl58Hg5pRnj

**Comment by jjnether** [comment]
I think this song isn't really reflective of the general theme throughout, what do you think of this one instead?

https://youtu.be/AVYNKsBqh7E?si=rooocHl58Hg5pRnj

**Comment by OcifferAction** [comment]
> I think this song isn't really reflective of the general theme throughout, what do you think of this one instead?
> 
> https://youtu.be/AVYNKsBqh7E?si=rooocHl58Hg5pRnj

Beautiful song. I've updated the link.
