### ISSUE TITLE
[MOVIE]: The Village (2004)

### ISSUE THREAD

**Issue by muzzymate** [LizardByte/ThemerrDB#1611]
### Database URL

https://www.themoviedb.org/movie/6947-the-village

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=oTfh4K_kHho

**Comment by jjnether** [comment]
I'm a bit partial, but what do you think about this theme instead? One of my all time favorites:

https://www.youtube.com/watch?v=oTfh4K_kHho

**Comment by muzzymate** [comment]
I adore that score! So many good tracks.   

Edited original post with your suggestion.
