### ISSUE TITLE
[MOVIE]: Captain Phillips (2013)

### ISSUE THREAD

**Issue by OcifferAction** [LizardByte/ThemerrDB#1628]
### Database URL

https://www.themoviedb.org/movie/109424-captain-phillips

### YouTube Theme Song Video URL

https://youtu.be/fM5ylDGzFS0?si=utE852vzsZby8I2s

**Comment by jjnether** [comment]
That track is a bit long. Could you replace with an alternative?

i.e. https://youtu.be/fM5ylDGzFS0?si=utE852vzsZby8I2s

**Comment by OcifferAction** [comment]
> That track is a bit long. Could you replace with an alternative?
> 
> i.e. https://youtu.be/fM5ylDGzFS0?si=utE852vzsZby8I2s

That works. Ive updated the original link
