### ISSUE TITLE
[MOVIE]: Chasing Mavericks (2012)

### ISSUE THREAD

**Issue by OcifferAction** [LizardByte/ThemerrDB#1636]
### Database URL

https://www.themoviedb.org/movie/82684-chasing-mavericks

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=9DIBI-_3Bzg

**Comment by jjnether** [comment]
Theme is a bit long, would this work as an alternative?

https://www.youtube.com/watch?v=9DIBI-_3Bzg

**Comment by OcifferAction** [comment]
> Theme is a bit long, would this work as an alternative?
> 
> https://www.youtube.com/watch?v=9DIBI-_3Bzg

That works. I've updated the original link.
