### ISSUE TITLE
[MOVIE]: Dr. Goldfoot and the Girl Bombs (1966)

### ISSUE THREAD

**Issue by muzzymate** [LizardByte/ThemerrDB#1641]
### Database URL

https://www.themoviedb.org/movie/77076-le-spie-vengono-dal-semifreddo

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=pwJq3ClsUNk

**Comment by jjnether** [comment]
How about this video instead? The one you have is barely audible

https://www.youtube.com/watch?v=pwJq3ClsUNk

**Comment by muzzymate** [comment]
> How about this video instead? 

Replaced.
