### ISSUE TITLE
[MOVIE]: Christopher Robin (2018)

### ISSUE THREAD

**Issue by primetime34** [LizardByte/ThemerrDB#1653]
### Database URL

https://www.themoviedb.org/movie/420814

### YouTube Theme Song Video URL

https://youtu.be/9plgre-131M?si=PzR0YsIDplzjL36r

**Comment by jjnether** [comment]
What do you think about this theme instead? I feel better listening than the song with lyrics

https://youtu.be/9plgre-131M?si=PzR0YsIDplzjL36r

**Comment by primetime34** [comment]
Works for me. Thanks
