### ISSUE TITLE
[MOVIE]: Fiddler on the Roof (1971)

### ISSUE THREAD

**Issue by primetime34** [LizardByte/ThemerrDB#1654]
### Database URL

https://www.themoviedb.org/movie/14811

### YouTube Theme Song Video URL

https://youtu.be/NZBLDkVpHSA?si=OFnOurXoWkOKc9fF

**Comment by jjnether** [comment]
What do you think about this theme instead? Just as it's more one of the themes rather than the violin solo

https://youtu.be/NZBLDkVpHSA?si=OFnOurXoWkOKc9fF

**Comment by primetime34** [comment]
Works for me...I've changed it
