### ISSUE TITLE
[MOVIE]: Ace Ventura: Pet Detective (1994)

### ISSUE THREAD

**Issue by licotto** [LizardByte/ThemerrDB#1661]
### Database URL

https://www.themoviedb.org/movie/3049

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=gHTEFS-imKY

**Comment by ReenigneArcher** [comment]
When a playlist is added, we take the first video from the playlist, which is what caused this exception. I've corrected it, but please keep that in mind for future requests. https://github.com/LizardByte/ThemerrDB/blob/master/docs/YouTube_Share.md#youtube-urls
