### ISSUE TITLE
[MOVIE]: Deepwater Horizon (2016)

### ISSUE THREAD

**Issue by OcifferAction** [LizardByte/ThemerrDB#1742]
### Database URL

https://www.themoviedb.org/movie/296524-deepwater-horizon

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=yi6huWojgtg

**Comment by ReenigneArcher** [comment]
The Database URL is invalid

**Comment by OcifferAction** [comment]
> The Database URL is invalid

My apologies. Database URL has been updated to the correct one.
