### ISSUE TITLE
[MOVIE]: Dolphin Tale (2011)

### ISSUE THREAD

**Issue by OcifferAction** [LizardByte/ThemerrDB#1761]
### Database URL

https://www.themoviedb.org/movie/62837-dolphin-tale

### YouTube Theme Song Video URL

https://youtu.be/tsLX61JFCf4?si=BibuCGjoiIyXPhfc

**Comment by jjnether** [comment]
Theme is a bit long, how about this one?

https://youtu.be/tsLX61JFCf4?si=BibuCGjoiIyXPhfc
