### ISSUE TITLE
[MOVIE]: Don't Breathe 2 (2021)

### ISSUE THREAD

**Issue by OcifferAction** [LizardByte/ThemerrDB#1766]
### Database URL

https://www.themoviedb.org/movie/482373-don-t-breathe-2

### YouTube Theme Song Video URL

https://youtu.be/tXMFL0OOvj8?si=iHwKP3u4mpKfGr3E

**Comment by jjnether** [comment]
Theme is a bit long, how about this one?

https://youtu.be/tXMFL0OOvj8?si=iHwKP3u4mpKfGr3E

**Comment by OcifferAction** [comment]
> Theme is a bit long, how about this one?
> 
> https://youtu.be/tXMFL0OOvj8?si=iHwKP3u4mpKfGr3E

That works great. I've updated the original URL
