### ISSUE TITLE
[MOVIE]: Doctor Strange in the Multiverse of Madness (2022)

### ISSUE THREAD

**Issue by LetsGoDude** [LizardByte/ThemerrDB#178]
### TheMovieDB URL

https://www.themoviedb.org/movie/453395-doctor-strange-in-the-multiverse-of-madness

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=WXr1Fd5FDIo

**Comment by ReenigneArcher** [comment]
Thanks for all the submissions! I'm really glad you're enjoying Themerr.

Just FYI, it might take a couple of days to get to these ones (but please keep submitting them). I'm working on a website to display the database, and I want to add a little bit more metadata to track database completion percentage and things like that.

P.S. are you on our discord server?

**Comment by LetsGoDude** [comment]
Yes I am! I did the bug test with you for the new agent :-)
