### ISSUE TITLE
[MOVIE]: Dungeons & Dragons (2000)

### ISSUE THREAD

**Issue by OcifferAction** [LizardByte/ThemerrDB#1781]
### Database URL

https://www.themoviedb.org/movie/11849-dungeons-dragons

### YouTube Theme Song Video URL

https://youtu.be/0EgG3iGaeUE?si=dfFot4_qymJSjEy1

**Comment by jjnether** [comment]
The theme is a bit long, how is this one instead?

https://youtu.be/0EgG3iGaeUE?si=dfFot4_qymJSjEy1

**Comment by OcifferAction** [comment]
> The theme is a bit long, how is this one instead?
> 
> https://youtu.be/0EgG3iGaeUE?si=dfFot4_qymJSjEy1

That works great. I've updated the original URL
