### ISSUE TITLE
[MOVIE]: The Divide (2012)

### ISSUE THREAD

**Issue by OcifferAction** [LizardByte/ThemerrDB#1794]
### Database URL

https://www.themoviedb.org/movie/38541-the-divide

### YouTube Theme Song Video URL

https://youtu.be/7ohY9dI2uks?si=SUAY4mk0TCthxYq8

**Comment by jjnether** [comment]
That theme is a bit long, and it seems it's not the exact version from the movie. How bout this one instead?

https://youtu.be/7ohY9dI2uks?si=SUAY4mk0TCthxYq8

**Comment by OcifferAction** [comment]
> That theme is a bit long, and it seems it's not the exact version from the movie. How bout this one instead?
> 
> https://youtu.be/7ohY9dI2uks?si=SUAY4mk0TCthxYq8

That works perfectly. I've updated the original link.
