### ISSUE TITLE
[MOVIE]: The Dry (2021)

### ISSUE THREAD

**Issue by OcifferAction** [LizardByte/ThemerrDB#1796]
### Database URL

https://www.themoviedb.org/movie/567797-the-dry

### YouTube Theme Song Video URL

https://youtu.be/lorA7WVEA7o?si=8-qrTnx2oZtJ5QvM

**Comment by jjnether** [comment]
It's mostly ambiance for the first 20 seconds, would this theme be ok instead?

https://youtu.be/lorA7WVEA7o?si=8-qrTnx2oZtJ5QvM
