### ISSUE TITLE
[MOVIE]: Demon Slayer -Kimetsu no Yaiba- The Movie: Mugen Train (2020)

### ISSUE THREAD

**Issue by YP2743** [LizardByte/ThemerrDB#1811]
### Database URL

https://www.themoviedb.org/movie/635302?language=en

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=jwriFosLRww

**Comment by jjnether** [comment]
The video you added has sounds of waves at the beginning. Here's one that goes directly into the song, if you can make the change:

https://www.youtube.com/watch?v=jwriFosLRww

**Comment by YP2743** [comment]
@jjnether Thanks for the suggestion. I will change it now.
