### ISSUE TITLE
[MOVIE]: Escape Room: Tournament of Champions (2021)

### ISSUE THREAD

**Issue by OcifferAction** [LizardByte/ThemerrDB#1850]
### Database URL

https://www.themoviedb.org/movie/585216-escape-room-tournament-of-champions

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=zPWKM1KXMB4

**Comment by jjnether** [comment]
Music doesn't come in till about 15 sec in, would this be alright instead?

https://www.youtube.com/watch?v=zPWKM1KXMB4

**Comment by OcifferAction** [comment]
> Music doesn't come in till about 15 sec in, would this be alright instead?
> 
> https://www.youtube.com/watch?v=zPWKM1KXMB4

Yep, that works. I've updated the original link.
