### ISSUE TITLE
[MOVIE]: 3 Men and a Baby (1987)

### ISSUE THREAD

**Issue by carbonbaseunit** [LizardByte/ThemerrDB#1854]
### Database URL

https://www.themoviedb.org/movie/12154-three-men-and-a-baby

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=fOvp6ElnRfA

**Comment by ReenigneArcher** [comment]
This theme is too long. Please find an alternative, edit your issue, and let us know when that's complete. Thanks.

https://github.com/LizardByte/ThemerrDB/blob/master/docs/Theme_Guidelines.md#theme-length

**Comment by ReenigneArcher** [comment]
Could you address this one before adding more?

**Comment by jjnether** [comment]
@carbonbaseunit how about this song from the movie?

https://www.youtube.com/watch?v=fOvp6ElnRfA

**Comment by carbonbaseunit** [comment]
edited
