### ISSUE TITLE
[MOVIE]: Cloud Atlas (2012)

### ISSUE THREAD

**Issue by tylerreed19** [LizardByte/ThemerrDB#1929]
### Database URL

https://www.themoviedb.org/movie/83542-cloud-atlas

### YouTube Theme Song Video URL

https://youtu.be/gBJ5auSU4io

**Comment by jjnether** [comment]
That theme is a bit long, how about this one instead?

https://youtu.be/KegOBMIZRho?si=EsEqY1R4KgNc_nsD

**Comment by tylerreed19** [comment]
> That theme is a bit long, how about this one instead?
> 
> https://youtu.be/KegOBMIZRho?si=EsEqY1R4KgNc_nsD

Yeah! That's actually better. I like that one.
