### ISSUE TITLE
[MOVIE]: Frozen II (2019)

### ISSUE THREAD

**Issue by OcifferAction** [LizardByte/ThemerrDB#1955]
### Database URL

https://www.themoviedb.org/movie/330457-frozen-ii

### YouTube Theme Song Video URL

https://youtu.be/ThMR1LPGt5E?si=kg-Axz3lmDbdYnvM

**Comment by jjnether** [comment]
That is actually from Frozen, not Frozen II. How about this instead?

https://youtu.be/ThMR1LPGt5E?si=kg-Axz3lmDbdYnvM

**Comment by OcifferAction** [comment]
That works well. I've updated the original link.

**Comment by OcifferAction** [comment]
> That is actually from Frozen, not Frozen II. How about this instead?
> 
> https://youtu.be/ThMR1LPGt5E?si=kg-Axz3lmDbdYnvM

That works well. I've updated the original link.
