### ISSUE TITLE
[MOVIE]: Fury (2014)

### ISSUE THREAD

**Issue by OcifferAction** [LizardByte/ThemerrDB#1956]
### Database URL

https://www.themoviedb.org/movie/228150-fury

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=xhfo-lB6JS8

**Comment by jjnether** [comment]
That theme has mostly ambiance for the first part, how about this one instead?

https://www.youtube.com/watch?v=xhfo-lB6JS8

**Comment by OcifferAction** [comment]
> That theme has mostly ambiance for the first part, how about this one instead?
> 
> https://www.youtube.com/watch?v=xhfo-lB6JS8

Perfect. I've updated the original link.
