### ISSUE TITLE
[MOVIE]: Pirates of the Caribbean: Dead Man's Chest (2006)

### ISSUE THREAD

**Issue by zdimension** [LizardByte/ThemerrDB#2011]
### Database URL

https://www.themoviedb.org/movie/58

### YouTube Theme Song Video URL

https://youtu.be/8reiuz1xNfQ

**Comment by jjnether** [comment]
How about this theme instead? Just one not from the opening sequence.

https://youtu.be/PPs416S7OFU?si=dLnQQIMFjwpTEcfL

**Comment by jjnether** [comment]
Sorry, I got mixed up with these movies, I placed the wrong link in a comment. Could you edit one more time with maybe this theme?

https://youtu.be/8reiuz1xNfQ?si=jR0ji689INhGYDad
