### ISSUE TITLE
[MOVIE]: Pirates of the Caribbean: At World's End (2007)

### ISSUE THREAD

**Issue by zdimension** [LizardByte/ThemerrDB#2012]
### Database URL

https://www.themoviedb.org/movie/285

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=dfgJYRdNwDE

**Comment by jjnether** [comment]
What do you think about this theme instead? I think might be better to have a main theme not from the opening sequence if possible.

https://www.youtube.com/watch?v=dfgJYRdNwDE
