### ISSUE TITLE
[MOVIE]: Pirates of the Caribbean: On Stranger Tides (2011)

### ISSUE THREAD

**Issue by zdimension** [LizardByte/ThemerrDB#2013]
### Database URL

https://www.themoviedb.org/movie/1865

### YouTube Theme Song Video URL

https://youtu.be/PPs416S7OFU

**Comment by jjnether** [comment]
How about this theme instead? Just one not from the opening sequence.

https://youtu.be/PPs416S7OFU?si=dLnQQIMFjwpTEcfL
