### ISSUE TITLE
[MOVIE]: Pirates of the Caribbean: Dead Men Tell No Tales (2017)

### ISSUE THREAD

**Issue by zdimension** [LizardByte/ThemerrDB#2014]
### Database URL

https://www.themoviedb.org/movie/166426

### YouTube Theme Song Video URL

https://youtu.be/LzJ4eVcHaHs

**Comment by jjnether** [comment]
What do you think about this theme instead? I prefer not to add the opening sequence from movies if possible

https://youtu.be/LzJ4eVcHaHs?si=uaVfojrcxfL5VBk8

**Comment by zdimension** [comment]
> What do you think about this theme instead? I prefer not to add the opening sequence from movies, but rather a main theme if possible
> 
> https://youtu.be/LzJ4eVcHaHs?si=uaVfojrcxfL5VBk8

Yeah, that one is nice
