### ISSUE TITLE
[MOVIE]: Platoon (1986)

### ISSUE THREAD

**Issue by carbonbaseunit** [LizardByte/ThemerrDB#2046]
### Database URL

https://www.themoviedb.org/movie/792-platoon

### YouTube Theme Song Video URL

https://youtu.be/asa1_EBCbVM?si=Tyj9VMUSmFB5tYF2

**Comment by ReenigneArcher** [comment]
Could you select something shorter? Not too much shows up on a youtube search. Here's a list of songs that appear in the movie. https://www.tunefind.com/movie/platoon-1987
