### ISSUE TITLE
[MOVIE]: Star Trek II: The Wrath of Khan (1982)

### ISSUE THREAD

**Issue by carbonbaseunit** [LizardByte/ThemerrDB#2048]
### Database URL

https://www.themoviedb.org/movie/154-star-trek-ii-the-wrath-of-khan

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=sofU3EMa4xc

**Comment by carbonbaseunit** [comment]
Edited

**Comment by ReenigneArcher** [comment]
Duplicate
