### ISSUE TITLE
[MOVIE]: Star Trek III: The Search for Spock (1984)

### ISSUE THREAD

**Issue by carbonbaseunit** [LizardByte/ThemerrDB#2049]
### Database URL

https://www.themoviedb.org/movie/157-star-trek-iii-the-search-for-spock

### YouTube Theme Song Video URL

https://youtu.be/xccJAIf8ukg?si=VioAjEAK1pSCaa6a

**Comment by carbonbaseunit** [comment]
I cannot.

**Comment by ReenigneArcher** [comment]
The length is pretty far outside our acceptable range. https://github.com/LizardByte/ThemerrDB/blob/master/docs/Theme_Guidelines.md#theme-length

**Comment by carbonbaseunit** [comment]
OK.  I found something
