### ISSUE TITLE
[MOVIE]: Star Trek IV: The Voyage Home (1986)

### ISSUE THREAD

**Issue by carbonbaseunit** [LizardByte/ThemerrDB#2050]
### Database URL

https://www.themoviedb.org/movie/168-star-trek-iv-the-voyage-home

### YouTube Theme Song Video URL

https://youtu.be/QYuAdOWVcEc?si=HcWdyJtXVJN89ZEh

**Comment by ReenigneArcher** [comment]
This is the same theme already in the database.
