### ISSUE TITLE
[MOVIE COLLECTION]: Star Wars Collection

### ISSUE THREAD

**Issue by carbonbaseunit** [LizardByte/ThemerrDB#2057]
### Database URL

https://www.themoviedb.org/collection/10-star-wars-collection

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=VRNjedp8o-c

**Comment by ReenigneArcher** [comment]
How about this shorter version? https://www.youtube.com/watch?v=VRNjedp8o-c

**Comment by carbonbaseunit** [comment]
Edited
