### ISSUE TITLE
[MOVIE COLLECTION]: Indiana Jones Collection

### ISSUE THREAD

**Issue by carbonbaseunit** [LizardByte/ThemerrDB#2058]
### Database URL

https://www.themoviedb.org/collection/84-indiana-jones-collection

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=IgncJgSbbck

**Comment by ReenigneArcher** [comment]
How about this shorter, and original version? https://www.youtube.com/watch?v=IgncJgSbbck

If you agree, please edit your issue with the new url.

Thanks!

Also, a duplicate of #2118 so whoever edits first will get accepted.

**Comment by carbonbaseunit** [comment]
Edited
