### ISSUE TITLE
[MOVIE]: All the President's Men (1976)

### ISSUE THREAD

**Issue by carbonbaseunit** [LizardByte/ThemerrDB#2061]
### Database URL

https://www.themoviedb.org/movie/891-all-the-president-s-men

### YouTube Theme Song Video URL

https://youtu.be/_Acj1gHFinE?si=hztN3dPo55Tkihog

**Comment by ReenigneArcher** [comment]
This seems to be a single video with many songs. Could you select something shorter?

**Comment by carbonbaseunit** [comment]
Edited
