### ISSUE TITLE
[MOVIE]: Marathon Man (1976)

### ISSUE THREAD

**Issue by carbonbaseunit** [LizardByte/ThemerrDB#2065]
### Database URL

https://www.themoviedb.org/movie/10518-marathon-man

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=_vioJmM2phw

**Comment by ReenigneArcher** [comment]
How about this shorter version? https://www.youtube.com/watch?v=_vioJmM2phw

**Comment by carbonbaseunit** [comment]
Edited
