### ISSUE TITLE
[MOVIE]: Bob Ross: Happy Accidents, Betrayal & Greed (2021)

### ISSUE THREAD

**Issue by Cjkeenan** [LizardByte/ThemerrDB#2094]
### Database URL

https://www.themoviedb.org/movie/853354

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=ZenCYatQFPY

**Comment by Cjkeenan** [comment]
Cannot find the "official" theme song, but this should be good since it was the theme song of his actual show.

**Comment by Cjkeenan** [comment]
I saw that as well, it was just the credit song and definitely not as recognizable as the one I posted, so it depends on how you want to handle something that doesn't have an exact match. I could not find the title song anywhere.

**Comment by ReenigneArcher** [comment]
There's no rule that it must be the title song, but there is one where it has to be recognizable from the film (not from a related film or show).

Credit music is a common choice for many of our themes.
