### ISSUE TITLE
[MOVIE COLLECTION]: Indiana Jones Collection

### ISSUE THREAD

**Issue by Cjkeenan** [LizardByte/ThemerrDB#2118]
### Database URL

https://www.themoviedb.org/collection/84

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=bC77czRbjd0

**Comment by ReenigneArcher** [comment]
How about this shorter, and original version? https://www.youtube.com/watch?v=IgncJgSbbck

If you agree, please edit your issue with the new url.

Thanks!

**Comment by ReenigneArcher** [comment]
Added by another user
