### ISSUE TITLE
[MOVIE COLLECTION]: Jurassic Park Collection

### ISSUE THREAD

**Issue by Cjkeenan** [LizardByte/ThemerrDB#2120]
### Database URL

https://www.themoviedb.org/collection/328

### YouTube Theme Song Video URL

https://youtu.be/3GE4yTN5_Sk

**Comment by ReenigneArcher** [comment]
Please select something shorter, and edit your original issue.

https://github.com/LizardByte/ThemerrDB/blob/master/docs/Theme_Guidelines.md#theme-length

**Comment by jjnether** [comment]
How about this?

https://youtu.be/3GE4yTN5_Sk
