### ISSUE TITLE
[MOVIE]: The Matrix Reloaded (2003)

### ISSUE THREAD

**Issue by Cjkeenan** [LizardByte/ThemerrDB#2122]
### Database URL

https://www.themoviedb.org/movie/604

### YouTube Theme Song Video URL

https://youtu.be/xJgrLGxlxAw?si=GPmbve9ZbiFLKRsq

**Comment by ReenigneArcher** [comment]
I'm not that familiar with these films, so I can't speak to that. In any event, the theme in your original issue is far too long.

**Comment by jjnether** [comment]
How about this theme instead?

https://youtu.be/xJgrLGxlxAw?si=GPmbve9ZbiFLKRsq
