### ISSUE TITLE
[TV SHOW]: The Falcon and the Winter Soldier (2021)

### ISSUE THREAD

**Issue by LetsGoDude** [LizardByte/ThemerrDB#215]
### Database URL

https://www.themoviedb.org/tv/88396-falcon-winter-soldier

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=h_K7cbXT0BY

**Comment by ReenigneArcher** [comment]
ThemerrDB does not currently accept TV shows. Would this feature be of interest?

**Comment by ind0r90** [comment]
if i can add something on my side this feature is not interesting because plex has this feature already built in not for every tv show but its fine

**Comment by TownyMontana** [comment]
> ThemerrDB does not currently accept TV shows. Would this feature be of interest?

This would be awesome. I would love to see Background Music for TV Shows

**Comment by ReenigneArcher** [comment]
I had left this open as I am planning to add TV theme support.

**Comment by ReenigneArcher** [comment]
@LizardByte-bot approve

**Comment by ReenigneArcher** [comment]
TV Show support has been added to the DB now. It isn't really beneficial to Plex, but will be for Jellyfin and Kodi.
