### ISSUE TITLE
[MOVIE]: The Visitors (1993)

### ISSUE THREAD

**Issue by zdimension** [LizardByte/ThemerrDB#2191]
### Database URL

https://www.themoviedb.org/movie/11687

### YouTube Theme Song Video URL

https://youtu.be/vfAoMLHe03w

**Comment by zdimension** [comment]
I edited the URL in the issue (to https://youtube.be/vfAoMLHe03w) but it doesn't seem like the bot caught up

**Comment by ReenigneArcher** [comment]
We have to manually re-label the issue.

**Comment by ReenigneArcher** [comment]
I get a 404 error on this one.

**Comment by zdimension** [comment]
Fixed
