### ISSUE TITLE
[MOVIE]: Zombieland: Double Tap (2019)

### ISSUE THREAD

**Issue by tylerbickel** [LizardByte/ThemerrDB#221]
### TheMovieDB URL

https://www.themoviedb.org/movie/338967

### YouTube Theme Song Video URL

https://youtu.be/wLoWd2KyUro

**Comment by ReenigneArcher** [comment]
Same as #220 ... which one to keep?

**Comment by tylerbickel** [comment]
Used the wrong YouTube link so this one. Thought the newer one would update the first.
________________________________

**Comment by ReenigneArcher** [comment]
Okay, nope it doesn't update other issues. In the future you can edit the issue, so long as you keep the formatting correct.
