### ISSUE TITLE
[MOVIE]: Godzilla (1954)

### ISSUE THREAD

**Issue by carbonbaseunit** [LizardByte/ThemerrDB#2239]
### Database URL

https://www.themoviedb.org/movie/1678?language=en-US

### YouTube Theme Song Video URL

https://youtu.be/ZYnT-Nuc5Y0?si=OS034hZvVNrGPpsH

**Comment by jjnether** [comment]
Theme doesn't start until about 40 sec in, would you be able to replace with one that starts earlier?

**Comment by carbonbaseunit** [comment]
Edited
