### ISSUE TITLE
[MOVIE]: Akira (1988)

### ISSUE THREAD

**Issue by carbonbaseunit** [LizardByte/ThemerrDB#2245]
### Database URL

https://www.themoviedb.org/movie/149-akira?language=en-US

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=o_I_2sDzc18

**Comment by jjnether** [comment]
How about this one without the loud lightning effects for the first 15 sec?

https://www.youtube.com/watch?v=o_I_2sDzc18
