### ISSUE TITLE
[MOVIE]: A Most Violent Year (2014)

### ISSUE THREAD

**Issue by carbonbaseunit** [LizardByte/ThemerrDB#2269]
### Database URL

https://www.themoviedb.org/movie/241239-a-most-violent-year?language=en-US

### YouTube Theme Song Video URL

https://youtu.be/wLPlHpAch8s?si=yrTbaMBcm4ZvhuJz

**Comment by jjnether** [comment]
Audio is barely audible, how about this instead?

https://youtu.be/wLPlHpAch8s?si=yrTbaMBcm4ZvhuJz
