### ISSUE TITLE
[MOVIE]: A Nightmare on Elm Street: The Dream Child (1989)

### ISSUE THREAD

**Issue by carbonbaseunit** [LizardByte/ThemerrDB#2275]
### Database URL

https://www.themoviedb.org/movie/10160-a-nightmare-on-elm-street-the-dream-child?language=en-US

### YouTube Theme Song Video URL

https://youtu.be/IJraacUy51U?si=Xwe10-564Pj_iJ0Q

**Comment by jjnether** [comment]
Please try to address your outstanding previous requests, then feel free to submit more

**Comment by carbonbaseunit** [comment]
Got it.  Done
