### ISSUE TITLE
[MOVIE]: All the Devil's Men (2018)

### ISSUE THREAD

**Issue by carbonbaseunit** [LizardByte/ThemerrDB#2300]
### Database URL

https://www.themoviedb.org/movie/481203-all-the-devil-s-men?language=en-US

### YouTube Theme Song Video URL

https://youtu.be/xpmkBevpy28?si=wyMGyC5O4hqSWcK0

**Comment by jjnether** [comment]
No music comes in for about a min, how about this instead?

https://youtu.be/xpmkBevpy28?si=wyMGyC5O4hqSWcK0
