### ISSUE TITLE
[MOVIE]: Altered States (1980)

### ISSUE THREAD

**Issue by carbonbaseunit** [LizardByte/ThemerrDB#2306]
### Database URL

https://www.themoviedb.org/movie/11542-altered-states?language=en-US

### YouTube Theme Song Video URL

https://youtu.be/leWRpTl8Wys?si=t1s279u00vXwXTMm

**Comment by jjnether** [comment]
The theme you have is very difficult to hear for a while, how about this instead?

https://youtu.be/leWRpTl8Wys?si=t1s279u00vXwXTMm
