### ISSUE TITLE
[MOVIE]: At Close Range (1986)

### ISSUE THREAD

**Issue by carbonbaseunit** [LizardByte/ThemerrDB#2366]
### Database URL

https://www.themoviedb.org/movie/13715

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=71P-bQ8hU1Q

**Comment by jjnether** [comment]
@carbonbaseunit video is unavailable, please edit theme with a different link

**Comment by LetsGoDude** [comment]
how about this one? @jjnether @carbonbaseunit 
https://www.youtube.com/watch?v=71P-bQ8hU1Q
its a soundtrack from the movie.

**Comment by ReenigneArcher** [comment]
@LizardByte-bot edit https://www.youtube.com/watch?v=71P-bQ8hU1Q

**Comment by jjnether** [comment]
@LizardByte-bot approve
