### ISSUE TITLE
[MOVIE COLLECTION]: 28 Days/Weeks Later Collection

### ISSUE THREAD

**Issue by carbonbaseunit** [LizardByte/ThemerrDB#2368]
### Database URL

https://www.themoviedb.org/collection/1565

### YouTube Theme Song Video URL

https://youtu.be/FRvYglZr_zQ?si=4eWq72BNjCJ62eI8

**Comment by jjnether** [comment]
The first minute is mostly just sounds, not really music. How about this theme instead?

https://youtu.be/FRvYglZr_zQ?si=4eWq72BNjCJ62eI8
