### ISSUE TITLE
[MOVIE]: Funny People (2009)

### ISSUE THREAD

**Issue by OcifferAction** [LizardByte/ThemerrDB#2371]
### Database URL

https://www.themoviedb.org/movie/20829-funny-people

### YouTube Theme Song Video URL

https://youtu.be/h-KNQA-sYxQ?si=z0olqNxnlne_vvRX

**Comment by jjnether** [comment]
Theme is a bit long, how about this one instead?

https://youtu.be/h-KNQA-sYxQ?si=z0olqNxnlne_vvRX

**Comment by OcifferAction** [comment]
> Theme is a bit long, how about this one instead?
> 
> https://youtu.be/h-KNQA-sYxQ?si=z0olqNxnlne_vvRX

That works. I've updated the original link.
