### ISSUE TITLE
[MOVIE]: Crocodile Dundee (1986)

### ISSUE THREAD

**Issue by OcifferAction** [LizardByte/ThemerrDB#2395]
### Database URL

https://www.themoviedb.org/movie/9671-crocodile-dundee

### YouTube Theme Song Video URL

https://youtu.be/H4T2XdcrptA?si=DjnQKXsasNw0O0dt

**Comment by jjnether** [comment]
It is preferred that the song is not from the opening sequence. How about this theme instead?

https://youtu.be/H4T2XdcrptA?si=DjnQKXsasNw0O0dt

**Comment by OcifferAction** [comment]
> It is preferred that the song is not from the opening sequence. How about this theme instead?
> 
> https://youtu.be/H4T2XdcrptA?si=DjnQKXsasNw0O0dt

That works. I've updated the original link.
