### ISSUE TITLE
[MOVIE]: Dark Phoenix (2019)

### ISSUE THREAD

**Issue by tylerbickel** [LizardByte/ThemerrDB#241]
### TheMovieDB URL

https://www.themoviedb.org/movie/320288

### YouTube Theme Song Video URL

https://youtu.be/EBRvEPT2Nrg

**Comment by ReenigneArcher** [comment]
This one is quite long and takes about a minute before there's much happening in the song. Would you opposed to choosing something else?

**Comment by tylerbickel** [comment]
Picked something different.
