### ISSUE TITLE
[MOVIE]: Commando (1985)

### ISSUE THREAD

**Issue by anonymouscat888** [LizardByte/ThemerrDB#2424]
### Database URL

https://www.themoviedb.org/movie/10999

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=pwhcJiTfYA4

**Comment by jjnether** [comment]
@anonymouscat888 You've linked the playlist. The workflow will only grab the first video from the playlist, so please edit the link for only the video so it grabs the proper theme. More info [here](https://github.com/LizardByte/ThemerrDB/blob/master/docs/YouTube_Share.md)
