### ISSUE TITLE
[MOVIE]: Boiler Room (2000)

### ISSUE THREAD

**Issue by anonymouscat888** [LizardByte/ThemerrDB#2429]
### Database URL

https://www.themoviedb.org/movie/14181

### YouTube Theme Song Video URL

https://youtu.be/jg8e2wctnIU?si=kN-8bDzIbh0K4P4U

**Comment by jjnether** [comment]
You listed a very short theme that doesn't really have music. How about this instead?

https://youtu.be/jg8e2wctnIU?si=kN-8bDzIbh0K4P4U
