### ISSUE TITLE
[MOVIE]: Blade (1998)

### ISSUE THREAD

**Issue by anonymouscat888** [LizardByte/ThemerrDB#2430]
### Database URL

https://www.themoviedb.org/movie/36647

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=4e2XhbA_3yQ

**Comment by jjnether** [comment]
@anonymouscat888 For your videos with exceptions, please edit with a new video that is not private and is available, then we can run the workflow again

**Comment by jjnether** [comment]
@anonymouscat888 Please remove your text from the field where the youtube link should go, only have the youtube link there, and we can run the workflow again
