### ISSUE TITLE
[MOVIE]: Barnyard (2006)

### ISSUE THREAD

**Issue by anonymouscat888** [LizardByte/ThemerrDB#2432]
### Database URL

https://www.themoviedb.org/movie/9907

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=iKhWmVR6t-M

**Comment by anonymouscat888** [comment]
Trying this one again...

https://www.youtube.com/watch?v=iKhWmVR6t-M

**Comment by jjnether** [comment]
@anonymouscat888 Please remove your text from the field where the youtube link should go, only have the youtube link there, and we can run the workflow again
