### ISSUE TITLE
[MOVIE]: Bad Moms (2016)

### ISSUE THREAD

**Issue by anonymouscat888** [LizardByte/ThemerrDB#2433]
### Database URL

https://www.themoviedb.org/movie/376659

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=W50HtcPAeSs

**Comment by anonymouscat888** [comment]
Trying this one again...

https://www.youtube.com/watch?v=YCnVGco4dyU&list=PL8Ug7BOOE4K6-yHCDVPpm3M0KfiBh2TfB&index=4

**Comment by jjnether** [comment]
@anonymouscat888 Please remove your text from the field where the youtube link should go, only have the youtube link there, and we can run the workflow again

**Comment by jjnether** [comment]
@anonymouscat888 you linked a video in a playlist. Please edit with a linked video that isn't in a playlist, as only the first video would be grabbed. (see [here](https://github.com/LizardByte/ThemerrDB/blob/master/docs/YouTube_Share.md) for more details.

**Comment by jjnether** [comment]
@anonymouscat888 theme is a bit long, how about this instead? Same song, but shorter

https://www.youtube.com/watch?v=W50HtcPAeSs
