### ISSUE TITLE
[MOVIE]: Ace Ventura: When Nature Calls (1995)

### ISSUE THREAD

**Issue by anonymouscat888** [LizardByte/ThemerrDB#2435]
### Database URL

https://www.themoviedb.org/movie/9273

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=hGugEQUYTl8

**Comment by jjnether** [comment]
@anonymouscat888 you linked a video in a playlist. Please edit with a linked video that isn't in a playlist, as only the first video would be grabbed. (see [here](https://github.com/LizardByte/ThemerrDB/blob/master/docs/YouTube_Share.md) for more details)
