### ISSUE TITLE
[MOVIE]: 9/11: Inside the President's War Room (2021)

### ISSUE THREAD

**Issue by sahara101** [LizardByte/ThemerrDB#2447]
### Database URL

https://www.themoviedb.org/movie/848981

### YouTube Theme Song Video URL

https://youtu.be/LUz0V2MsjEc?si=dqx0y8qLTJ9_F2uw

**Comment by jjnether** [comment]
@sahara101 theme is quite long, how about this one instead?

https://youtu.be/LUz0V2MsjEc?si=dqx0y8qLTJ9_F2uw

**Comment by sahara101** [comment]
Edited
