### ISSUE TITLE
[MOVIE]: Gods (2014)

### ISSUE THREAD

**Issue by sahara101** [LizardByte/ThemerrDB#2459]
### Database URL

https://www.themoviedb.org/movie/298040

### YouTube Theme Song Video URL

https://youtu.be/ejkxvWkMbaQ?si=tOWAyIX5SeihT1J-

**Comment by jjnether** [comment]
@sahara101 theme is a bit long, how about this instead?

https://www.youtube.com/watch?v=ejkxvWkMbaQ

**Comment by sahara101** [comment]
Edited
