### ISSUE TITLE
[MOVIE]: The Holdovers (2023)

### ISSUE THREAD

**Issue by sahara101** [LizardByte/ThemerrDB#2463]
### Database URL

https://www.themoviedb.org/movie/840430

### YouTube Theme Song Video URL

https://youtu.be/Imut95oXlZE?si=JrVk3etyr_O1IIW-

**Comment by sahara101** [comment]
https://www.youtube.com/watch?v=Imut95oXlZE&list=PLftFBln7oG6f7Ump_D_p-6T23Qa7klSlm&index=2

**Comment by jjnether** [comment]
@sahara101 Please edit your original comment with the new theme link, then we can run the workflow

**Comment by sahara101** [comment]
Edited

**Comment by jjnether** [comment]
@sahara101 you linked a video in a playlist. Please edit with a linked video that isn't in a playlist, as only the first video would be grabbed. (see [here](https://github.com/LizardByte/ThemerrDB/blob/master/docs/YouTube_Share.md) for more details)

**Comment by sahara101** [comment]
Edited
