### ISSUE TITLE
[MOVIE]: Insidious: The Red Door (2023)

### ISSUE THREAD

**Issue by sahara101** [LizardByte/ThemerrDB#2464]
### Database URL

https://www.themoviedb.org/movie/614479

### YouTube Theme Song Video URL

https://youtu.be/hHjfoXZGlLI?si=V6uJjXzqdvjrGFGF

**Comment by jjnether** [comment]
@sahara101 you linked a video in a playlist. Please edit with a linked video that isn't in a playlist, as only the first video would be grabbed. (see [here](https://github.com/LizardByte/ThemerrDB/blob/master/docs/YouTube_Share.md) for more details)

**Comment by sahara101** [comment]
Edited
