### ISSUE TITLE
[MOVIE]: Mavka: The Forest Song (2023)

### ISSUE THREAD

**Issue by sahara101** [LizardByte/ThemerrDB#2468]
### Database URL

https://www.themoviedb.org/movie/459003

### YouTube Theme Song Video URL

https://youtu.be/u6pkzREm1kY?si=AAjMNicZ_ziqSNqR

**Comment by jjnether** [comment]
@sahara101 you linked a video in a playlist. Please edit with a linked video that isn't in a playlist, as only the first video would be grabbed. (see [here](https://github.com/LizardByte/ThemerrDB/blob/master/docs/YouTube_Share.md) for more details)

**Comment by sahara101** [comment]
Edited

**Comment by ReenigneArcher** [comment]
While, I have not seen this movie... this theme appears to be a scene in the movie which we would like to avoid. https://github.com/LizardByte/ThemerrDB/blob/master/docs/Theme_Guidelines.md#miscellaneous

**Comment by jjnether** [comment]
How about this theme instead?

https://youtu.be/u6pkzREm1kY?si=AAjMNicZ_ziqSNqR
