### ISSUE TITLE
[MOVIE]: No Hard Feelings (2023)

### ISSUE THREAD

**Issue by sahara101** [LizardByte/ThemerrDB#2471]
### Database URL

https://www.themoviedb.org/movie/884605

### YouTube Theme Song Video URL

https://youtu.be/wXkSqo9sSjM?si=NI3k1YoD6QdxBzKn

**Comment by jjnether** [comment]
@sahara101 you linked a video in a playlist. Please edit with a link without the playlist, as only the first video would be grabbed. (see [here](https://github.com/LizardByte/ThemerrDB/blob/master/docs/YouTube_Share.md) for more details)

**Comment by sahara101** [comment]
Edited
