### ISSUE TITLE
[MOVIE]: Retribution (2023)

### ISSUE THREAD

**Issue by sahara101** [LizardByte/ThemerrDB#2476]
### Database URL

https://www.themoviedb.org/movie/762430

### YouTube Theme Song Video URL

https://youtu.be/YeJML3s-TcA?si=8qmVpGiHDO8JbFQU

**Comment by jjnether** [comment]
@sahara101 you linked a video in a playlist. Please edit with a link without the playlist, as only the first video would be grabbed. (see [here](https://github.com/LizardByte/ThemerrDB/blob/master/docs/YouTube_Share.md) for more details)

**Comment by sahara101** [comment]
Edited
