### ISSUE TITLE
[MOVIE]: Saw X (2023)

### ISSUE THREAD

**Issue by sahara101** [LizardByte/ThemerrDB#2478]
### Database URL

https://www.themoviedb.org/movie/951491

### YouTube Theme Song Video URL

https://youtu.be/ckX20W-esMM?si=bOsvX-4WQ-YGisNa

**Comment by jjnether** [comment]
@sahara101 The theme should be from the movie, not trailer. How about this theme instead?

https://youtu.be/ckX20W-esMM?si=bOsvX-4WQ-YGisNa

**Comment by sahara101** [comment]
@jjnether Yes that is fine

**Comment by jjnether** [comment]
Ok, please edit your original link with the new one

**Comment by sahara101** [comment]
done

**Comment by ReenigneArcher** [comment]
@sahara101 Please be cautious when editing issues to not change the headings or formatting of the issue body. This caused errors in our workflow that took a good amount of time to diagnose.
