### ISSUE TITLE
[MOVIE]: She and Her Cat (1999)

### ISSUE THREAD

**Issue by sahara101** [LizardByte/ThemerrDB#2479]
### Database URL

https://www.themoviedb.org/movie/18143

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=jvRG49syGKM

**Comment by jjnether** [comment]
@sahara101 looks like the video you linked is just someone playing piano, not from the actual movie. How about this instead?

https://www.youtube.com/watch?v=jvRG49syGKM

**Comment by sahara101** [comment]
It is fine, I have edited
