### ISSUE TITLE
[MOVIE]: The Lord of the Rings: The Fellowship of the Ring (2001)

### ISSUE THREAD

**Issue by JohnnyWeber1** [LizardByte/ThemerrDB#2490]
### Database URL

https://www.themoviedb.org/movie/120

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=rpnh9fCURds

**Comment by JohnnyWeber1** [comment]
https://www.youtube.com/watch?v=rpnh9fCURds

**Comment by JohnnyWeber1** [comment]
sorry, the right one is:  https://www.youtube.com/watch?v=rpnh9fCURds

**Comment by ReenigneArcher** [comment]
Already exists.
