### ISSUE TITLE
[MOVIE]: The Jackal (1997)

### ISSUE THREAD

**Issue by anonymouscat888** [LizardByte/ThemerrDB#2520]
### Database URL

https://www.themoviedb.org/movie/4824

### YouTube Theme Song Video URL

https://youtu.be/ZmYf5uSIDYg?si=TfUSV5Dds-d-0dlK

**Comment by jjnether** [comment]
@anonymouscat888 Theme is very bad quality. Please edit with this link instead, same song but better quality

https://youtu.be/ZmYf5uSIDYg?si=TfUSV5Dds-d-0dlK

**Comment by anonymouscat888** [comment]
> @anonymouscat888 Theme is very bad quality. Please edit with this link instead, same song but better quality
> 
> https://youtu.be/ZmYf5uSIDYg?si=TfUSV5Dds-d-0dlK

Thank you!
