### ISSUE TITLE
[MOVIE]: Daft Punk - Alive 2007 - Live Album Concert à Paris (2007)

### ISSUE THREAD

**Issue by InyoEndo** [LizardByte/ThemerrDB#2526]
### Database URL

https://www.themoviedb.org/movie/843809

### YouTube Theme Song Video URL

https://youtu.be/TycgkK2gFvA?si=K4zr0fvU0CM-ANBg

**Comment by jjnether** [comment]
Theme is quite long, how about this instead?

https://youtu.be/TycgkK2gFvA?si=K4zr0fvU0CM-ANBg

**Comment by InyoEndo** [comment]
Yeah that works
