### ISSUE TITLE
[MOVIE]: TAYLOR SWIFT | THE ERAS TOUR (2023)

### ISSUE THREAD

**Issue by InyoEndo** [LizardByte/ThemerrDB#2529]
### Database URL

https://www.themoviedb.org/movie/1160164

### YouTube Theme Song Video URL

https://youtu.be/CUy33EutG-k?si=kmV9SF8c_AJg93gz

**Comment by jjnether** [comment]
@InyoEndo Theme is very long, how about this instead?

https://youtu.be/CUy33EutG-k?si=kmV9SF8c_AJg93gz

**Comment by InyoEndo** [comment]
Yes that works
