### ISSUE TITLE
[MOVIE]: The Croods (2013)

### ISSUE THREAD

**Issue by LetsGoDude** [LizardByte/ThemerrDB#2534]
### Database URL

https://www.themoviedb.org/movie/49519-the-croods

### YouTube Theme Song Video URL

https://youtu.be/xwmSMvM2J5c?si=CpVumd0_1zcxEhG0

**Comment by LetsGoDude** [comment]
I have updated the link.
Same video as currently only without geoblocking (available in USA and Europe).
The current link does not work in the EU.

**Comment by jjnether** [comment]
It's preferred that the theme isn't from the opening scene. How about this instead?

https://youtu.be/xwmSMvM2J5c?si=CpVumd0_1zcxEhG0

**Comment by LetsGoDude** [comment]
Yeah this is great too. i edited the link
