### ISSUE TITLE
[MOVIE]: Airplane II: The Sequel (1982)

### ISSUE THREAD

**Issue by anonymouscat888** [LizardByte/ThemerrDB#2536]
### Database URL

https://www.themoviedb.org/movie/2665

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=4TmIte7z7mo

**Comment by jjnether** [comment]
The video you linked is an actual scene from the movie. Please edit with this instead, just the song

https://www.youtube.com/watch?v=4TmIte7z7mo

**Comment by anonymouscat888** [comment]
Thank you so much for your suggesetions!  They are very much apprecaited.  I really love this plugin!
