### ISSUE TITLE
[MOVIE]: Detective Conan: Jolly Roger in the Deep Azure (2007)

### ISSUE THREAD

**Issue by LetsGoDude** [LizardByte/ThemerrDB#2549]
### Database URL

https://www.themoviedb.org/movie/39206

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=3xYj4Pa4P10

**Comment by jjnether** [comment]
Instead of same theme for this series, what about this one unique to the movie?

https://www.youtube.com/watch?v=3xYj4Pa4P10

**Comment by LetsGoDude** [comment]
updated
