### ISSUE TITLE
[MOVIE]: Detective Conan: The Private Eyes' Requiem (2006)

### ISSUE THREAD

**Issue by LetsGoDude** [LizardByte/ThemerrDB#2550]
### Database URL

https://www.themoviedb.org/movie/39205

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=XlpNr1amdyY

**Comment by jjnether** [comment]
How about this instead, unique to this movie?

https://www.youtube.com/watch?v=XlpNr1amdyY

**Comment by LetsGoDude** [comment]
updated
