### ISSUE TITLE
[MOVIE]: Detective Conan: Strategy Above the Depths (2005)

### ISSUE THREAD

**Issue by LetsGoDude** [LizardByte/ThemerrDB#2551]
### Database URL

https://www.themoviedb.org/movie/39204

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=n7boa_Mbe1g

**Comment by jjnether** [comment]
How about this theme, unique to this movie?

https://www.youtube.com/watch?v=n7boa_Mbe1g

**Comment by LetsGoDude** [comment]
updated
