### ISSUE TITLE
[MOVIE]: Detective Conan: Crossroad in the Ancient Capital (2003)

### ISSUE THREAD

**Issue by LetsGoDude** [LizardByte/ThemerrDB#2553]
### Database URL

https://www.themoviedb.org/movie/39202

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=5a4uOKrhZaQ

**Comment by jjnether** [comment]
How about this theme, unique to this movie?

https://www.youtube.com/watch?v=5a4uOKrhZaQ

**Comment by LetsGoDude** [comment]
updated
