### ISSUE TITLE
[MOVIE]: Detective Conan: The Phantom of Baker Street (2002)

### ISSUE THREAD

**Issue by LetsGoDude** [LizardByte/ThemerrDB#2554]
### Database URL

https://www.themoviedb.org/movie/26662

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=mI1_thjNJ7A

**Comment by jjnether** [comment]
How about this theme, unique to this movie?

https://www.youtube.com/watch?v=mI1_thjNJ7A

**Comment by LetsGoDude** [comment]
updated
