### ISSUE TITLE
[MOVIE]: Case Closed: Countdown to Heaven (2001)

### ISSUE THREAD

**Issue by LetsGoDude** [LizardByte/ThemerrDB#2555]
### Database URL

https://www.themoviedb.org/movie/32022

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=YBJ9zBikQCM

**Comment by jjnether** [comment]
@LetsGoDude Ok, it seems you put the same theme for all these Case Closed movies, but it's pretty easy to find the theme unique to each movie. Please edit with those themes for all these, thanks

**Comment by LetsGoDude** [comment]
@jjnether updated
I deliberately chose the same one because the themes differ only minimally. With the exception of two or three films, the themes are all very similar.
I have now updated them all.

**Comment by jjnether** [comment]
Thanks for editing. They are all very similar, we just try to have unique themes if possible. Not a big deal though
