### ISSUE TITLE
[MOVIE]: Detective Conan: Captured in Her Eyes (2000)

### ISSUE THREAD

**Issue by LetsGoDude** [LizardByte/ThemerrDB#2556]
### Database URL

https://www.themoviedb.org/movie/20677

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=7EYcOntuD7s

**Comment by jjnether** [comment]
Please edit with a theme unique to this movie

**Comment by LetsGoDude** [comment]
this is the correct Theme for this movie (Captured In Her Eyes Version)

**Comment by jjnether** [comment]
Ahh sorry about that
