### ISSUE TITLE
[MOVIE]: Detective Conan: The Last Wizard of the Century (1999)

### ISSUE THREAD

**Issue by LetsGoDude** [LizardByte/ThemerrDB#2557]
### Database URL

https://www.themoviedb.org/movie/28808

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=tPdJqW_rlSk

**Comment by jjnether** [comment]
Please edit with a theme unique to this movie

**Comment by LetsGoDude** [comment]
updated
