### ISSUE TITLE
[MOVIE]: Detective Conan: The Time Bombed Skyscraper (1997)

### ISSUE THREAD

**Issue by LetsGoDude** [LizardByte/ThemerrDB#2559]
### Database URL

https://www.themoviedb.org/movie/21422

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=7TZx_UhpmEE

**Comment by jjnether** [comment]
Please edit with a theme unique to this movie

**Comment by LetsGoDude** [comment]
updated
