### ISSUE TITLE
[MOVIE]: Detective Conan: Black Iron Submarine (2023)

### ISSUE THREAD

**Issue by LetsGoDude** [LizardByte/ThemerrDB#2560]
### Database URL

https://www.themoviedb.org/movie/1047041

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=3PsiCUGd9cU

**Comment by jjnether** [comment]
Please edit with a theme unique to this movie

**Comment by LetsGoDude** [comment]
updated
