### ISSUE TITLE
[MOVIE]: Detective Conan: The Raven Chaser (2009)

### ISSUE THREAD

**Issue by LetsGoDude** [LizardByte/ThemerrDB#2562]
### Database URL

https://www.themoviedb.org/movie/28764

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=BoIyxDO5lFQ

**Comment by jjnether** [comment]
Please edit with a theme unique to this movie

**Comment by LetsGoDude** [comment]
updated
