### ISSUE TITLE
[MOVIE]: Detective Conan: The Lost Ship in the Sky (2010)

### ISSUE THREAD

**Issue by LetsGoDude** [LizardByte/ThemerrDB#2563]
### Database URL

https://www.themoviedb.org/movie/97375

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=rWEupX0vc10

**Comment by jjnether** [comment]
Please edit with a theme unique to this movie

**Comment by LetsGoDude** [comment]
updated
