### ISSUE TITLE
[MOVIE]: Detective Conan: Quarter of Silence (2011)

### ISSUE THREAD

**Issue by LetsGoDude** [LizardByte/ThemerrDB#2564]
### Database URL

https://www.themoviedb.org/movie/77617-15

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=BLyqySJiKLk

**Comment by jjnether** [comment]
Please edit with a theme unique to this movie

**Comment by LetsGoDude** [comment]
updated
