### ISSUE TITLE
[MOVIE]: Detective Conan: Private Eye in the Distant Sea (2013)

### ISSUE THREAD

**Issue by LetsGoDude** [LizardByte/ThemerrDB#2566]
### Database URL

https://www.themoviedb.org/movie/228805

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=JFpQ3-8gTIk

**Comment by jjnether** [comment]
Please edit with a theme unique to this movie

**Comment by LetsGoDude** [comment]
updated
