### ISSUE TITLE
[MOVIE]: Lupin the Third vs. Detective Conan: The Movie (2013)

### ISSUE THREAD

**Issue by LetsGoDude** [LizardByte/ThemerrDB#2567]
### Database URL

https://www.themoviedb.org/movie/239529-vs-the-movie

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=t3dMRkDGBiw

**Comment by jjnether** [comment]
Please edit with a theme unique to this movie

**Comment by LetsGoDude** [comment]
updated
