### ISSUE TITLE
[MOVIE]: Detective Conan: Dimensional Sniper (2014)

### ISSUE THREAD

**Issue by LetsGoDude** [LizardByte/ThemerrDB#2568]
### Database URL

https://www.themoviedb.org/movie/257512

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=bFoC9JSW_f8

**Comment by jjnether** [comment]
Please edit with a theme unique to this movie

**Comment by LetsGoDude** [comment]
updated

**Comment by ReenigneArcher** [comment]
@LetsGoDude you no longer need to comment that you updated the issue. The bot let's us know. Thanks!
