### ISSUE TITLE
[MOVIE]: Detective Conan: Sunflowers of Inferno (2015)

### ISSUE THREAD

**Issue by LetsGoDude** [LizardByte/ThemerrDB#2569]
### Database URL

https://www.themoviedb.org/movie/316873

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=mfyXy_-DTpI

**Comment by jjnether** [comment]
Please edit with a theme unique to this movie

**Comment by LetsGoDude** [comment]
updated
