### ISSUE TITLE
[MOVIE]: Detective Conan: The Darkest Nightmare (2016)

### ISSUE THREAD

**Issue by LetsGoDude** [LizardByte/ThemerrDB#2570]
### Database URL

https://www.themoviedb.org/movie/374856

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=81hdpUjL5MA

**Comment by jjnether** [comment]
Please edit with a theme unique to this movie

**Comment by LetsGoDude** [comment]
updated
