### ISSUE TITLE
[MOVIE]: Case Closed: The Fist of Blue Sapphire (2019)

### ISSUE THREAD

**Issue by LetsGoDude** [LizardByte/ThemerrDB#2572]
### Database URL

https://www.themoviedb.org/movie/566555

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=rPv6Dx2aUCo

**Comment by jjnether** [comment]
Please edit with a theme unique to this movie

**Comment by LetsGoDude** [comment]
updated
