### ISSUE TITLE
[MOVIE]: Detective Conan: The Scarlet Bullet (2021)

### ISSUE THREAD

**Issue by LetsGoDude** [LizardByte/ThemerrDB#2573]
### Database URL

https://www.themoviedb.org/movie/662638

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=atE3kkG1Wrc

**Comment by jjnether** [comment]
Please edit with a theme unique to this movie

**Comment by LetsGoDude** [comment]
updated
