### ISSUE TITLE
[MOVIE]: Detective Conan: The Bride of Halloween (2022)

### ISSUE THREAD

**Issue by LetsGoDude** [LizardByte/ThemerrDB#2574]
### Database URL

https://www.themoviedb.org/movie/903939

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=ZB-KgVYpP-A

**Comment by jjnether** [comment]
Please edit with a theme unique to this movie

**Comment by LetsGoDude** [comment]
updated
