### ISSUE TITLE
[MOVIE]: Case Closed: The Crimson Love Letter (2017)

### ISSUE THREAD

**Issue by LetsGoDude** [LizardByte/ThemerrDB#2575]
### Database URL

https://www.themoviedb.org/movie/438058

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=Slh8PNCY6qU

**Comment by jjnether** [comment]
Please edit with a theme unique to this movie

**Comment by LetsGoDude** [comment]
updated
