### ISSUE TITLE
[MOVIE]: Dungeons & Dragons: Honor Among Thieves (2023)

### ISSUE THREAD

**Issue by raphpa** [LizardByte/ThemerrDB#2616]
### Database URL

https://www.themoviedb.org/movie/493529-dungeons-dragons-honor-among-thieves

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=0RfzfZXgWkk

**Comment by jjnether** [comment]
Video is unavailable, and there is already an existing theme for this. What's the reason for the change?

**Comment by raphpa** [comment]
Oh it seems that the already available version is region locked in the EU where as the proposed version is region locked in the US. 
This one would be available everywhere I tested:

https://www.youtube.com/watch?v=0RfzfZXgWkk

**Comment by ReenigneArcher** [comment]
@LizardByte-bot edit https://www.youtube.com/watch?v=0RfzfZXgWkk

**Comment by ReenigneArcher** [comment]
@LizardByte-bot approve
