### ISSUE TITLE
[MOVIE]: Alien³ (1992)

### ISSUE THREAD

**Issue by welshleddy** [LizardByte/ThemerrDB#2618]
### Database URL

https://www.themoviedb.org/movie/8077

### YouTube Theme Song Video URL

https://youtu.be/XfMRCiRqEuU?si=ady-0TvSQshgkTuP

**Comment by jjnether** [comment]
@welshleddy theme you linked is very soft for the first 30 seconds. How about this instead?

https://youtu.be/XfMRCiRqEuU?si=ady-0TvSQshgkTuP

**Comment by welshleddy** [comment]
That sounds better.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ReenigneArcher** [comment]
@LizardByte-bot edit https://youtu.be/XfMRCiRqEuU?si=ady-0TvSQshgkTuP

**Comment by ReenigneArcher** [comment]
@LizardByte-bot approve
