### ISSUE TITLE
[MOVIE]: Area 51: The CIA's Secret (2014)

### ISSUE THREAD

**Issue by sahara101** [LizardByte/ThemerrDB#2623]
### Database URL

https://www.themoviedb.org/movie/378952

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=EnVL9GmDh60

**Comment by ReenigneArcher** [comment]
Does the requested theme actually represent this documentary?

Documentaries are tricky. Is there any music played during the documentary? If so you can use Shazam to detect it.

**Comment by sahara101** [comment]
Hmm I haven't watched it yet, so maybe I reopen once I do?
