### ISSUE TITLE
[MOVIE]: The Aristocats (1970)

### ISSUE THREAD

**Issue by anonymouscat888** [LizardByte/ThemerrDB#2629]
### Database URL

https://www.themoviedb.org/movie/10112

### YouTube Theme Song Video URL

https://youtu.be/hYe6ffMrOWE?si=rx9OMgvmNbQz5hqU

**Comment by jjnether** [comment]
@LizardByte-bot edit https://youtu.be/hYe6ffMrOWE?si=rx9OMgvmNbQz5hqU

**Comment by jjnether** [comment]
@LizardByte-bot approve
