### ISSUE TITLE
[MOVIE]: 1½ Knights - In Search of the Ravishing Princess Herzelinde (2008)

### ISSUE THREAD

**Issue by LetsGoDude** [LizardByte/ThemerrDB#2632]
### Database URL

https://www.themoviedb.org/movie/9510-1-ritter-auf-der-suche-nach-der-hinrei-enden-herzelinde

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=EA4bDj9L6Xc

**Comment by jjnether** [comment]
@LizardByte-bot approve
