### ISSUE TITLE
[MOVIE]: The Hangover (2009)

### ISSUE THREAD

**Issue by LetsGoDude** [LizardByte/ThemerrDB#2669]
### Database URL

https://www.themoviedb.org/movie/18785-the-hangover

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=60FS8rKjXYk

**Comment by ReenigneArcher** [comment]
We're trying to avoid opening scene music... how about this one?

https://www.youtube.com/watch?v=60FS8rKjXYk

**Comment by ReenigneArcher** [comment]
@LizardByte-bot edit https://www.youtube.com/watch?v=60FS8rKjXYk

**Comment by ReenigneArcher** [comment]
@LizardByte-bot approve
