### ISSUE TITLE
[MOVIE]: 97% Owned (2012)

### ISSUE THREAD

**Issue by sahara101** [LizardByte/ThemerrDB#2755]
### Database URL

https://www.themoviedb.org/movie/147580-97-owned

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=KAc80hrIMa4

**Comment by ReenigneArcher** [comment]
I think you pasted the same theme from #2754

**Comment by sahara101** [comment]
Ups, you can reject for now, I do not find a theme
