### ISSUE TITLE
[MOVIE]: Titanic (1997)

### ISSUE THREAD

**Issue by eterchronos** [LizardByte/ThemerrDB#2756]
### Database URL

https://www.themoviedb.org/movie/597

### YouTube Theme Song Video URL

https://youtu.be/mcjtQtIReyk

**Comment by ReenigneArcher** [comment]
What's the reason for the change?

**Comment by eterchronos** [comment]
My idea is not to change, when the scan is done, for me this film appears as if it had no music, so I collaborated to put a theme song for it
________________________________
De: ReenigneArcher ***@***.***>
Enviado: sábado, 13 de janeiro de 2024 22:11
Para: LizardByte/ThemerrDB ***@***.***>
Cc: Lucas Oliveira ***@***.***>; Author ***@***.***>
Assunto: Re: [LizardByte/ThemerrDB] [MOVIE]: Titanic (1997) (Issue #2756)


What's the reason for the change?

**Comment by ReenigneArcher** [comment]
It could be a regional issue. Currently, all of our themes are available in the USA.

Are you using Plex, Jellyfin, or Kodi?

**Comment by eterchronos** [comment]
im using jellyfin language: portuguese-brazil but Country: united states. I don't want to cause trouble, I was just trying to collaborate on the missing theme songs.
________________________________
De: ReenigneArcher ***@***.***>
Enviado: sábado, 13 de janeiro de 2024 23:17
Para: LizardByte/ThemerrDB ***@***.***>
Cc: Lucas Oliveira ***@***.***>; Author ***@***.***>
Assunto: Re: [LizardByte/ThemerrDB] [MOVIE]: Titanic (1997) (Issue #2756)


It could be a regional issue. Currently, all of our themes are available in the USA.

Are you using Plex, Jellyfin, or Kodi?

**Comment by ReenigneArcher** [comment]
> I don't want to cause trouble

You're not causing trouble! I was just asking to determine why the theme is unavailable for you.

If you have access to a VPN that can connect to the US, I think it would help.

The completion table in the Jellyfin config html page is still in it's early stages. I'd like to do a little more work on it so the user can see if the item is in our database. That's what we do for our Plex dashboard. If it's in our database but the user doesn't have a theme for it, then we display an "error" icon with a "failed to download" status.

**Comment by eterchronos** [comment]
Is there any way to change the volume of the theme song? He plays extremely loud.
________________________________
De: ReenigneArcher ***@***.***>
Enviado: domingo, 14 de janeiro de 2024 01:40
Para: LizardByte/ThemerrDB ***@***.***>
Cc: Lucas Oliveira ***@***.***>; Author ***@***.***>
Assunto: Re: [LizardByte/ThemerrDB] [MOVIE]: Titanic (1997) (Issue #2756)


I don't want to cause trouble

You're not causing trouble! I was just asking to determine why the theme is unavailable for you.

If you have access to a VPN that can connect to the US, I think it would help.

The completion table in the Jellyfin config html page is still in it's early stages. I'd like to do a little more work on it so the user can see if the item is in our database. That's what we do for our Plex dashboard. If it's in our database but the user doesn't have a theme for it, then we display an "error" icon with a "failed to download" status.
