### ISSUE TITLE
[MOVIE]: The Guardians of the Galaxy Holiday Special (2022)

### ISSUE THREAD

**Issue by eterchronos** [LizardByte/ThemerrDB#2757]
### Database URL

https://www.themoviedb.org/movie/774752

### YouTube Theme Song Video URL

https://youtu.be/axjJCkTZx74?list=PLxaFrzRPFngUsNRzFrGQJVdVcEVcUdD67

**Comment by ReenigneArcher** [comment]
Please don't submit playlists. We only support one video.

**Comment by jjnether** [comment]
@LizardByte-bot approve
