### ISSUE TITLE
[MOVIE]: Joker (2019)

### ISSUE THREAD

**Issue by eterchronos** [LizardByte/ThemerrDB#2758]
### Database URL

https://www.themoviedb.org/movie/475557

### YouTube Theme Song Video URL

https://youtu.be/gSwbYHJYskM

**Comment by ReenigneArcher** [comment]
What's the reason for the change?

**Comment by eterchronos** [comment]
My idea is not to change, when the scan is done, for me this film appears as if it had no music, so I collaborated to put a theme song for it
________________________________
De: ReenigneArcher ***@***.***>
Enviado: sábado, 13 de janeiro de 2024 22:11
Para: LizardByte/ThemerrDB ***@***.***>
Cc: Lucas Oliveira ***@***.***>; Author ***@***.***>
Assunto: Re: [LizardByte/ThemerrDB] [MOVIE]: Joker (2019) (Issue #2758)


What's the reason for the change?
