### ISSUE TITLE
[MOVIE]: Inside Man (2006)

### ISSUE THREAD

**Issue by alltilla** [LizardByte/ThemerrDB#2779]
### Database URL

https://www.themoviedb.org/movie/388

### YouTube Theme Song Video URL

https://youtu.be/rCZBLIkUh7Q?si=hjuxgWqiYlBc18aX

**Comment by jjnether** [comment]
@alltilla theme is a bit long, how about this instead?

https://youtu.be/rCZBLIkUh7Q?si=hjuxgWqiYlBc18aX

**Comment by alltilla** [comment]
Perfect, thanks!

**Comment by jjnether** [comment]
@LizardByte-bot edit https://youtu.be/rCZBLIkUh7Q?si=hjuxgWqiYlBc18aX

**Comment by jjnether** [comment]
@LizardByte-bot approve
