### ISSUE TITLE
[MOVIE]: Weathering with You (2019)

### ISSUE THREAD

**Issue by tylerbickel** [LizardByte/ThemerrDB#280]
### TheMovieDB URL

https://www.themoviedb.org/movie/568160

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=a2GujJZfXpg

**Comment by ReenigneArcher** [comment]
Appears to be the same song you selected for #226 ... Are these in the same collection? I didn't see any collection details for this item.

**Comment by tylerbickel** [comment]
Same studio I think. I’ll go and find something else.
________________________________

**Comment by ReenigneArcher** [comment]
> Same studio I think. I’ll go and find something else.

It's okay if they're the same song. I don't have any rule about re-using themes. I was just curious.
