### ISSUE TITLE
[MOVIE]: We Need to Talk About Kevin (2011)

### ISSUE THREAD

**Issue by tylerbickel** [LizardByte/ThemerrDB#282]
### TheMovieDB URL

https://www.themoviedb.org/movie/71859

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=C4bwjJ0XlV4

**Comment by ReenigneArcher** [comment]
This one is pretty long, ~30 minutes. Is anything short available?

This is kind of what I've been using.

| Preference | Length |
| ---------- | ------ |
| Ideal      | 1-2.5 mins |
| Good       | 2.5-5 mins |
| Acceptable | 5-8 mins |
| Less Acceptable | 8-11 mins |

**Comment by tylerbickel** [comment]
Oops totally missed the length on this one. Been trying to pick the shortest video available, and ones that have an immediate start (no slow buildup or channel intros).

Too bad there’s no way to specify a start/end time, or have the downloader truncate after 5 mins. But I know you don’t want to complicate it. I’ll look for something else for this one.
________________________________

**Comment by tylerbickel** [comment]
Updated YT link.
