### ISSUE TITLE
[MOVIE]: Wonka (2023)

### ISSUE THREAD

**Issue by alltilla** [LizardByte/ThemerrDB#2828]
### Database URL

https://www.themoviedb.org/movie/787699

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=owexvIpqGcE

**Comment by jjnether** [comment]
@alltilla It's preferred that the theme isn't from the opening scene. Please edit with a different theme

**Comment by jjnether** [comment]
Someone else responded regarding this theme
