### ISSUE TITLE
[MOVIE]: Kill Bill: Vol. 2 (2004)

### ISSUE THREAD

**Issue by Lagrosso** [LizardByte/ThemerrDB#2831]
### Database URL

https://www.themoviedb.org/movie/393

### YouTube Theme Song Video URL

https://youtu.be/vPh7y_KkyjI?si=Nw7XZt303OgrD6M7

**Comment by jjnether** [comment]
The theme you submitted is from the first Kill Bill, and a theme already exists for Kill Bill 2
