### ISSUE TITLE
[TV SHOW]: Captain Tsubasa (2018)

### ISSUE THREAD

**Issue by Lagrosso** [LizardByte/ThemerrDB#2833]
### Database URL

https://www.themoviedb.org/tv/77240

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=2hq3jDi2NeU

**Comment by jjnether** [comment]
@Lagrosso your theme submission is for the older version of this show. I'll edit with a proper theme

**Comment by jjnether** [comment]
@LizardByte-bot edit https://www.youtube.com/watch?v=2hq3jDi2NeU

**Comment by jjnether** [comment]
@LizardByte-bot approve
