### ISSUE TITLE
[MOVIE]: Jurassic Park (1993)

### ISSUE THREAD

**Issue by Jolaru21** [LizardByte/ThemerrDB#2867]
### Database URL

https://www.themoviedb.org/movie/329

### YouTube Theme Song Video URL

https://youtu.be/rbRE-hmkVXE

**Comment by jjnether** [comment]
@Jolaru21 Any particular reason for the change? Although the theme you selected is the main theme of the movie, it's barely audible for the first 30 seconds

**Comment by jjnether** [comment]
I'll edit to a version where the main theme is more prominent

**Comment by jjnether** [comment]
@LizardByte-bot edit https://youtu.be/rbRE-hmkVXE

**Comment by jjnether** [comment]
@LizardByte-bot approve
