### ISSUE TITLE
[TV SHOW]: The Last of Us (2023)

### ISSUE THREAD

**Issue by tubben** [LizardByte/ThemerrDB#2871]
### Database URL

https://www.themoviedb.org/tv/100088

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=8SWhBsbxmpk

**Comment by jjnether** [comment]
I'll change to the actual TV show intro (basically same theme, just shorter)

**Comment by jjnether** [comment]
@LizardByte-bot edit https://www.youtube.com/watch?v=8SWhBsbxmpk

**Comment by jjnether** [comment]
@LizardByte-bot approve
