### ISSUE TITLE
[MOVIE]: A Nightmare on Elm Street (2010)

### ISSUE THREAD

**Issue by JanRi3D** [LizardByte/ThemerrDB#2875]
### Database URL

https://www.themoviedb.org/movie/23437

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=HZSnwJOQp0A

**Comment by jjnether** [comment]
@JanRi3D A theme already exists, any reason for the change?

**Comment by jjnether** [comment]
When replacing a theme, please comment your reason for the theme replacement.
