### ISSUE TITLE
[MOVIE]: Dawn of the Dead (1978)

### ISSUE THREAD

**Issue by harunator0** [LizardByte/ThemerrDB#2880]
### Database URL

https://www.themoviedb.org/movie/923-dawn-of-the-dead

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=zYKy8Z1Ze3E&list=PLE4FQLcmWEPY4Q5fwQ6STYsklUtjr_fHr&index=2

**Comment by jjnether** [comment]
@LizardByte-bot approve
