### ISSUE TITLE
[MOVIE]: Truck Turner (1974)

### ISSUE THREAD

**Issue by harunator0** [LizardByte/ThemerrDB#2881]
### Database URL

https://www.themoviedb.org/movie/22121-truck-turner

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=XOu-LjGDSOY&list=OLAK5uy_mr670fDXHVH7_6XPcabua6DmWUDIeAYn4

**Comment by jjnether** [comment]
@LizardByte-bot approve
