### ISSUE TITLE
[MOVIE]: The Hateful Eight (2015)

### ISSUE THREAD

**Issue by harunator0** [LizardByte/ThemerrDB#2882]
### Database URL

https://www.themoviedb.org/movie/273248-the-hateful-eight?language=de

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=G_PzOl4r_Dc

**Comment by jjnether** [comment]
@harunator0 A theme already exists for this. Any reason for the change?

**Comment by harunator0** [comment]
Yes, this theme is played often throughout the movie, so it can be considered it's main theme, while the current theme is only played once and doesn't really represent the movie.

**Comment by ReenigneArcher** [comment]
@harunator0 thank you for the clarification. In the future please let us know why you are replacing a theme at the start. https://stackoverflow.com/a/46380601/11214013

Thanks!

**Comment by jjnether** [comment]
@LizardByte-bot approve
