### ISSUE TITLE
[MOVIE]: Eyes Wide Shut (1999)

### ISSUE THREAD

**Issue by harunator0** [LizardByte/ThemerrDB#2901]
### Database URL

https://www.themoviedb.org/movie/345-eyes-wide-shut?language=de-DE

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=5wjnzGwmbqs&list=PLpg2_ILe5eBLAgmNsNOfV5ce48Uwdl_Nz&index=2

**Comment by jjnether** [comment]
@LizardByte-bot approve
