### ISSUE TITLE
[MOVIE]: Mission: Impossible (1996)

### ISSUE THREAD

**Issue by harunator0** [LizardByte/ThemerrDB#2902]
### Database URL

https://www.themoviedb.org/movie/954-mission-impossible?language=de-DE

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=rgPjAeQDrGY&list=PLqnnuEVGcRQwoTVAlAgP549D2H9RL93kq

**Comment by jjnether** [comment]
@harunator0 Theme already exists. Please check existing theme before submitting
