### ISSUE TITLE
[MOVIE]: Wonka (2023)

### ISSUE THREAD

**Issue by alexander-stepanenko** [LizardByte/ThemerrDB#2903]
### Database URL

https://www.themoviedb.org/movie/787699

### YouTube Theme Song Video URL

https://youtu.be/b4wHnf9VTRk?si=FZ8yqd6d9t0yDdSL

**Comment by jjnether** [comment]
@alexander-stepanenko It's preferred that the theme isn't from the opening scene. How about this instead?
https://youtu.be/b4wHnf9VTRk?si=FZ8yqd6d9t0yDdSL

**Comment by alexander-stepanenko** [comment]
@LizardByte-bot edit https://youtu.be/b4wHnf9VTRk?si=FZ8yqd6d9t0yDdSL

**Comment by alexander-stepanenko** [comment]
@LizardByte-bot approve

**Comment by jjnether** [comment]
@alexander-stepanenko  Haha you can just let me know your response when I ask a question, and I'll do the commands. The bot commands only work for approvers

**Comment by jjnether** [comment]
@LizardByte-bot edit https://youtu.be/b4wHnf9VTRk?si=FZ8yqd6d9t0yDdSL

**Comment by jjnether** [comment]
> @alexander-stepanenko Haha you can just let me know your response when I ask a question, and I'll do the commands. The bot commands only work for approvers

You can also edit your own comment yourself if you want to change the link, but I'll handle this one

**Comment by jjnether** [comment]
@LizardByte-bot approve
