### ISSUE TITLE
[MOVIE]: Palmer (2021)

### ISSUE THREAD

**Issue by alexander-stepanenko** [LizardByte/ThemerrDB#2905]
### Database URL

https://www.themoviedb.org/movie/458220

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=57EUOC4P5H4#:~:text=Nathaniel%20Rateliff%20%2D%20Redemption%20(From%20the,Film%20%E2%80%9CPalmer%E2%80%9D)%20%2D%20YouTube

**Comment by jjnether** [comment]
@LizardByte-bot approve
