### ISSUE TITLE
[MOVIE]: Blow (2001)

### ISSUE THREAD

**Issue by Lissi95** [LizardByte/ThemerrDB#2910]
### Database URL

https://www.themoviedb.org/movie/4133

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=ivgqccySCls

**Comment by jjnether** [comment]
@LizardByte-bot edit https://www.youtube.com/watch?v=ivgqccySCls

**Comment by jjnether** [comment]
Song was too long, edited with a shortened version

**Comment by jjnether** [comment]
@LizardByte-bot approve
