### ISSUE TITLE
[MOVIE]: Apocalypto (2006)

### ISSUE THREAD

**Issue by alexander-stepanenko** [LizardByte/ThemerrDB#2916]
### Database URL

https://www.themoviedb.org/movie/1579

### YouTube Theme Song Video URL

https://youtu.be/Qit1gSSrKg4?si=PyZz0cjB19VlYomz

**Comment by jjnether** [comment]
@LizardByte-bot edit https://youtu.be/Qit1gSSrKg4?si=PyZz0cjB19VlYomz

**Comment by jjnether** [comment]
@LizardByte-bot approve
