### ISSUE TITLE
[MOVIE]: Jupiter Ascending (2015)

### ISSUE THREAD

**Issue by alexander-stepanenko** [LizardByte/ThemerrDB#2918]
### Database URL

https://www.themoviedb.org/movie/76757

### YouTube Theme Song Video URL

https://youtu.be/sdfNJHYHzG0?si=nawLJbiFRqw3hOUp

**Comment by jjnether** [comment]
@alexander-stepanenko Theme is a bit long, how about this instead?
https://youtu.be/sdfNJHYHzG0?si=nawLJbiFRqw3hOUp

**Comment by jjnether** [comment]
@LizardByte-bot edit https://youtu.be/sdfNJHYHzG0?si=nawLJbiFRqw3hOUp

**Comment by jjnether** [comment]
@LizardByte-bot approve
