### ISSUE TITLE
[TV SHOW]: Gen V (2023)

### ISSUE THREAD

**Issue by alexander-stepanenko** [LizardByte/ThemerrDB#2925]
### Database URL

https://www.themoviedb.org/tv/205715

### YouTube Theme Song Video URL

https://youtu.be/aFmpZJ6XuIY?si=_u2WiHvcNPRrTv8H

**Comment by alexander-stepanenko** [comment]
@LizardByte-bot approve

**Comment by jjnether** [comment]
> @LizardByte-bot approve

@alexander-stepanenko Only moderators can approve themes. The theme you submitted is from a trailer, it's preferred that the theme is from the actual movie/show. How about this instead?

https://youtu.be/aFmpZJ6XuIY?si=_u2WiHvcNPRrTv8H

**Comment by alexander-stepanenko** [comment]
That should work

**Comment by jjnether** [comment]
@LizardByte-bot edit https://youtu.be/aFmpZJ6XuIY?si=_u2WiHvcNPRrTv8H

**Comment by jjnether** [comment]
@LizardByte-bot approve
