### ISSUE TITLE
[MOVIE]: Fear and Loathing in Las Vegas (1998)

### ISSUE THREAD

**Issue by Lissi95** [LizardByte/ThemerrDB#2930]
### Database URL

https://www.themoviedb.org/movie/1878

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=Z2LSSgQMc2E

**Comment by jjnether** [comment]
Editing with version that starts immediately and better quality

**Comment by jjnether** [comment]
@LizardByte-bot edit https://www.youtube.com/watch?v=Z2LSSgQMc2E

**Comment by jjnether** [comment]
@LizardByte-bot approve
