### ISSUE TITLE
[MOVIE]: Annabelle Comes Home (2019)

### ISSUE THREAD

**Issue by X8Haz** [LizardByte/ThemerrDB#2938]
### Database URL

https://www.themoviedb.org/movie/521029

### YouTube Theme Song Video URL

https://youtu.be/DCByXZhGKIs?si=7dZWZIJy0Yt1ddc9

**Comment by jjnether** [comment]
@X8Haz music doesn't kick in until about 20 sec in. How about this instead?

https://youtu.be/DCByXZhGKIs?si=7dZWZIJy0Yt1ddc9

**Comment by X8Haz** [comment]
@jjnether yes of course

**Comment by jjnether** [comment]
@LizardByte-bot edit https://youtu.be/DCByXZhGKIs?si=7dZWZIJy0Yt1ddc9

**Comment by jjnether** [comment]
@LizardByte-bot approve
