### ISSUE TITLE
[TV SHOW]: Workaholics (2011)

### ISSUE THREAD

**Issue by ericthomasca** [LizardByte/ThemerrDB#2950]
### Database URL

https://www.themoviedb.org/tv/36994

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=k3M-XmKAHMA&pp=ygUWV29ya2Fob2xpY3MgdGhlbWUgc29uZw%3D%3D

**Comment by jjnether** [comment]
@LizardByte-bot approve
