### ISSUE TITLE
[TV SHOW]: ted (2024)

### ISSUE THREAD

**Issue by ericthomasca** [LizardByte/ThemerrDB#2951]
### Database URL

https://www.themoviedb.org/tv/201834

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=NzgI_a8U_dU

**Comment by jjnether** [comment]
Will edit with a longer version

**Comment by jjnether** [comment]
@LizardByte-bot edit https://www.youtube.com/watch?v=NzgI_a8U_dU

**Comment by jjnether** [comment]
@LizardByte-bot approve
