### ISSUE TITLE
[MOVIE]: Explorers (1985)

### ISSUE THREAD

**Issue by MadaxDeLuXe** [LizardByte/ThemerrDB#2986]
### Database URL

https://www.themoviedb.org/movie/9872

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=c59g3KucIzo

**Comment by jjnether** [comment]
@MadaxDeLuXe The video you posted is far too long. How about this instead?

https://www.youtube.com/watch?v=c59g3KucIzo

**Comment by jjnether** [comment]
> Ah, ok. I actually thought it'd grab (lets say) the first 30 sec of that soundfile , fade it out and start over :P

Np, unfortunately not how this works

**Comment by jjnether** [comment]
@LizardByte-bot edit https://www.youtube.com/watch?v=c59g3KucIzo

**Comment by jjnether** [comment]
@LizardByte-bot approve
