### ISSUE TITLE
[MOVIE]: Jeepers Creepers (2001)

### ISSUE THREAD

**Issue by MadaxDeLuXe** [LizardByte/ThemerrDB#2989]
### Database URL

https://www.themoviedb.org/movie/8922

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=81GpS8_I_Jw

**Comment by jjnether** [comment]
I'll edit with same song, but slightly better fidelity

**Comment by jjnether** [comment]
@LizardByte-bot edit https://www.youtube.com/watch?v=81GpS8_I_Jw

**Comment by jjnether** [comment]
@LizardByte-bot approve
