### ISSUE TITLE
[MOVIE]: And Now for Something Completely Different (1971)

### ISSUE THREAD

**Issue by funkydory** [LizardByte/ThemerrDB#3003]
### Database URL

https://www.themoviedb.org/movie/9267

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=Fb6zQ9wj0Xo

**Comment by jjnether** [comment]
@funkydory Video is private, please replace with different video

**Comment by jjnether** [comment]
@LizardByte-bot edit https://www.youtube.com/watch?v=Fb6zQ9wj0Xo

**Comment by jjnether** [comment]
@LizardByte-bot approve
