### ISSUE TITLE
[MOVIE]: The Big Chill (1983)

### ISSUE THREAD

**Issue by funkydory** [LizardByte/ThemerrDB#3015]
### Database URL

https://www.themoviedb.org/movie/12560

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=VWG3npfEoHo

**Comment by jjnether** [comment]
Editing with song that doesn't have sound effects

**Comment by jjnether** [comment]
@LizardByte-bot edit https://www.youtube.com/watch?v=VWG3npfEoHo

**Comment by jjnether** [comment]
@LizardByte-bot approve
