### ISSUE TITLE
[MOVIE]: Bill & Ted Face the Music (2020)

### ISSUE THREAD

**Issue by funkydory** [LizardByte/ThemerrDB#3019]
### Database URL

https://www.themoviedb.org/movie/501979

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=MCbJSGWim9E&list=PLzzIkwkMf766L34rFi7kYHv1bWkrM2jsr

**Comment by jjnether** [comment]
@LizardByte-bot approve
