### ISSUE TITLE
[MOVIE]: Can't Stop the Music (1980)

### ISSUE THREAD

**Issue by funkydory** [LizardByte/ThemerrDB#3023]
### Database URL

https://www.themoviedb.org/movie/40932

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=uKRPt_a2J8M

**Comment by jjnether** [comment]
Editing with the actual song

**Comment by jjnether** [comment]
@LizardByte-bot edit https://www.youtube.com/watch?v=uKRPt_a2J8M

**Comment by jjnether** [comment]
@LizardByte-bot approve
