### ISSUE TITLE
[MOVIE]: City Slickers II: The Legend of Curly's Gold (1994)

### ISSUE THREAD

**Issue by funkydory** [LizardByte/ThemerrDB#3027]
### Database URL

https://www.themoviedb.org/movie/11310

### YouTube Theme Song Video URL

https://youtu.be/KRQ2ahmO72o?si=QgqOkXir7t2f0E89

**Comment by jjnether** [comment]
@funkydory You uploaded the same theme from the first movie. How about this instead from the second movie?

https://youtu.be/KRQ2ahmO72o?si=QgqOkXir7t2f0E89

**Comment by jjnether** [comment]
@LizardByte-bot edit https://youtu.be/KRQ2ahmO72o?si=QgqOkXir7t2f0E89

**Comment by jjnether** [comment]
@LizardByte-bot approve
