### ISSUE TITLE
[MOVIE]: Cocoon (1985)

### ISSUE THREAD

**Issue by funkydory** [LizardByte/ThemerrDB#3030]
### Database URL

https://www.themoviedb.org/movie/10328

### YouTube Theme Song Video URL

https://youtu.be/Bze-37ZP4qk?si=boAyPWJo99nMmYgH

**Comment by jjnether** [comment]
@funkydory Theme is too long, how about this instead?

https://youtu.be/Bze-37ZP4qk?si=boAyPWJo99nMmYgH

**Comment by jjnether** [comment]
@LizardByte-bot edit https://youtu.be/Bze-37ZP4qk?si=boAyPWJo99nMmYgH

**Comment by jjnether** [comment]
@LizardByte-bot approve
