### ISSUE TITLE
[MOVIE]: The Day the Earth Stood Still (1951)

### ISSUE THREAD

**Issue by funkydory** [LizardByte/ThemerrDB#3037]
### Database URL

https://www.themoviedb.org/movie/828

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=XHs1ysraqDw&list=PLyhuKbqT8gVGeqcFQ5y0qyE54TZn-XJ5P

**Comment by jjnether** [comment]
@LizardByte-bot approve
