### ISSUE TITLE
[TV SHOW]: True Detective (2014)

### ISSUE THREAD

**Issue by tubben** [LizardByte/ThemerrDB#3069]
### Database URL

https://www.themoviedb.org/tv/46648

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=a7kk0KSGPs0

**Comment by jjnether** [comment]
Replacing with fixed theme

**Comment by jjnether** [comment]
@LizardByte-bot edit https://www.youtube.com/watch?v=a7kk0KSGPs0

**Comment by jjnether** [comment]
@LizardByte-bot approve
