### ISSUE TITLE
[MOVIE]: An American Tail (1986)

### ISSUE THREAD

**Issue by funkydory** [LizardByte/ThemerrDB#3085]
### Database URL

https://www.themoviedb.org/movie/4978

### YouTube Theme Song Video URL

https://youtu.be/e8sx6HRTo34?si=fCesTlS9H3cnMchJ

**Comment by jjnether** [comment]
@funkydory Theme is a bit long and not very audible for the first 30 sec. How about this instead?

https://youtu.be/e8sx6HRTo34?si=fCesTlS9H3cnMchJ

**Comment by funkydory** [comment]
Changed to suggested url for YouTube

**Comment by jjnether** [comment]
@LizardByte-bot approve
