### ISSUE TITLE
[MOVIE]: The Best Little Whorehouse in Texas (1982)

### ISSUE THREAD

**Issue by funkydory** [LizardByte/ThemerrDB#3088]
### Database URL

https://www.themoviedb.org/movie/16363

### YouTube Theme Song Video URL

https://youtu.be/t4CZ1aBpxwQ?si=CX2OgY-eRg-5Eemp

**Comment by jjnether** [comment]
@funkydory Theme is a bit long, how about this instead?

https://youtu.be/t4CZ1aBpxwQ?si=CX2OgY-eRg-5Eemp

**Comment by jjnether** [comment]
@LizardByte-bot edit https://youtu.be/t4CZ1aBpxwQ?si=CX2OgY-eRg-5Eemp

**Comment by jjnether** [comment]
@LizardByte-bot approve
