### ISSUE TITLE
[MOVIE]: The Boss Baby: Family Business (2021)

### ISSUE THREAD

**Issue by funkydory** [LizardByte/ThemerrDB#3093]
### Database URL

https://www.themoviedb.org/movie/459151

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=fY5CBEBhgF0&list=PLJIEpdZoj5dswWkMIY38ZHwHkRh1IGluL

**Comment by jjnether** [comment]
@LizardByte-bot approve
