### ISSUE TITLE
[MOVIE]: Can't Buy Me Love (1987)

### ISSUE THREAD

**Issue by funkydory** [LizardByte/ThemerrDB#3095]
### Database URL

https://www.themoviedb.org/movie/12919

### YouTube Theme Song Video URL

https://youtu.be/tDRBu4DDrRI?si=1OS1t4ouI5n-mIXe

**Comment by jjnether** [comment]
Editing with song alone, you had the whole soundtrack in one video

**Comment by jjnether** [comment]
@LizardByte-bot edit https://youtu.be/tDRBu4DDrRI?si=1OS1t4ouI5n-mIXe

**Comment by jjnether** [comment]
@LizardByte-bot approve
