### ISSUE TITLE
[TV SHOW]: Ugly Betty (2006)

### ISSUE THREAD

**Issue by ToffeMaister** [LizardByte/ThemerrDB#3099]
### Database URL

https://www.themoviedb.org/tv/4626

### YouTube Theme Song Video URL

https://youtu.be/XZGe9MqBXWg?si=_mkB3uhHfe38zEFc

**Comment by jjnether** [comment]
@ToffeMaister Theme is too short, how about this instead?

https://youtu.be/XZGe9MqBXWg?si=_mkB3uhHfe38zEFc

**Comment by jjnether** [comment]
@LizardByte-bot edit https://youtu.be/XZGe9MqBXWg?si=_mkB3uhHfe38zEFc

**Comment by jjnether** [comment]
@LizardByte-bot approve
