### ISSUE TITLE
[TV SHOW]: True Detective (2014)

### ISSUE THREAD

**Issue by lguerard** [LizardByte/ThemerrDB#3108]
### Database URL

https://www.themoviedb.org/tv/46648

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=p4zluA60hjs

**Comment by jjnether** [comment]
@lguerard A theme for this already exists. When replacing a theme, please comment your reason for the theme replacement.

**Comment by lguerard** [comment]
Oops sorry, I didn't see that one was already existed.
