### ISSUE TITLE
[TV SHOW]: Black Mirror (2011)

### ISSUE THREAD

**Issue by lguerard** [LizardByte/ThemerrDB#3111]
### Database URL

https://www.themoviedb.org/tv/42009

### YouTube Theme Song Video URL

https://youtu.be/xlyiIHjCOhE?si=ECiQ9qRZHGGLds53

**Comment by jjnether** [comment]
@lguerard the video you posted isn't really music. How about this instead?

https://youtu.be/xlyiIHjCOhE?si=ECiQ9qRZHGGLds53

**Comment by lguerard** [comment]
That sounds ok, the series is quite special and has plenty of different music types and songs that are for specific episodes, so any is fine for me :)

**Comment by jjnether** [comment]
@LizardByte-bot edit https://youtu.be/xlyiIHjCOhE?si=ECiQ9qRZHGGLds53

**Comment by jjnether** [comment]
@LizardByte-bot approve
