### ISSUE TITLE
[MOVIE]: Casablanca (1943)

### ISSUE THREAD

**Issue by lguerard** [LizardByte/ThemerrDB#3114]
### Database URL

https://www.themoviedb.org/movie/289

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=d22CiKMPpaY

**Comment by jjnether** [comment]
Editing with song from the actual movie

**Comment by jjnether** [comment]
@LizardByte-bot https://www.youtube.com/watch?v=d22CiKMPpaY

**Comment by jjnether** [comment]
@LizardByte-bot edit https://www.youtube.com/watch?v=d22CiKMPpaY

**Comment by jjnether** [comment]
@LizardByte-bot approve
