### ISSUE TITLE
[MOVIE]: It's Always Fair Weather (1955)

### ISSUE THREAD

**Issue by lguerard** [LizardByte/ThemerrDB#3122]
### Database URL

https://www.themoviedb.org/movie/17640

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=16al08KsuU0

**Comment by jjnether** [comment]
@lguerard She's kinda just talking in the first part. How about this instead?

https://www.youtube.com/watch?v=16al08KsuU0

**Comment by jjnether** [comment]
@LizardByte-bot edit https://www.youtube.com/watch?v=16al08KsuU0

**Comment by jjnether** [comment]
@LizardByte-bot approve
