### ISSUE TITLE
[TV SHOW]: Belgravia (2020)

### ISSUE THREAD

**Issue by lguerard** [LizardByte/ThemerrDB#3123]
### Database URL

https://www.themoviedb.org/tv/85862

### YouTube Theme Song Video URL

https://youtu.be/MK2fX3yIZ2k?si=HRreSM3pUvZaC5ci

**Comment by jjnether** [comment]
@lguerard Theme is a bit long, how about this instead?

https://youtu.be/MK2fX3yIZ2k?si=HRreSM3pUvZaC5ci

**Comment by lguerard** [comment]
Sounds good, thanks a lot !

**Comment by jjnether** [comment]
@LizardByte-bot approve
