### ISSUE TITLE
[MOVIE]: Bonne Conduite (2023)

### ISSUE THREAD

**Issue by lguerard** [LizardByte/ThemerrDB#3124]
### Database URL

https://www.themoviedb.org/movie/974561

### YouTube Theme Song Video URL

https://youtu.be/9ogTqDU3chk?si=Bgck2pzli11Vnf7b

**Comment by jjnether** [comment]
@lguerard There isn't anything audible until about 30 sec in. How about this instead?

https://youtu.be/9ogTqDU3chk?si=Bgck2pzli11Vnf7b

**Comment by lguerard** [comment]
I couldn't find a better one so all good, thanks

**Comment by jjnether** [comment]
@LizardByte-bot edit https://youtu.be/9ogTqDU3chk?si=Bgck2pzli11Vnf7b

**Comment by jjnether** [comment]
@LizardByte-bot approve
