### ISSUE TITLE
[MOVIE]: Elvis (2022)

### ISSUE THREAD

**Issue by titus91360** [LizardByte/ThemerrDB#3143]
### Database URL

https://www.themoviedb.org/movie/614934

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=Xb6DG4G8vy8&list=PLbPzSVIJFd4EEhN581dFztlghLtSZ_AbM

**Comment by jjnether** [comment]
@titus91360 A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
