### ISSUE TITLE
[MOVIE]: V/H/S (2012)

### ISSUE THREAD

**Issue by tylerbickel** [LizardByte/ThemerrDB#319]
### TheMovieDB URL

https://www.themoviedb.org/movie/84348

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=oobPDNY8SoM

**Comment by ReenigneArcher** [comment]
An exception on this one.

**Comment by tylerbickel** [comment]
That means find a different link? What is the issue?
________________________________

**Comment by tylerbickel** [comment]
Oops another age restriction… those would play if they’ve added their age appropriate YT credentials right? You’re looking for the most accessible option I’m sure.
________________________________

**Comment by tylerbickel** [comment]
Updated YT link without age restriction.

**Comment by ReenigneArcher** [comment]
> those would play if they’ve added their age appropriate YT credentials right

Correct, it should work like that in the plugin... I think it's kind of a pain to add credentials though since you have to create an app specific password if I recall.

If we can avoid the age restricted content I think that would be ideal. If we can't, it not the end of the world.
