### ISSUE TITLE
[MOVIE]: Alien Resurrection (1997)

### ISSUE THREAD

**Issue by K3rn3l-P** [LizardByte/ThemerrDB#3195]
### Database URL

https://www.themoviedb.org/movie/8078

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=nKJHZOnZFJQ&list=PLohYzz4btpaQ8gDG3pZijyKWtLK1CBP_r

**Comment by jjnether** [comment]
@K3rn3l-P A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
