### ISSUE TITLE
[MOVIE]: The Matrix (1999)

### ISSUE THREAD

**Issue by K3rn3l-P** [LizardByte/ThemerrDB#3197]
### Database URL

https://www.themoviedb.org/movie/603

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=dzEtP6fpbOo&list=PLkAUJkbhd-RjPcRCzWfddeeDmeheHCoLX

**Comment by jjnether** [comment]
@K3rn3l-P Theme already exists. When replacing a theme, please comment your reason for the theme replacement.
