### ISSUE TITLE
[MOVIE]: Rocky (1976)

### ISSUE THREAD

**Issue by K3rn3l-P** [LizardByte/ThemerrDB#3198]
### Database URL

https://www.themoviedb.org/movie/1366

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=KUbh-e2J_h8&list=PLNwVhFRTji9CueUWhvISh5ivU7535xiT2

**Comment by jjnether** [comment]
@K3rn3l-P Theme already exists. When replacing a theme, please comment your reason for the theme replacement.
