### ISSUE TITLE
[TV SHOW]: Mr. Robot (2015)

### ISSUE THREAD

**Issue by K3rn3l-P** [LizardByte/ThemerrDB#3199]
### Database URL

https://www.themoviedb.org/tv/62560

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=OQOeePhNj-I&list=PLFclG9NFqg0bBNDGVk3Eul-jU5m9gLaDi&index=9

**Comment by jjnether** [comment]
@LizardByte-bot approve
