### ISSUE TITLE
[TV SHOW]: Jujutsu Kaisen (2020)

### ISSUE THREAD

**Issue by K3rn3l-P** [LizardByte/ThemerrDB#3202]
### Database URL

https://www.themoviedb.org/tv/95479

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=FtRp6svwSY4&list=PLOseTNHq-Flc1jOx1vh2iuY3lypHFYbAk&index=59

**Comment by jjnether** [comment]
@LizardByte-bot approve
