### ISSUE TITLE
[MOVIE]: In the Heights (2021)

### ISSUE THREAD

**Issue by satyasuchak** [LizardByte/ThemerrDB#3203]
### Database URL

https://www.themoviedb.org/movie/467909

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=RrIAUhmQsXM

**Comment by jjnether** [comment]
@satyasuchak Theme is quite long, how about this instead?

https://www.youtube.com/watch?v=RrIAUhmQsXM

**Comment by satyasuchak** [comment]
works :)

**Comment by jjnether** [comment]
@LizardByte-bot approve
