### ISSUE TITLE
[MOVIE]: Rocky II (1979)

### ISSUE THREAD

**Issue by K3rn3l-P** [LizardByte/ThemerrDB#3206]
### Database URL

https://www.themoviedb.org/movie/1367

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=EE-I7-5qcB8&list=PLN9czHtAsHftn_8bqcHA65vQkgnX4bFZj

**Comment by jjnether** [comment]
@K3rn3l-P Theme already exists. When replacing a theme, please comment your reason for the theme replacement.
