### ISSUE TITLE
[MOVIE]: Rocky III (1982)

### ISSUE THREAD

**Issue by K3rn3l-P** [LizardByte/ThemerrDB#3207]
### Database URL

https://www.themoviedb.org/movie/1371

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=0IFhi49ATFk&list=PL8Lpw39GxwbNZ0rkiHlT4SJGcd9t6JdOo

**Comment by jjnether** [comment]
@K3rn3l-P Theme already exists. When replacing a theme, please comment your reason for the theme replacement.
