### ISSUE TITLE
[MOVIE]: 3:10 to Yuma (2007)

### ISSUE THREAD

**Issue by garlik82** [LizardByte/ThemerrDB#3214]
### Database URL

https://www.themoviedb.org/movie/5176

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=61B6Z6CRfac

**Comment by garlik82** [comment]
Getting an error saying the previous link isn't available anymore.

**Comment by jjnether** [comment]
@LizardByte-bot approve
