### ISSUE TITLE
[MOVIE]: The Hunt for Red October (1990)

### ISSUE THREAD

**Issue by Mati232411** [LizardByte/ThemerrDB#3216]
### Database URL

https://www.themoviedb.org/movie/1669

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=MRG1UixHvos

**Comment by jjnether** [comment]
@Mati232411 A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
