### ISSUE TITLE
[MOVIE]: Aliens (1986)

### ISSUE THREAD

**Issue by wh3d0ubl3d** [LizardByte/ThemerrDB#3219]
### Database URL

https://www.themoviedb.org/movie/679

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=wnPJRJbVEIg

**Comment by jjnether** [comment]
@wh3d0ubl3d A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
