### ISSUE TITLE
[TV SHOW]: Hannibal (2013)

### ISSUE THREAD

**Issue by corgan2222** [LizardByte/ThemerrDB#3232]
### Database URL

https://www.themoviedb.org/tv/40008

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=Gl0oIJvtzjA

**Comment by jjnether** [comment]
Theme a bit short, replacing with extended version.

**Comment by jjnether** [comment]
@LizardByte-bot edit https://www.youtube.com/watch?v=Gl0oIJvtzjA

**Comment by jjnether** [comment]
@LizardByte-bot approve
