### ISSUE TITLE
[TV SHOW]: The Chemistry of Death (2023)

### ISSUE THREAD

**Issue by corgan2222** [LizardByte/ThemerrDB#3239]
### Database URL

https://www.themoviedb.org/tv/217180

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=lKn-2gH5kdA

**Comment by jjnether** [comment]
@corgan2222 This is a trailer and has dialogue in it. Please replace with a proper theme that doesn't contain dialogue.
