### ISSUE TITLE
[TV SHOW]: The Walking Dead (2010)

### ISSUE THREAD

**Issue by corgan2222** [LizardByte/ThemerrDB#3245]
### Database URL

https://www.themoviedb.org/tv/1402

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=v5ISBJc1wFk

**Comment by jjnether** [comment]
@corgan2222 A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
