### ISSUE TITLE
[TV SHOW]: True Detective (2014)

### ISSUE THREAD

**Issue by corgan2222** [LizardByte/ThemerrDB#3246]
### Database URL

https://www.themoviedb.org/tv/46648-true-detective

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=p4zluA60hjs

**Comment by jjnether** [comment]
@corgan2222 A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
