### ISSUE TITLE
[MOVIE]: 10 Cloverfield Lane (2016)

### ISSUE THREAD

**Issue by manosrh** [LizardByte/ThemerrDB#3254]
### Database URL

https://www.themoviedb.org/movie/333371

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=pbSsw7e1nDk

**Comment by jjnether** [comment]
@manosrh A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
