### ISSUE TITLE
[MOVIE]: 2001: A Space Odyssey (1968)

### ISSUE THREAD

**Issue by manosrh** [LizardByte/ThemerrDB#3266]
### Database URL

https://www.themoviedb.org/movie/62

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=QwxYiVXYyVs&t=19

**Comment by jjnether** [comment]
@manosrh A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
