### ISSUE TITLE
[MOVIE]: Men in Black (1997)

### ISSUE THREAD

**Issue by MrBoneCrash** [LizardByte/ThemerrDB#3270]
### Database URL

https://www.themoviedb.org/movie/607

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=jyb33RgAxis

**Comment by MrBoneCrash** [comment]
@jjnether Sorry, I didn't see that, I submitted it because Themerr shows this 
![image](https://github.com/LizardByte/ThemerrDB/assets/41182882/3d78831d-c406-41b7-8efc-2b3464664f04)

**Comment by jjnether** [comment]
@MrBoneCrash No worries, sometimes it takes a day or two for Themerr to update. You can confirm that the theme exists [here](https://app.lizardbyte.dev/ThemerrDB)

**Comment by MrBoneCrash** [comment]
@jjnether Thanks for the info. 
It was my mistake that the theme wasnt downloaded, had no permissions to the folder.
A thing to note, if not intentional the error message shown is this:
![image](https://github.com/LizardByte/ThemerrDB/assets/41182882/7025e843-f0db-4169-bfb0-9ef6203c99ff)

**Comment by jjnether** [comment]
@MrBoneCrash Hmm I'm not sure, if you want you can join the [lizardbyte discord](https://discord.gg/lizardbyte-804382334370578482) and submit a post under Themerr
