### ISSUE TITLE
[MOVIE]: Who Framed Roger Rabbit (1988)

### ISSUE THREAD

**Issue by wildsavage** [LizardByte/ThemerrDB#3326]
### Database URL

https://www.themoviedb.org/movie/856

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=p05jnlxyEOA

**Comment by jjnether** [comment]
@wildsavage A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
