### ISSUE TITLE
[MOVIE]: Gravity (2013)

### ISSUE THREAD

**Issue by wildsavage** [LizardByte/ThemerrDB#3327]
### Database URL

https://www.themoviedb.org/movie/49047

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=QRH-uuI7xYk&list=PLDmdF1ma6cZplDv3cr6d3yefkW39Eq-N6&index=1

**Comment by jjnether** [comment]
@LizardByte-bot approve
