### ISSUE TITLE
[MOVIE]: Spaceman (2024)

### ISSUE THREAD

**Issue by kadu247** [LizardByte/ThemerrDB#3329]
### Database URL

https://www.themoviedb.org/movie/636706

### YouTube Theme Song Video URL

https://youtu.be/NS1IqjQN-AU?si=LFS5OsCSbmkqHLkU

**Comment by jjnether** [comment]
@kadu247 theme is too long. How about this instead?

https://youtu.be/NS1IqjQN-AU?si=LFS5OsCSbmkqHLkU

**Comment by jjnether** [comment]
@LizardByte-bot edit https://youtu.be/NS1IqjQN-AU?si=LFS5OsCSbmkqHLkU

**Comment by jjnether** [comment]
@LizardByte-bot approve
