### ISSUE TITLE
[MOVIE]: Damsel (2024)

### ISSUE THREAD

**Issue by kadu247** [LizardByte/ThemerrDB#3330]
### Database URL

https://www.themoviedb.org/movie/763215

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=_RgBp8sKnLA&list=PLLv3qeuV3YDqx_syHreOEmYOIhJSVaS_3

**Comment by jjnether** [comment]
@kadu247 Theme is pretty inaudible for the first 30 sec or so, how about this instead?

https://youtu.be/NTdE0XgueC0?si=fAv9rbJhI2J_0lex
