### ISSUE TITLE
[MOVIE]: A Prayer Before Dawn (2018)

### ISSUE THREAD

**Issue by mo-st** [LizardByte/ThemerrDB#3362]
### Database URL

https://www.themoviedb.org/movie/448776

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=r3nkhDK6lnw

**Comment by jjnether** [comment]
@mo-st Theme is too long. How about this instead from the movie?

https://www.youtube.com/watch?v=r3nkhDK6lnw

**Comment by mo-st** [comment]
Sure, that fits nicely as well! Thanks jjnether

**Comment by jjnether** [comment]
@LizardByte-bot edit https://www.youtube.com/watch?v=r3nkhDK6lnw

**Comment by jjnether** [comment]
@LizardByte-bot approve
