### ISSUE TITLE
[TV SHOW]: BLUE EYE SAMURAI (2023)

### ISSUE THREAD

**Issue by mo-st** [LizardByte/ThemerrDB#3370]
### Database URL

https://www.themoviedb.org/tv/225180

### YouTube Theme Song Video URL

https://youtu.be/jisMZ6nSuKU?si=eyL6adJrCiSnWcFj

**Comment by jjnether** [comment]
Theme is too long. Editing with a shorter one that starts with the same theme.

**Comment by jjnether** [comment]
@LizardByte-bot edit https://youtu.be/jisMZ6nSuKU?si=eyL6adJrCiSnWcFj

**Comment by jjnether** [comment]
@LizardByte-bot approve
