### ISSUE TITLE
[MOVIE]: Psycho-Pass: Providence (2023)

### ISSUE THREAD

**Issue by spirytuslove** [LizardByte/ThemerrDB#3378]
### Database URL

https://www.themoviedb.org/movie/1012652

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=Y3qkb87eBuc

**Comment by jjnether** [comment]
@spirytuslove Please edit video, it's unavailable.

**Comment by ooTruffle** [comment]
After doing some searching it seems like this is the new video

https://www.youtube.com/watch?v=Y3qkb87eBuc

**Comment by jjnether** [comment]
@LizardByte-bot edit https://www.youtube.com/watch?v=Y3qkb87eBuc

**Comment by jjnether** [comment]
@LizardByte-bot approve
