### ISSUE TITLE
[MOVIE]: Spirited Away (2001)

### ISSUE THREAD

**Issue by Alexandre1a** [LizardByte/ThemerrDB#3398]
### Database URL

https://www.themoviedb.org/movie/129

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=TK1Ij_-mank

**Comment by jjnether** [comment]
@Alexandre1a A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
