### ISSUE TITLE
[MOVIE]: Amityville II: The Possession (1982)

### ISSUE THREAD

**Issue by gjlutz** [LizardByte/ThemerrDB#3425]
### Database URL

https://www.themoviedb.org/movie/16235

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=6sjOLMfMjYY&list=PLkYIEW7FWeHy06GIoQOZH8u3613dQmdgM&index=1

**Comment by jjnether** [comment]
@LizardByte-bot approve
