### ISSUE TITLE
[MOVIE]: Initiation Love (2015)

### ISSUE THREAD

**Issue by laheeee666** [LizardByte/ThemerrDB#3434]
### Database URL

https://www.themoviedb.org/movie/345731

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=OOza2ZLY5NA&list=PLjQGyQRiJ3AOQPwkw1H8oScsnDWRShFma&index=3

**Comment by jjnether** [comment]
@LizardByte-bot approve
