### ISSUE TITLE
[MOVIE]: Ah, Wilderness: Part 2 (2017)

### ISSUE THREAD

**Issue by laheeee666** [LizardByte/ThemerrDB#3438]
### Database URL

https://www.themoviedb.org/movie/490916

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=G4LUegu-yVc

**Comment by jjnether** [comment]
Editing with song without movie dialogue

**Comment by jjnether** [comment]
@LizardByte-bot edit https://www.youtube.com/watch?v=G4LUegu-yVc

**Comment by jjnether** [comment]
@LizardByte-bot approve
