### ISSUE TITLE
[MOVIE]: Ah, Wilderness: Part 1 (2017)

### ISSUE THREAD

**Issue by laheeee666** [LizardByte/ThemerrDB#3439]
### Database URL

https://www.themoviedb.org/movie/410227

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=G4LUegu-yVc

**Comment by jjnether** [comment]
@LizardByte-bot edit https://www.youtube.com/watch?v=G4LUegu-yVc

**Comment by jjnether** [comment]
@LizardByte-bot approve
