### ISSUE TITLE
[MOVIE]: About Last Night... (1986)

### ISSUE THREAD

**Issue by gjlutz** [LizardByte/ThemerrDB#3445]
### Database URL

https://www.themoviedb.org/movie/18169

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=cJq0-hB0-RI&list=PLT4KKjsnL7Wcrz9fEjHYgx8PF1NkfNvW4

**Comment by jjnether** [comment]
@LizardByte-bot approve
