### ISSUE TITLE
[MOVIE]: The Age of Adaline (2015)

### ISSUE THREAD

**Issue by gjlutz** [LizardByte/ThemerrDB#3446]
### Database URL

https://www.themoviedb.org/movie/293863

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=Ij9vhGaig-s&list=PLatC4grZcvag_ZtkAoi_d4h-s6VjTfk3K

**Comment by jjnether** [comment]
@LizardByte-bot approve
