### ISSUE TITLE
[MOVIE]: Another 48 Hrs. (1990)

### ISSUE THREAD

**Issue by gjlutz** [LizardByte/ThemerrDB#3447]
### Database URL

https://www.themoviedb.org/movie/11595

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=FI__sUbQ_6s&list=PLH9C08qrQ7S5PHX2VdveOWsJ0o8Q592WD

**Comment by jjnether** [comment]
@LizardByte-bot approve
