### ISSUE TITLE
[MOVIE]: Antebellum (2020)

### ISSUE THREAD

**Issue by gjlutz** [LizardByte/ThemerrDB#3448]
### Database URL

https://www.themoviedb.org/movie/627290

### YouTube Theme Song Video URL

https://youtu.be/bVXvzi5dzW8?si=WP6C8O43rHaxAAAC

**Comment by jjnether** [comment]
@gjlutz Theme is too long. How about this instead?

https://youtu.be/bVXvzi5dzW8?si=WP6C8O43rHaxAAAC

**Comment by gjlutz** [comment]
@jjnether My apologies - yes this works.  Is there a time limit I need to keep in mind?

**Comment by jjnether** [comment]
@gjlutz Yeah just check the guidelines [here](https://github.com/LizardByte/ThemerrDB/blob/master/docs/Theme_Guidelines.md)

**Comment by jjnether** [comment]
@LizardByte-bot edit https://youtu.be/bVXvzi5dzW8?si=WP6C8O43rHaxAAAC

**Comment by gjlutz** [comment]
@jjnether thank you!  I somehow missed this.  I’ll use this moving forward.

**Comment by jjnether** [comment]
> @jjnether thank you! I somehow missed this. I’ll use this moving forward.

No worries. The theme length is not a hard rule, just try to look for themes that are shorter. But if only a longer one exists, it can work

**Comment by jjnether** [comment]
@LizardByte-bot approve
