### ISSUE TITLE
[MOVIE]: Babe: Pig in the City (1998)

### ISSUE THREAD

**Issue by gjlutz** [LizardByte/ThemerrDB#3450]
### Database URL

https://www.themoviedb.org/movie/9447

### YouTube Theme Song Video URL

https://youtu.be/LNVAFTmaWqg?si=wQWQ9CN9noo2PvPx

**Comment by jjnether** [comment]
@gjlutz Theme you put has words at the beginning. How about this instead?

https://youtu.be/LNVAFTmaWqg?si=wQWQ9CN9noo2PvPx

**Comment by jjnether** [comment]
@LizardByte-bot edit https://youtu.be/LNVAFTmaWqg?si=wQWQ9CN9noo2PvPx

**Comment by jjnether** [comment]
@LizardByte-bot approve
