### ISSUE TITLE
[MOVIE COLLECTION]: Monsters, Inc. Collection

### ISSUE THREAD

**Issue by x1ao4** [LizardByte/ThemerrDB#3460]
### Database URL

https://www.themoviedb.org/collection/137696

### YouTube Theme Song Video URL

https://youtu.be/PfFepOnARFA?si=HAb-UH8Ob6N1Wo8D

**Comment by jjnether** [comment]
@x1ao4 I think songs from the first movie are more iconic for this collection. What do you think about this instead?

https://youtu.be/PfFepOnARFA?si=HAb-UH8Ob6N1Wo8D

**Comment by x1ao4** [comment]
> @x1ao4 I think songs from the first movie are more iconic for this collection. What do you think about this instead?
> 
> https://youtu.be/PfFepOnARFA?si=HAb-UH8Ob6N1Wo8D

Good choice.

**Comment by jjnether** [comment]
@LizardByte-bot edit https://youtu.be/PfFepOnARFA?si=HAb-UH8Ob6N1Wo8D

**Comment by jjnether** [comment]
@LizardByte-bot approve
