### ISSUE TITLE
[MOVIE COLLECTION]: The Amazing Spider-Man Collection

### ISSUE THREAD

**Issue by x1ao4** [LizardByte/ThemerrDB#3461]
### Database URL

https://www.themoviedb.org/collection/125574

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=eBOajc3tZDs

**Comment by jjnether** [comment]
@x1ao4 What do you think about this theme instead? I think a bit better for Amazing Spiderman theme.

https://www.youtube.com/watch?v=eBOajc3tZDs

**Comment by x1ao4** [comment]
> https://www.youtube.com/watch?v=eBOajc3tZDs

I like it, sure.

**Comment by jjnether** [comment]
@LizardByte-bot approve
