### ISSUE TITLE
[MOVIE]: Dune (1984)

### ISSUE THREAD

**Issue by gjlutz** [LizardByte/ThemerrDB#3465]
### Database URL

https://www.themoviedb.org/movie/841

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=yE4pPzrkgsM

**Comment by jjnether** [comment]
@gjlutz Theme is far too long. How about this instead?

https://www.youtube.com/watch?v=yE4pPzrkgsM

**Comment by gjlutz** [comment]
@jjnether thank you

**Comment by jjnether** [comment]
@LizardByte-bot edit https://www.youtube.com/watch?v=yE4pPzrkgsM

**Comment by jjnether** [comment]
@LizardByte-bot approve
