### ISSUE TITLE
[MOVIE]: The Beaches of Agnès (2008)

### ISSUE THREAD

**Issue by laheeee666** [LizardByte/ThemerrDB#3472]
### Database URL

https://www.themoviedb.org/movie/38879

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=LmsdHnQ7RD8

**Comment by jjnether** [comment]
@laheeee666 Theme is quite long, is there a shorter theme that can be used?

**Comment by laheeee666** [comment]
https://www.youtube.com/watch?v=LmsdHnQ7RD8

**Comment by jjnether** [comment]
@LizardByte-bot edit https://www.youtube.com/watch?v=LmsdHnQ7RD8

**Comment by jjnether** [comment]
@LizardByte-bot approve
