### ISSUE TITLE
[MOVIE]: Long Live Love! (2023)

### ISSUE THREAD

**Issue by laheeee666** [LizardByte/ThemerrDB#3475]
### Database URL

https://www.themoviedb.org/movie/1026961

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=MWZeKkkg8eI

**Comment by laheeee666** [comment]
https://www.youtube.com/watch?v=MWZeKkkg8eI

**Comment by jjnether** [comment]
@LizardByte-bot edit https://www.youtube.com/watch?v=MWZeKkkg8eI
