### ISSUE TITLE
[MOVIE]: Before Midnight (2013)

### ISSUE THREAD

**Issue by laheeee666** [LizardByte/ThemerrDB#3481]
### Database URL

https://www.themoviedb.org/movie/132344

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=CYDM-8jAG6U&list=PLGgC73Z3mtU6aomtjYPPFAdOhtvc-wlCI

**Comment by jjnether** [comment]
@LizardByte-bot approve
