### ISSUE TITLE
[MOVIE]: Ice Age: The Meltdown (2006)

### ISSUE THREAD

**Issue by laheeee666** [LizardByte/ThemerrDB#3484]
### Database URL

https://www.themoviedb.org/movie/950

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=mVXbFbCP6uE&list=PLh3-icSKvfhkGP3-fqEzOE6o5n8x1CKIB

**Comment by jjnether** [comment]
@LizardByte-bot approve
