### ISSUE TITLE
[MOVIE]: Ice Age: Dawn of the Dinosaurs (2009)

### ISSUE THREAD

**Issue by laheeee666** [LizardByte/ThemerrDB#3485]
### Database URL

https://www.themoviedb.org/movie/8355

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=YbDpyf_1xys&list=PLp02o2ISMlXb6IsgI0CDqR-fBXFEmMMS5

**Comment by jjnether** [comment]
@LizardByte-bot approve
