### ISSUE TITLE
[MOVIE]: Ice Age: Continental Drift (2012)

### ISSUE THREAD

**Issue by laheeee666** [LizardByte/ThemerrDB#3486]
### Database URL

https://www.themoviedb.org/movie/57800

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=mHX-T3svW_I&list=PLDmdF1ma6cZqL4_3eWLIT_fie4FLSHjMu

**Comment by jjnether** [comment]
@LizardByte-bot approve
