### ISSUE TITLE
[MOVIE]: Fabricated City (2017)

### ISSUE THREAD

**Issue by laheeee666** [LizardByte/ThemerrDB#3489]
### Database URL

https://www.themoviedb.org/movie/435366

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=h9KDHny4BqU&list=PLkVq7v2N3vX5vCJY9xotWA8bLM6zgOYd6&index=3

**Comment by jjnether** [comment]
@LizardByte-bot approve
