### ISSUE TITLE
[MOVIE]: Black Mass (2015)

### ISSUE THREAD

**Issue by gjlutz** [LizardByte/ThemerrDB#3508]
### Database URL

https://www.themoviedb.org/movie/261023

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=VfYUHt8iY8M&list=OLAK5uy_kf23ODKg6Ode827OxxEuynF6Kt8EUzwNc

**Comment by jjnether** [comment]
@LizardByte-bot approve
