### ISSUE TITLE
[MOVIE]: (T)Raumschiff Surprise - Periode 1 (2004)

### ISSUE THREAD

**Issue by i-am-the-real-guru** [LizardByte/ThemerrDB#3517]
### Database URL

https://www.themoviedb.org/movie/9805

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=5sE_vGOC5os&list=PLWIheDdUl4GTKjM4ncI04DSznrNs3u6n-&index=5

**Comment by jjnether** [comment]
@LizardByte-bot approve
