### ISSUE TITLE
[TV SHOW]: House of the Dragon (2022)

### ISSUE THREAD

**Issue by seb20137** [LizardByte/ThemerrDB#3519]
### Database URL

https://www.themoviedb.org/tv/94997

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=0mmyZ4Y6NkM

**Comment by jjnether** [comment]
@seb20137 A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
