### ISSUE TITLE
[MOVIE]: Bob Marley: One Love (2024)

### ISSUE THREAD

**Issue by kadu247** [LizardByte/ThemerrDB#3524]
### Database URL

https://www.themoviedb.org/movie/802219

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=-zShbxTAXJc&list=PLDhajrZgo0TLbXCRbjrf2Msg4Ql2KffEb

**Comment by jjnether** [comment]
@LizardByte-bot approve
