### ISSUE TITLE
[MOVIE]: Fight Club (1999)

### ISSUE THREAD

**Issue by XIVIX134** [LizardByte/ThemerrDB#3527]
### Database URL

https://www.themoviedb.org/movie/550

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=OJ62RzJkYUo

**Comment by jjnether** [comment]
@XIVIX134 A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.

**Comment by jjnether** [comment]
> The available song isn't the main theme song

@XIVIX134 Ok, please make a comment with the reason next time you're replacing a theme

**Comment by jjnether** [comment]
@LizardByte-bot approve
