### ISSUE TITLE
[TV SHOW]: The Completely Made-Up Adventures of Dick Turpin (2024)

### ISSUE THREAD

**Issue by teslaweiler** [LizardByte/ThemerrDB#3551]
### Database URL

https://www.themoviedb.org/tv/197459

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=vZHFos0_VOs

**Comment by jjnether** [comment]
@teslaweiler A theme for this already exists or was submitted before yours (same theme though). When replacing a theme, please comment your reason for the theme replacement.
