### ISSUE TITLE
[TV SHOW]: Phineas and Ferb (2007)

### ISSUE THREAD

**Issue by ooTruffle** [LizardByte/ThemerrDB#3553]
### Database URL

https://www.themoviedb.org/tv/1877

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=tz19bfsVlGs

**Comment by ooTruffle** [comment]
This is the full theme song for the show, The current one cuts short of the end of even where it would end in the intro

**Comment by jjnether** [comment]
@LizardByte-bot approve
