### ISSUE TITLE
[MOVIE]: Kung Fu Panda (2008)

### ISSUE THREAD

**Issue by x1ao4** [LizardByte/ThemerrDB#3557]
### Database URL

https://www.themoviedb.org/movie/9502

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=eqJxJmb-Q4Y

**Comment by jjnether** [comment]
@x1ao4 A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
