### ISSUE TITLE
[MOVIE]: Cujo (1983)

### ISSUE THREAD

**Issue by gjlutz** [LizardByte/ThemerrDB#3573]
### Database URL

https://www.themoviedb.org/movie/10489

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=L9xWj-BL4v8&list=PLh3-icSKvfhnOBuw57sqn48X4CvinGJKHhttps://www.youtube.com/watch?v=L9xWj-BL4v8&list=PLh3-icSKvfhnOBuw57sqn48X4CvinGJKH

**Comment by jjnether** [comment]
@LizardByte-bot approve
