### ISSUE TITLE
[MOVIE]: Cutthroat Island (1995)

### ISSUE THREAD

**Issue by gjlutz** [LizardByte/ThemerrDB#3574]
### Database URL

https://www.themoviedb.org/movie/1408

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=5DiSgwzQfzA&list=PLocqHZj7MJflxQUpxoyuikCZR5bdKUbWL

**Comment by jjnether** [comment]
@LizardByte-bot approve
