### ISSUE TITLE
[MOVIE]: Jurassic World (2015)

### ISSUE THREAD

**Issue by gjlutz** [LizardByte/ThemerrDB#3578]
### Database URL

https://www.themoviedb.org/movie/135397

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=XNyo3Xahzyc&list=PLo-lF9fUuCDTFH-mEvnVnadkRh0xl6ffq

**Comment by jjnether** [comment]
@LizardByte-bot approve
