### ISSUE TITLE
[MOVIE]: Jurassic Park III (2001)

### ISSUE THREAD

**Issue by gjlutz** [LizardByte/ThemerrDB#3579]
### Database URL

https://www.themoviedb.org/movie/331

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=t7hCXuPYMp8&list=PLFlLzKECbcIO78qV2wNH-gMFhKHQdH1VM&index=5

**Comment by jjnether** [comment]
@LizardByte-bot approve
