### ISSUE TITLE
[MOVIE]: Jurassic World: Fallen Kingdom (2018)

### ISSUE THREAD

**Issue by gjlutz** [LizardByte/ThemerrDB#3581]
### Database URL

https://www.themoviedb.org/movie/351286

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=Sn0HCinpr6k&list=PLim3m5NnkYFdBYCLw8U0jMi2pADergou6

**Comment by jjnether** [comment]
@LizardByte-bot approve
