### ISSUE TITLE
[TV SHOW]: Johnny Test (2021)

### ISSUE THREAD

**Issue by ooTruffle** [LizardByte/ThemerrDB#3586]
### Database URL

https://www.themoviedb.org/tv/127753

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=-Jp7Nmykpgk

**Comment by jjnether** [comment]
Editing with theme without netflix sound

**Comment by jjnether** [comment]
@LizardByte-bot edit https://www.youtube.com/watch?v=-Jp7Nmykpgk

**Comment by jjnether** [comment]
@LizardByte-bot approve
