### ISSUE TITLE
[MOVIE]: Meg 2: The Trench (2023)

### ISSUE THREAD

**Issue by andreas-fahrecker** [LizardByte/ThemerrDB#3596]
### Database URL

https://www.themoviedb.org/movie/615656

### YouTube Theme Song Video URL

https://youtu.be/UF9giZxkpbw?si=-UZJF9R2EfcGGzJL

**Comment by jjnether** [comment]
@andreas-fahrecker Theme is too long and doesn't have much audio at the beginning. How about this instead?

https://youtu.be/UF9giZxkpbw?si=-UZJF9R2EfcGGzJL

**Comment by andreas-fahrecker** [comment]
> @andreas-fahrecker Theme is too long and doesn't have much audio at the beginning. How about this instead?
> 
> https://youtu.be/UF9giZxkpbw?si=-UZJF9R2EfcGGzJL

That seems like a much better choice.

**Comment by jjnether** [comment]
@LizardByte-bot edit https://youtu.be/UF9giZxkpbw?si=-UZJF9R2EfcGGzJL

**Comment by jjnether** [comment]
@LizardByte-bot approve
