### ISSUE TITLE
[MOVIE]: Lucy (2014)

### ISSUE THREAD

**Issue by KonstantinasK-1205** [LizardByte/ThemerrDB#3624]
### Database URL

https://www.themoviedb.org/movie/240832

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=C5VYo_VpUEI

**Comment by jjnether** [comment]
@KonstantinasK-1205 A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
