### ISSUE TITLE
[MOVIE]: Whiplash (2014)

### ISSUE THREAD

**Issue by felipemarinho97** [LizardByte/ThemerrDB#3630]
### Database URL

https://www.themoviedb.org/movie/244786

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=-jAtHf9RA4w

**Comment by jjnether** [comment]
@felipemarinho97 A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.

**Comment by felipemarinho97** [comment]
@jjnether there is a bug with the plugin, It's suggesting to me that it can't find the theme and to open an Issue adding it. My Jellyfin is in Portuguese, so I think the plugin is using the pt-BR title instead of the ID, i dont know....

**Comment by jjnether** [comment]
@ReenigneArcher Anything to look into here?

**Comment by ReenigneArcher** [comment]
I'm not sure without more details. I don't think the language matters as we just use the MovieDB id.

**Comment by jjnether** [comment]
@felipemarinho97 If you want to try solving this problem, please submit a report in Themerr on lizardbyte discord with details of your problem and any logs you might have.

**Comment by felipemarinho97** [comment]
@jjnether @ReenigneArcher I created an issue with more info https://github.com/LizardByte/Themerr-jellyfin/issues/296
