### ISSUE TITLE
[TV SHOW]: Battlestar Galactica (2004)

### ISSUE THREAD

**Issue by absarshah** [LizardByte/ThemerrDB#3639]
### Database URL

https://www.themoviedb.org/tv/1972-battlestar-galactica

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=o9iTGIFuLKQ

**Comment by jjnether** [comment]
@absarshah A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
