### ISSUE TITLE
[MOVIE]: The Muppet Christmas Carol (1992)

### ISSUE THREAD

**Issue by gjlutz** [LizardByte/ThemerrDB#3643]
### Database URL

https://www.themoviedb.org/movie/10437

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=jDJ4_fzxb-w&list=PLw4AP6SyWCYxn48T67oH9paJcPE9IHc1M

**Comment by jjnether** [comment]
@LizardByte-bot approve
