### ISSUE TITLE
[MOVIE]: Apocalypse Now (1979)

### ISSUE THREAD

**Issue by BlackCharon142** [LizardByte/ThemerrDB#3649]
### Database URL

https://www.themoviedb.org/movie/28

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=4wdDkfExQ3A

**Comment by jjnether** [comment]
@BlackCharon142 A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
