### ISSUE TITLE
[MOVIE]: Cloudy with a Chance of Meatballs 2 (2013)

### ISSUE THREAD

**Issue by BlackCharon142** [LizardByte/ThemerrDB#3661]
### Database URL

https://www.themoviedb.org/movie/109451

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=nNr_XpunBf8

**Comment by jjnether** [comment]
@BlackCharon142 A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
