### ISSUE TITLE
[MOVIE]: Corpse Bride (2005)

### ISSUE THREAD

**Issue by BlackCharon142** [LizardByte/ThemerrDB#3662]
### Database URL

https://www.themoviedb.org/movie/3933

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=67QeerRPPZw

**Comment by jjnether** [comment]
@BlackCharon142 A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
