### ISSUE TITLE
[MOVIE]: Django Unchained (2012)

### ISSUE THREAD

**Issue by BlackCharon142** [LizardByte/ThemerrDB#3664]
### Database URL

https://www.themoviedb.org/movie/68718

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=lYF6K1HGKIs

**Comment by jjnether** [comment]
@BlackCharon142 A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
