### ISSUE TITLE
[MOVIE]: Expend4bles (2023)

### ISSUE THREAD

**Issue by BlackCharon142** [LizardByte/ThemerrDB#3667]
### Database URL

https://www.themoviedb.org/movie/299054

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=P_SMsoIDP-A

**Comment by jjnether** [comment]
@BlackCharon142 A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
