### ISSUE TITLE
[MOVIE]: Fantastic Beasts and Where to Find Them (2016)

### ISSUE THREAD

**Issue by BlackCharon142** [LizardByte/ThemerrDB#3670]
### Database URL

https://www.themoviedb.org/movie/259316

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=WBOMpfxsUpk

**Comment by jjnether** [comment]
@BlackCharon142 A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
