### ISSUE TITLE
[MOVIE]: Harry Potter and the Goblet of Fire (2005)

### ISSUE THREAD

**Issue by the0nly0ne7** [LizardByte/ThemerrDB#3672]
### Database URL

https://www.themoviedb.org/movie/674

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=wtHra9tFISY

**Comment by jjnether** [comment]
@the0nly0ne7 A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
