### ISSUE TITLE
[TV SHOW]: Bel-Air (2022)

### ISSUE THREAD

**Issue by HomerBeer** [LizardByte/ThemerrDB#3676]
### Database URL

https://www.themoviedb.org/tv/107365

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=0EnRK5YvBwU

**Comment by jjnether** [comment]
Editing with actual song

**Comment by jjnether** [comment]
@LizardByte-bot edit https://www.youtube.com/watch?v=0EnRK5YvBwU

**Comment by jjnether** [comment]
@LizardByte-bot approve
