### ISSUE TITLE
[TV SHOW]: Fallout (2024)

### ISSUE THREAD

**Issue by Yeetov** [LizardByte/ThemerrDB#3683]
### Database URL

https://www.themoviedb.org/tv/106379

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=BLi9sSLAUKc

**Comment by jjnether** [comment]
@Yeetov Theme is a bit long and isn't very audible at the start, another user's submission has been added for this show.

**Comment by Yeetov** [comment]
Ok, I just wanted to help by adding a theme in the first place. :)
