### ISSUE TITLE
[MOVIE]: A Beautiful Mind (2001)

### ISSUE THREAD

**Issue by BlackCharon142** [LizardByte/ThemerrDB#3685]
### Database URL

https://www.themoviedb.org/movie/453

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=e1J8sY8RSfA

**Comment by BlackCharon142** [comment]
Reason for the theme replacement: **The existing link is defective(Video Unavailable)**

**Comment by jjnether** [comment]
Just replacing video with same theme that starts earlier, no country restrictions

**Comment by jjnether** [comment]
@LizardByte-bot edit https://www.youtube.com/watch?v=e1J8sY8RSfA

**Comment by jjnether** [comment]
@LizardByte-bot approve
