### ISSUE TITLE
[MOVIE]: Apocalypse Now (1979)

### ISSUE THREAD

**Issue by BlackCharon142** [LizardByte/ThemerrDB#3688]
### Database URL

https://www.themoviedb.org/movie/28

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=D1bo8j0Io9k

**Comment by BlackCharon142** [comment]
Reason for the theme replacement: **The existing link is defective(Video Unavailable/Copyright Problems)**

**Comment by jjnether** [comment]
@BlackCharon142 song is far too long. Do you have an alternative that is shorter and adheres to the guidelines?

**Comment by jjnether** [comment]
Replacing with a shorter theme that has no geo restrictions

**Comment by jjnether** [comment]
@LizardByte-bot edit https://www.youtube.com/watch?v=D1bo8j0Io9k

**Comment by jjnether** [comment]
@LizardByte-bot approve
