### ISSUE TITLE
[MOVIE]: 10.0 Earthquake (2014)

### ISSUE THREAD

**Issue by Fatwire** [LizardByte/ThemerrDB#3696]
### Database URL

https://www.themoviedb.org/movie/302666

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=52Y1hHjRaJM

**Comment by jjnether** [comment]
I don't believe that song is actually in the movie. Replacing with a theme that is.

**Comment by jjnether** [comment]
@LizardByte-bot edit https://www.youtube.com/watch?v=52Y1hHjRaJM

**Comment by jjnether** [comment]
@LizardByte-bot approve
