### ISSUE TITLE
[MOVIE]: Star Wars: Episode I - The Phantom Menace (1999)

### ISSUE THREAD

**Issue by Rapha149** [LizardByte/ThemerrDB#3704]
### Database URL

https://www.themoviedb.org/movie/1893

### YouTube Theme Song Video URL

https://youtu.be/xlYCxbBZUCY

**Comment by Rapha149** [comment]
The existing theme song as requested in #2214 is country-specific. The version in Themerr

**Comment by jjnether** [comment]
@LizardByte-bot approve
