### ISSUE TITLE
[MOVIE]: Star Wars: Episode III - Revenge of the Sith (2005)

### ISSUE THREAD

**Issue by Rapha149** [LizardByte/ThemerrDB#3706]
### Database URL

https://www.themoviedb.org/movie/1895

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=FHuD5y-PZM0

**Comment by Rapha149** [comment]
I requested this to replace the existing one requested in #2216 because the existing one is not available in countries other than the United States - at least not in Germany (there is a version of this video available in Germany, but that in turn is not available in the US).
The soundtrack is the same, but it's a version that is available in the US and in Germany.

**Comment by jjnether** [comment]
@Rapha149 I realized that previous song is actually quite inaudible until 35 sec in. How about this theme instead? (also no geo restriction)

https://www.youtube.com/watch?v=FHuD5y-PZM0

**Comment by Rapha149** [comment]
That work's too. I chose the other one because it was the non-geoblocked version of the soundtrack that was submitted previously.

**Comment by jjnether** [comment]
@LizardByte-bot edit https://www.youtube.com/watch?v=FHuD5y-PZM0

**Comment by jjnether** [comment]
@LizardByte-bot approve
