### ISSUE TITLE
[TV SHOW]: Steins;Gate (2011)

### ISSUE THREAD

**Issue by 1xFF** [LizardByte/ThemerrDB#3709]
### Database URL

https://www.themoviedb.org/tv/42509

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=TR3ma_60-m4

**Comment by 1xFF** [comment]
Perhaps I should submit a new issue for this, but due to the semicolon in the show's name, I had to manually add the rest of the title.
Not sure if this effects any other part of themerr.

**Comment by ReenigneArcher** [comment]
What plugin are you using?

**Comment by ReenigneArcher** [comment]
Nevermind, I saw your PR. Thank you!

**Comment by ReenigneArcher** [comment]
@LizardByte-bot approve
