### ISSUE TITLE
[MOVIE]: Dune: Part Two (2024)

### ISSUE THREAD

**Issue by starrider346** [LizardByte/ThemerrDB#3711]
### Database URL

https://www.themoviedb.org/movie/693134

### YouTube Theme Song Video URL

https://youtu.be/zzYPIuHi4fA?si=Dm2kAkesSgmnyGBl&t=51

**Comment by jjnether** [comment]
@starrider346 A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
