### ISSUE TITLE
[TV SHOW]: Serial Experiments Lain (1998)

### ISSUE THREAD

**Issue by 1xFF** [LizardByte/ThemerrDB#3712]
### Database URL

https://www.themoviedb.org/tv/1087

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=MM8RufZr5lw

**Comment by 1xFF** [comment]
Maybe this shorter version is more appropriate:
https://www.youtube.com/watch?v=MM8RufZr5lw

**Comment by jjnether** [comment]
@LizardByte-bot edit https://www.youtube.com/watch?v=MM8RufZr5lw

**Comment by jjnether** [comment]
@LizardByte-bot approve
