### ISSUE TITLE
[GAME]: Steins;Gate (2010)

### ISSUE THREAD

**Issue by 1xFF** [LizardByte/ThemerrDB#3716]
### Database URL

https://www.igdb.com/games/steins-gate

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=hzPg6CZj4Yg

**Comment by ReenigneArcher** [comment]
How come you closed it?

**Comment by 1xFF** [comment]
> How come you closed it?

I used the piano version instead of the vocal which is probably more well known, I suppose I could've asked for it to be changed
It should be https://www.youtube.com/watch?v=hzPg6CZj4Yg

**Comment by ReenigneArcher** [comment]
@LizardByte-bot approve

**Comment by ReenigneArcher** [comment]
Thanks for adding a game! We're a bit lacking in that department so far.
