### ISSUE TITLE
[TV SHOW]: Hazbin Hotel (2024)

### ISSUE THREAD

**Issue by M1noa** [LizardByte/ThemerrDB#3725]
### Database URL

https://www.themoviedb.org/tv/94954

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=lyDUfn5f-Lc&pp=ygUXSGF6YmluIEhvdGVsIHRoZW1lIHNvbmc%3D

**Comment by jjnether** [comment]
@LizardByte-bot approve
