### ISSUE TITLE
[TV SHOW]: Ghost in the Shell: SAC_2045 (2020)

### ISSUE THREAD

**Issue by Spood3n** [LizardByte/ThemerrDB#3734]
### Database URL

https://www.themoviedb.org/tv/90293

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=fuXZMQAD9vU

**Comment by jjnether** [comment]
Editing with available song

**Comment by jjnether** [comment]
@LizardByte-bot edit https://www.youtube.com/watch?v=fuXZMQAD9vU

**Comment by jjnether** [comment]
@LizardByte-bot approve
