### ISSUE TITLE
[MOVIE]: Blood & Gold (2023)

### ISSUE THREAD

**Issue by jj3005** [LizardByte/ThemerrDB#3774]
### Database URL

https://www.themoviedb.org/movie/1098110

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=i0ywCQpELwY&list=OLAK5uy_lmhlXzfU1qMgL30OaUGubOBMHZw4ZEWK8&index=18

**Comment by jjnether** [comment]
@LizardByte-bot approve
