### ISSUE TITLE
[MOVIE]: Benny & Joon (1993)

### ISSUE THREAD

**Issue by jj3005** [LizardByte/ThemerrDB#3786]
### Database URL

https://www.themoviedb.org/movie/4104

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=7OjFtBv9BSQ&list=PLhF8g6T36ZhO4tOMrw4PjP6NwxATfpM_u&index=13

**Comment by jjnether** [comment]
@LizardByte-bot approve
