### ISSUE TITLE
[MOVIE]: Vampire Sisters (2012)

### ISSUE THREAD

**Issue by jj3005** [LizardByte/ThemerrDB#3793]
### Database URL

https://www.themoviedb.org/movie/151478

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=xeV8ArvfwAI&list=PLjwh5m03j7Xqe8Et73y6LQGpHhjsThTlz&index=2

**Comment by jjnether** [comment]
@LizardByte-bot approve
