### ISSUE TITLE
[MOVIE]: The Edge of Seventeen (2016)

### ISSUE THREAD

**Issue by jj3005** [LizardByte/ThemerrDB#3795]
### Database URL

https://www.themoviedb.org/movie/376660

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=QhQvXtVPqm0&list=PLzlZnKbYwF7PLvQ18HkE4N9zolmGC3QnZ&index=2

**Comment by jjnether** [comment]
@LizardByte-bot approve
