### ISSUE TITLE
[MOVIE]: Eighth Grade (2018)

### ISSUE THREAD

**Issue by jj3005** [LizardByte/ThemerrDB#3796]
### Database URL

https://www.themoviedb.org/movie/489925

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=1fR7sRmwOj8&list=PLbHI36JYR2GlRRGFZVOo0CJWJAujQEEVZ&index=1

**Comment by jjnether** [comment]
@jj3005 I realized this is actually not a theme in this movie, and was just a random playlist on youtube. Please make sure to check if your song actually applies to the movie
