### ISSUE TITLE
[TV SHOW]: How to Sell Drugs Online (Fast) (2019)

### ISSUE THREAD

**Issue by jj3005** [LizardByte/ThemerrDB#3800]
### Database URL

https://www.themoviedb.org/tv/88236

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=1a5pmxtEGHw&list=PLDisKgcnAC4RWvCaHFDu6QhO8o4pu-6D6

**Comment by jjnether** [comment]
@LizardByte-bot approve
