### ISSUE TITLE
[TV SHOW]: Dear Child (2023)

### ISSUE THREAD

**Issue by jj3005** [LizardByte/ThemerrDB#3802]
### Database URL

https://www.themoviedb.org/tv/229221

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=VPTQTcJHQXg&list=PLACrjduQziWtG7_fweZVhzo_gwmBuyaRj&index=4

**Comment by jjnether** [comment]
@LizardByte-bot approve
