### ISSUE TITLE
[TV SHOW]: The Night Agent (2023)

### ISSUE THREAD

**Issue by jj3005** [LizardByte/ThemerrDB#3804]
### Database URL

https://www.themoviedb.org/tv/129552

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=EqtE_mlkhok&list=PLWWwgAIIK3OMybnWpeYrKJG81crAEs64x&index=2

**Comment by jjnether** [comment]
@LizardByte-bot approve
