### ISSUE TITLE
[TV SHOW]: Sky Rojo (2021)

### ISSUE THREAD

**Issue by jj3005** [LizardByte/ThemerrDB#3806]
### Database URL

https://www.themoviedb.org/tv/117023

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=DnpH_fWomZU&list=PLDisKgcnAC4TQYMPKJAGBU0mBe27IO_l6&index=1

**Comment by jjnether** [comment]
@LizardByte-bot approve
