### ISSUE TITLE
[MOVIE]: Saltburn (2023)

### ISSUE THREAD

**Issue by jj3005** [LizardByte/ThemerrDB#3809]
### Database URL

https://www.themoviedb.org/movie/930564

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=xqSCxsR5g0A&list=PLKybJpxCzqPOoqVPli-z2G38DDMVzXOX6&index=4

**Comment by jjnether** [comment]
@LizardByte-bot approve
