### ISSUE TITLE
[MOVIE]: Jumanji: The Next Level (2019)

### ISSUE THREAD

**Issue by jj3005** [LizardByte/ThemerrDB#3826]
### Database URL

https://www.themoviedb.org/movie/512200

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=0IAoE4lZRIY&list=PLDisKgcnAC4RN5ClcXVDd3R9mCbUAE7KR&index=1

**Comment by jjnether** [comment]
@jj3005 A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
