### ISSUE TITLE
[TV SHOW]: Kill la Kill (2013)

### ISSUE THREAD

**Issue by pieman9876** [LizardByte/ThemerrDB#3839]
### Database URL

https://www.themoviedb.org/tv/60728

### YouTube Theme Song Video URL

https://youtu.be/Lz-uxl3qTwc?si=eoU7zHMBD2XxUWSY

**Comment by jjnether** [comment]
Editing with same theme without age restriction

**Comment by jjnether** [comment]
@LizardByte-bot edit https://youtu.be/Lz-uxl3qTwc?si=eoU7zHMBD2XxUWSY

**Comment by jjnether** [comment]
@LizardByte-bot approve
