### ISSUE TITLE
[MOVIE]: Paprika (2006)

### ISSUE THREAD

**Issue by r-mathieu** [LizardByte/ThemerrDB#3872]
### Database URL

https://www.themoviedb.org/movie/4977

### YouTube Theme Song Video URL

https://youtu.be/DHVijvx-hG4

**Comment by hauveli** [comment]
I got curious and clicked because of the tag.
Youtube video seems to be from [Parasite](https://www.themoviedb.org/movie/496243) and not from Paprika (2006).

**Comment by r-mathieu** [comment]
A new case of copy/paste failure

**Comment by ReenigneArcher** [comment]
You can edit the original issue. Just be careful not to edit the formatting.
