### ISSUE TITLE
[MOVIE]: Aladdin (2019)

### ISSUE THREAD

**Issue by udisteanumarianflavius** [LizardByte/ThemerrDB#3878]
### Database URL

https://www.themoviedb.org/movie/420817

### YouTube Theme Song Video URL

https://m.youtube.com/watch?v=-SMUppzCt0Y&pp=ygUSYWxhZGRpbiBzb3VuZHRyYWNr

**Comment by jjnether** [comment]
@udisteanumarianflavius A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
