### ISSUE TITLE
[MOVIE]: Cinderella (2015)

### ISSUE THREAD

**Issue by udisteanumarianflavius** [LizardByte/ThemerrDB#3879]
### Database URL

https://www.themoviedb.org/movie/150689

### YouTube Theme Song Video URL

https://m.youtube.com/watch?v=-SMUppzCt0Y&pp=ygUSYWxhZGRpbiBzb3VuZHRyYWNr

**Comment by jjnether** [comment]
@udisteanumarianflavius When you make an error with the theme submission, you can simply edit and comment rather than making a new submission
