### ISSUE TITLE
[MOVIE]: Cinderella (2015)

### ISSUE THREAD

**Issue by udisteanumarianflavius** [LizardByte/ThemerrDB#3880]
### Database URL

https://www.themoviedb.org/movie/150689

### YouTube Theme Song Video URL

https://m.youtube.com/watch?v=b3s3hW5-iDQ&list=PLh3-icSKvfhnlpoztRd5Zn4S607eOaso7&index=1&pp=iAQB8AUB

**Comment by jjnether** [comment]
@LizardByte-bot approve
