### ISSUE TITLE
[MOVIE]: Fantastic Beasts and Where to Find Them (2016)

### ISSUE THREAD

**Issue by udisteanumarianflavius** [LizardByte/ThemerrDB#3881]
### Database URL

https://www.themoviedb.org/movie/259316

### YouTube Theme Song Video URL

https://youtu.be/WY4GOkOOXQg?si=gTkc6fpsHHUvjCJV

**Comment by jjnether** [comment]
Editing to fix link (ideally we don't link with playlist)

**Comment by jjnether** [comment]
@LizardByte-bot edit https://youtu.be/WY4GOkOOXQg?si=gTkc6fpsHHUvjCJV

**Comment by jjnether** [comment]
@LizardByte-bot approve
