### ISSUE TITLE
[MOVIE]: Ballerina (2016)

### ISSUE THREAD

**Issue by udisteanumarianflavius** [LizardByte/ThemerrDB#3882]
### Database URL

https://www.themoviedb.org/movie/342473

### YouTube Theme Song Video URL

https://m.youtube.com/watch?v=gUmxQCd05QM&pp=ygUVYmFsbGVyaW5hIHNvdW5kdHJhY2tz

**Comment by jjnether** [comment]
@LizardByte-bot approve
