### ISSUE TITLE
[MOVIE]: Dune: Part Two (2024)

### ISSUE THREAD

**Issue by Elshepl** [LizardByte/ThemerrDB#3887]
### Database URL

https://www.themoviedb.org/movie/693134-dune-part-two

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=iPypPemhFls

**Comment by jjnether** [comment]
@Elshepl A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
