### ISSUE TITLE
[TV SHOW]: Oshi No Ko (2023)

### ISSUE THREAD

**Issue by HametAk** [LizardByte/ThemerrDB#3890]
### Database URL

https://www.themoviedb.org/tv/203737

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=ZYlaUrj2Zkk

**Comment by jjnether** [comment]
@HametAk A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
