### ISSUE TITLE
[TV SHOW]: Demon Slayer: Kimetsu no Yaiba (2019)

### ISSUE THREAD

**Issue by Hadyark** [LizardByte/ThemerrDB#3894]
### Database URL

https://www.themoviedb.org/tv/85937

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=YkJvHe3KK2c

**Comment by jjnether** [comment]
@Hadyark A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
