### ISSUE TITLE
[TV SHOW]: Jujutsu Kaisen (2020)

### ISSUE THREAD

**Issue by Hadyark** [LizardByte/ThemerrDB#3898]
### Database URL

https://www.themoviedb.org/tv/95479

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=GwaRztMaoY0

**Comment by jjnether** [comment]
@Hadyark A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
