### ISSUE TITLE
[TV SHOW]: Attack on Titan (2013)

### ISSUE THREAD

**Issue by Hadyark** [LizardByte/ThemerrDB#3899]
### Database URL

https://www.themoviedb.org/tv/1429

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=8OkpRK2_gVs

**Comment by jjnether** [comment]
@Hadyark A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
