### ISSUE TITLE
[MOVIE COLLECTION]: Kingsman Collection

### ISSUE THREAD

**Issue by jj3005** [LizardByte/ThemerrDB#3904]
### Database URL

https://www.themoviedb.org/collection/391860

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=d_kbCecEaBw

**Comment by jjnether** [comment]
replacing with shorter version of the theme

**Comment by jjnether** [comment]
@LizardByte-bot edit https://www.youtube.com/watch?v=d_kbCecEaBw

**Comment by jjnether** [comment]
@LizardByte-bot approve
