### ISSUE TITLE
[MOVIE COLLECTION]: Ghostbusters Collection

### ISSUE THREAD

**Issue by jj3005** [LizardByte/ThemerrDB#3905]
### Database URL

https://www.themoviedb.org/collection/2980

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=TaV1r341wYk

**Comment by jjnether** [comment]
replacing with different epic version, the song you gave has intro sounds

**Comment by jjnether** [comment]
@LizardByte-bot edit https://www.youtube.com/watch?v=H4IF3xQO_uk

**Comment by jjnether** [comment]
actually just replacing with ghostbusters theme, should be a theme from the movies

**Comment by jjnether** [comment]
@LizardByte-bot edit https://www.youtube.com/watch?v=TaV1r341wYk

**Comment by jjnether** [comment]
@LizardByte-bot approve
