### ISSUE TITLE
[MOVIE COLLECTION]: Alice in Wonderland Collection

### ISSUE THREAD

**Issue by jj3005** [LizardByte/ThemerrDB#3907]
### Database URL

https://www.themoviedb.org/collection/261307

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=PCTzUDkkQDA

**Comment by jjnether** [comment]
@jj3005 A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
