### ISSUE TITLE
[MOVIE COLLECTION]: Addams Family Collection

### ISSUE THREAD

**Issue by jj3005** [LizardByte/ThemerrDB#3911]
### Database URL

https://www.themoviedb.org/collection/11716

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=X6QzbvH-ZNo

**Comment by jjnether** [comment]
replacing with live action version

**Comment by jjnether** [comment]
@LizardByte-bot edit https://www.youtube.com/watch?v=X6QzbvH-ZNo

**Comment by jjnether** [comment]
@LizardByte-bot approve
