### ISSUE TITLE
[MOVIE COLLECTION]: Enola Holmes Collection

### ISSUE THREAD

**Issue by jj3005** [LizardByte/ThemerrDB#3912]
### Database URL

https://www.themoviedb.org/collection/829314

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=_7j5BT1FCu8

**Comment by jjnether** [comment]
@jj3005 The song you gave is from a trailer, not the actual show. How about this instead?

https://www.youtube.com/watch?v=_7j5BT1FCu8

**Comment by jj3005** [comment]
Is also OK!👍

**Comment by jjnether** [comment]
@LizardByte-bot approve
