### ISSUE TITLE
[MOVIE]: 13 (2010)

### ISSUE THREAD

**Issue by CooperSkooper** [LizardByte/ThemerrDB#3925]
### Database URL

https://www.themoviedb.org/movie/44982

### YouTube Theme Song Video URL

https://youtu.be/wZ6kgqYORJE?si=CUKNgiDf7QHoUPzX

**Comment by CooperSkooper** [comment]
Kinda hard to find ngl, not relevant but the dates on this film's release date seems a little bungled between 2010 and 2011.

**Comment by jjnether** [comment]
@LizardByte-bot approve
