### ISSUE TITLE
[TV SHOW]: Boruto: Naruto Next Generations (2017)

### ISSUE THREAD

**Issue by Hadyark** [LizardByte/ThemerrDB#3926]
### Database URL

https://www.themoviedb.org/tv/70881

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=unR1h10HPsk&list=PL2R75x3ZazUCXlh2WxMHznlpRqU9nm4D8

**Comment by jjnether** [comment]
@LizardByte-bot approve
