### ISSUE TITLE
[TV SHOW]: My Hero Academia (2016)

### ISSUE THREAD

**Issue by Hadyark** [LizardByte/ThemerrDB#3929]
### Database URL

https://www.themoviedb.org/tv/65930

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=yu0HjPzFYnY

**Comment by Hadyark** [comment]
The link provided in the [MR ](https://github.com/LizardByte/ThemerrDB/issues/3841) does not work for me (Video not available + Comments disabled). I am from Belgium. The link I provide seems better, same theme from the same youtube channel but 55million views against 11million. 
![image](https://github.com/LizardByte/ThemerrDB/assets/32941087/72d3e921-fff7-4260-a598-712c62f0df37)

**Comment by Hadyark** [comment]
The link provided in the [MR ](https://github.com/LizardByte/ThemerrDB/issues/3841) does not work for me (Video not available + Comments disabled). I am from Belgium. The link I provide seems better, same theme from the same youtube channel but 55million views against 11million. 
![image](https://github.com/LizardByte/ThemerrDB/assets/32941087/1584339d-e983-4c1c-a5b0-ccd28efd5718)

**Comment by jjnether** [comment]
@LizardByte-bot approve
