### ISSUE TITLE
[MOVIE COLLECTION]: Asterix and Obelix (Animation) Collection

### ISSUE THREAD

**Issue by jj3005** [LizardByte/ThemerrDB#3934]
### Database URL

https://www.themoviedb.org/collection/94039

### YouTube Theme Song Video URL

https://youtu.be/_LTpPa2y_Bg?list=PLbDCXngxN3zu7E_ZFErtyJc8gDNXW0l9K

**Comment by jjnether** [comment]
@LizardByte-bot approve
