### ISSUE TITLE
[MOVIE COLLECTION]: It Collection

### ISSUE THREAD

**Issue by jj3005** [LizardByte/ThemerrDB#3936]
### Database URL

https://www.themoviedb.org/collection/477962

### YouTube Theme Song Video URL

https://youtu.be/y6lQMPE6MVE?si=W4lKlfLL3mViaQZM

**Comment by jjnether** [comment]
@jj3005 It's not really music, just frantic atmosphere. How about this instead?

https://youtu.be/y6lQMPE6MVE?si=W4lKlfLL3mViaQZM

**Comment by jj3005** [comment]
Is also OK.

**Comment by jjnether** [comment]
@LizardByte-bot edit https://youtu.be/y6lQMPE6MVE?si=W4lKlfLL3mViaQZM

**Comment by jj3005** [comment]
👍

**Comment by jjnether** [comment]
@LizardByte-bot approve
