### ISSUE TITLE
[MOVIE COLLECTION]: Jumanji Collection

### ISSUE THREAD

**Issue by jj3005** [LizardByte/ThemerrDB#3938]
### Database URL

https://www.themoviedb.org/collection/495527

### YouTube Theme Song Video URL

https://youtu.be/0oqd_66SOo8?si=F1_Aad93-T5Z-LLO

**Comment by jjnether** [comment]
@jj3005 It is silent for the first 20 seconds or so. How about this instead?

https://youtu.be/0oqd_66SOo8?si=F1_Aad93-T5Z-LLO

**Comment by jj3005** [comment]
Is also OK.

**Comment by jjnether** [comment]
@LizardByte-bot edit https://youtu.be/0oqd_66SOo8?si=F1_Aad93-T5Z-LLO

**Comment by jj3005** [comment]
👍

**Comment by jjnether** [comment]
@LizardByte-bot approve
