### ISSUE TITLE
[MOVIE]: Adam's Apples (2005)

### ISSUE THREAD

**Issue by Iceman808** [LizardByte/ThemerrDB#3955]
### Database URL

https://www.themoviedb.org/movie/1023

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=KOItqbWhWtU

**Comment by jjnether** [comment]
Changing to actual song

**Comment by jjnether** [comment]
@LizardByte-bot edit https://www.youtube.com/watch?v=KOItqbWhWtU

**Comment by jjnether** [comment]
@LizardByte-bot approve
