### ISSUE TITLE
[MOVIE]: Deep Blue Sea (1999)

### ISSUE THREAD

**Issue by Iceman808** [LizardByte/ThemerrDB#3959]
### Database URL

https://www.themoviedb.org/movie/8914

### YouTube Theme Song Video URL

https://youtu.be/5i4wMZnaG7w?si=phhv_KQu6FantrOp

**Comment by jjnether** [comment]
@LizardByte-bot edit https://youtu.be/5i4wMZnaG7w?si=phhv_KQu6FantrOp

**Comment by jjnether** [comment]
@LizardByte-bot approve
