### ISSUE TITLE
[MOVIE]: Parasite (2019)

### ISSUE THREAD

**Issue by Leonito2003** [LizardByte/ThemerrDB#3970]
### Database URL

https://www.themoviedb.org/movie/496243

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=cmuh1tJLChQ

**Comment by Leonito2003** [comment]
The current video is blocked basically everywhere but the US, this one nowhere.

**Comment by jjnether** [comment]
@LizardByte-bot approve
