### ISSUE TITLE
[MOVIE]: The Hunger Games: Catching Fire (2013)

### ISSUE THREAD

**Issue by Leonito2003** [LizardByte/ThemerrDB#3971]
### Database URL

https://www.themoviedb.org/movie/101299

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=m0df1WsEKwE

**Comment by Leonito2003** [comment]
The current video is blocked in parts of Europe and Africa, this one nowhere.

**Comment by jjnether** [comment]
@LizardByte-bot approve
