### ISSUE TITLE
[MOVIE]: The Hunger Games (2012)

### ISSUE THREAD

**Issue by Leonito2003** [LizardByte/ThemerrDB#3972]
### Database URL

https://www.themoviedb.org/movie/70160

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=2S30TlNpQvg

**Comment by Leonito2003** [comment]
The current video is blocked in France, this one nowhere.

**Comment by jjnether** [comment]
@LizardByte-bot approve
