### ISSUE TITLE
[TV SHOW]: K.C. Undercover (2015)

### ISSUE THREAD

**Issue by donghaerang** [LizardByte/ThemerrDB#3984]
### Database URL

https://www.themoviedb.org/tv/61915

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=DR5FhYgdJeQ

**Comment by jjnether** [comment]
replacing with better quality theme

**Comment by jjnether** [comment]
@LizardByte-bot edit https://www.youtube.com/watch?v=DR5FhYgdJeQ

**Comment by jjnether** [comment]
@LizardByte-bot approve
