### ISSUE TITLE
[MOVIE]: Future Boy Conan: The Big Giant Robot's Resurrection (1984)

### ISSUE THREAD

**Issue by donghaerang** [LizardByte/ThemerrDB#3989]
### Database URL

https://www.themoviedb.org/movie/674683

### YouTube Theme Song Video URL

https://youtu.be/2xDQNtRFVLs?si=ob2Or0griR3K9qN-

**Comment by jjnether** [comment]
replacing with actual theme

**Comment by jjnether** [comment]
@LizardByte-bot edit https://youtu.be/2xDQNtRFVLs?si=ob2Or0griR3K9qN-

**Comment by jjnether** [comment]
@LizardByte-bot approve
