### ISSUE TITLE
[MOVIE]: True Romance (1993)

### ISSUE THREAD

**Issue by ShaunC21** [LizardByte/ThemerrDB#4017]
### Database URL

https://www.themoviedb.org/movie/319-true-romance

### YouTube Theme Song Video URL

https://youtu.be/Mzzkz5-gbGo?list=PLqnnuEVGcRQzmWG8OI-7Zub62D4zs04IA

**Comment by ShaunC21** [comment]
thanks

**Comment by jjnether** [comment]
@LizardByte-bot approve
