### ISSUE TITLE
[MOVIE]: Natural Born Killers (1994)

### ISSUE THREAD

**Issue by ShaunC21** [LizardByte/ThemerrDB#4026]
### Database URL

https://www.themoviedb.org/movie/241-natural-born-killers

### YouTube Theme Song Video URL

https://youtu.be/skmSfXqPN3A?list=PLjDvaXwceFJRGGjzqlFILuOLmePDK8gjp

**Comment by jjnether** [comment]
@LizardByte-bot approve
