### ISSUE TITLE
[TV SHOW]: For All Mankind (2019)

### ISSUE THREAD

**Issue by Leonito2003** [LizardByte/ThemerrDB#4028]
### Database URL

https://www.themoviedb.org/tv/87917

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=LbVH6s6glgk

**Comment by bonswouar** [comment]
Not sure what's recommended for tv shows, but as an alternative to the main title theme I'd suggest for example: https://www.youtube.com/watch?v=LbVH6s6glgk

**Comment by Leonito2003** [comment]
why not, sounds good too

**Comment by jjnether** [comment]
@LizardByte-bot edit https://www.youtube.com/watch?v=LbVH6s6glgk

**Comment by jjnether** [comment]
@LizardByte-bot approve
