### ISSUE TITLE
[TV SHOW]: 3 Body Problem (2024)

### ISSUE THREAD

**Issue by Jchasa** [LizardByte/ThemerrDB#4034]
### Database URL

https://www.themoviedb.org/tv/108545

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=1D-hAbS1AbU

**Comment by Leonito2003** [comment]
This isn't the main theme though, this one is https://www.youtube.com/watch?v=3jpKd-4manQ

**Comment by jjnether** [comment]
We'll keep the main title for this one
