### ISSUE TITLE
[MOVIE]: 22 Jump Street (2014)

### ISSUE THREAD

**Issue by Iceman808** [LizardByte/ThemerrDB#4058]
### Database URL

https://www.themoviedb.org/movie/187017

### YouTube Theme Song Video URL

https://youtu.be/GWrzix_-SV4?si=3CLg218ZmF6tbTd7

**Comment by jjnether** [comment]
@Iceman808 Theme is a bit long, how about this instead?

https://youtu.be/GWrzix_-SV4?si=3CLg218ZmF6tbTd7

**Comment by jjnether** [comment]
@LizardByte-bot edit https://youtu.be/GWrzix_-SV4?si=3CLg218ZmF6tbTd7

**Comment by jjnether** [comment]
@LizardByte-bot approve
