### ISSUE TITLE
[MOVIE]: Lost Highway (1997)

### ISSUE THREAD

**Issue by harunator0** [LizardByte/ThemerrDB#4071]
### Database URL

https://www.themoviedb.org/movie/638-lost-highway?language=de

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=IzIXlttNCyo

**Comment by harunator0** [comment]
Requested update because this has better audio quality than the last submitted track.

**Comment by jjnether** [comment]
@LizardByte-bot approve
