### ISSUE TITLE
[MOVIE]: Tomorrow Never Dies (1997)

### ISSUE THREAD

**Issue by tylerbickel** [LizardByte/ThemerrDB#408]
### TheMovieDB URL

https://www.themoviedb.org/movie/714

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=rwDUWnOVf0c

**Comment by ReenigneArcher** [comment]
What do you think of using the official song? https://www.youtube.com/watch?v=rwDUWnOVf0c

**Comment by tylerbickel** [comment]
Yea I chose the wrong track here. Let’s go with your suggestion.
________________________________
