### ISSUE TITLE
[TV SHOW]: Code Geass: Lelouch of the Rebellion (2006)

### ISSUE THREAD

**Issue by EasyArt** [LizardByte/ThemerrDB#4087]
### Database URL

https://www.themoviedb.org/tv/31724

### YouTube Theme Song Video URL

https://youtu.be/G8CFuZ9MseQ

**Comment by jjnether** [comment]
@EasyArt A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
