### ISSUE TITLE
[TV SHOW]: American Horror Story (2011)

### ISSUE THREAD

**Issue by bonswouar** [LizardByte/ThemerrDB#4097]
### Database URL

https://www.themoviedb.org/tv/1413

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=1qXiKIM0TKA

**Comment by bonswouar** [comment]
A shorter one maybe: https://youtu.be/JvUofsgMVsU

**Comment by jjnether** [comment]
@LizardByte-bot approve
