### ISSUE TITLE
[MOVIE]: Godzilla x Kong: The New Empire (2024)

### ISSUE THREAD

**Issue by jj3005** [LizardByte/ThemerrDB#4103]
### Database URL

https://www.themoviedb.org/movie/823464

### YouTube Theme Song Video URL

https://youtu.be/uh5v3bUAWIc?list=PLim3m5NnkYFf1-5UGYG2x5rMfyQD26rVf

**Comment by jjnether** [comment]
@LizardByte-bot approve
