### ISSUE TITLE
[TV SHOW]: Gaim Gaiden: Kamen Rider Gridon VS Kamen Rider Bravo (2020)

### ISSUE THREAD

**Issue by fowlplay27** [LizardByte/ThemerrDB#4125]
### Database URL

https://www.themoviedb.org/tv/132582

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=uFfDiFiu0Yg

**Comment by ZhongQiyu** [comment]
这个是要做多模态挖掘吗

**Comment by jjnether** [comment]
@LizardByte-bot approve
