### ISSUE TITLE
[TV SHOW]: WIND BREAKER (2024)

### ISSUE THREAD

**Issue by joao17017** [LizardByte/ThemerrDB#4140]
### Database URL

https://www.themoviedb.org/tv/223500

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=IuSAC8ZDf1A&ab_channel=%E3%82%A2%E3%83%8B%E3%83%97%E3%83%AC%E3%83%83%E3%82%AF%E3%82%B9%E3%83%81%E3%83%A3%E3%83%B3%E3%83%8D%E3%83%AB

**Comment by jjnether** [comment]
@LizardByte-bot approve
