### ISSUE TITLE
[TV SHOW]: X-Men '97 (2024)

### ISSUE THREAD

**Issue by joao17017** [LizardByte/ThemerrDB#4141]
### Database URL

https://www.themoviedb.org/tv/138502

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=EkIlM0lYtT0&ab_channel=MarvelMusicVEVO

**Comment by jjnether** [comment]
A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
