### ISSUE TITLE
[TV SHOW]: Fear the Walking Dead (2015)

### ISSUE THREAD

**Issue by GabrielPearce** [LizardByte/ThemerrDB#4158]
### Database URL

https://www.themoviedb.org/tv/62286

### YouTube Theme Song Video URL

https://youtu.be/MVJKNXcR8GE?si=By_h8bjlDAYxsVsK

**Comment by jjnether** [comment]
@GabrielPearce Theme is too short, how about this instead?

https://youtu.be/MVJKNXcR8GE?si=By_h8bjlDAYxsVsK

**Comment by jjnether** [comment]
@LizardByte-bot edit https://youtu.be/MVJKNXcR8GE?si=By_h8bjlDAYxsVsK

**Comment by jjnether** [comment]
@LizardByte-bot approve
