### ISSUE TITLE
[TV SHOW]: I Got a Cheat Skill in Another World and Became Unrivaled in the Real World, Too (2023)

### ISSUE THREAD

**Issue by Hadyark** [LizardByte/ThemerrDB#4163]
### Database URL

https://www.themoviedb.org/tv/208493

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=UrOakf2Z08g

**Comment by jjnether** [comment]
A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
