### ISSUE TITLE
[TV SHOW]: The Big Bang Theory (2007)

### ISSUE THREAD

**Issue by Mike-Blade037** [LizardByte/ThemerrDB#4167]
### Database URL

https://www.themoviedb.org/tv/1418-the-big-bang-theory

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=20i5eqwK178

**Comment by jjnether** [comment]
A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
