### ISSUE TITLE
[TV SHOW]: The Mandalorian (2019)

### ISSUE THREAD

**Issue by Mike-Blade037** [LizardByte/ThemerrDB#4169]
### Database URL

https://www.themoviedb.org/tv/82856-the-mandalorian

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=2YDKxcdIXBs

**Comment by jjnether** [comment]
A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
