### ISSUE TITLE
[TV SHOW]: Marvel's The Defenders (2017)

### ISSUE THREAD

**Issue by Mike-Blade037** [LizardByte/ThemerrDB#4171]
### Database URL

https://www.themoviedb.org/tv/62285-marvel-s-the-defenders

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=7tNaH_WW4YI

**Comment by ReenigneArcher** [comment]
Stop... We don't accept imdb urls.

**Comment by jjnether** [comment]
@LizardByte-bot approve
