### ISSUE TITLE
[TV SHOW]: Rubble & Crew (2023)

### ISSUE THREAD

**Issue by Mike-Blade037** [LizardByte/ThemerrDB#4174]
### Database URL

https://www.themoviedb.org/tv/214875-rubble-crew

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=KWXXC228g24

**Comment by ReenigneArcher** [comment]
@Mike-Blade037 last warning. You must use themoviedb urls, not imdb.

**Comment by jjnether** [comment]
@LizardByte-bot approve
