### ISSUE TITLE
[TV SHOW]: Squid Game (2021)

### ISSUE THREAD

**Issue by Mike-Blade037** [LizardByte/ThemerrDB#4175]
### Database URL

https://www.themoviedb.org/tv/93405

### YouTube Theme Song Video URL

https://youtu.be/BqwN8cOAAWQ?si=WRnY-BF7UlFbURBv

**Comment by jjnether** [comment]
@Mike-Blade037 I know this is a theme from the show, but is initially quite hard to listen to in my opinion, what do you think about this instead?

https://youtu.be/BqwN8cOAAWQ?si=WRnY-BF7UlFbURBv

**Comment by jjnether** [comment]
@LizardByte-bot edit https://youtu.be/BqwN8cOAAWQ?si=WRnY-BF7UlFbURBv

**Comment by jjnether** [comment]
@LizardByte-bot approve
