### ISSUE TITLE
[MOVIE]: The Fast and the Furious (2001)

### ISSUE THREAD

**Issue by Mike-Blade037** [LizardByte/ThemerrDB#4189]
### Database URL

https://www.themoviedb.org/movie/9799-the-fast-and-the-furious

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=DB5lfqfRyGE

**Comment by jjnether** [comment]
A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
