### ISSUE TITLE
[MOVIE]: Fast & Furious 6 (2013)

### ISSUE THREAD

**Issue by Mike-Blade037** [LizardByte/ThemerrDB#4194]
### Database URL

https://www.themoviedb.org/movie/82992-fast-furious-6

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=c3R3VRPOpao

**Comment by jjnether** [comment]
A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
