### ISSUE TITLE
[TV SHOW]: For All Mankind (2019)

### ISSUE THREAD

**Issue by Mike-Blade037** [LizardByte/ThemerrDB#4202]
### Database URL

https://www.themoviedb.org/tv/87917-for-all-mankind

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=TV-8rDmAhYY

**Comment by jjnether** [comment]
A theme for this already exists or was submitted before yours. When replacing a theme, please mark that you're replacing a theme and the reason for it in the submission.
