### ISSUE TITLE
[MOVIE COLLECTION]: Harry Potter Collection

### ISSUE THREAD

**Issue by Mike-Blade037** [LizardByte/ThemerrDB#4204]
### Database URL

https://www.themoviedb.org/collection/1241-harry-potter-collection

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=WUiI5aQcTow

**Comment by jjnether** [comment]
A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
