### ISSUE TITLE
[MOVIE]: Harry Potter and the Philosopher's Stone (2001)

### ISSUE THREAD

**Issue by Mike-Blade037** [LizardByte/ThemerrDB#4205]
### Database URL

https://www.themoviedb.org/movie/671-harry-potter-and-the-philosopher-s-stone

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=loD2tTA2u-M

**Comment by jjnether** [comment]
A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
