### ISSUE TITLE
[MOVIE]: Harry Potter and the Chamber of Secrets (2002)

### ISSUE THREAD

**Issue by Mike-Blade037** [LizardByte/ThemerrDB#4206]
### Database URL

https://www.themoviedb.org/movie/672-harry-potter-and-the-chamber-of-secrets

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=r9wEODhKzOw

**Comment by jjnether** [comment]
A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
