### ISSUE TITLE
[MOVIE]: Harry Potter and the Prisoner of Azkaban (2004)

### ISSUE THREAD

**Issue by Mike-Blade037** [LizardByte/ThemerrDB#4207]
### Database URL

https://www.themoviedb.org/movie/673-harry-potter-and-the-prisoner-of-azkaban

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=MdJC0wbiyUY

**Comment by jjnether** [comment]
A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
