### ISSUE TITLE
[MOVIE]: Harry Potter and the Goblet of Fire (2005)

### ISSUE THREAD

**Issue by Mike-Blade037** [LizardByte/ThemerrDB#4208]
### Database URL

https://www.themoviedb.org/movie/674-harry-potter-and-the-goblet-of-fire

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=VQrISvu-Gfo

**Comment by jjnether** [comment]
A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
