### ISSUE TITLE
[MOVIE]: Harry Potter and the Order of the Phoenix (2007)

### ISSUE THREAD

**Issue by Mike-Blade037** [LizardByte/ThemerrDB#4209]
### Database URL

https://www.themoviedb.org/movie/675-harry-potter-and-the-order-of-the-phoenix

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=M4mURo3icTU

**Comment by jjnether** [comment]
A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
