### ISSUE TITLE
[MOVIE]: Harry Potter and the Half-Blood Prince (2009)

### ISSUE THREAD

**Issue by Mike-Blade037** [LizardByte/ThemerrDB#4210]
### Database URL

https://www.themoviedb.org/movie/767-harry-potter-and-the-half-blood-prince

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=mSfuaHWlGsw

**Comment by jjnether** [comment]
A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
