### ISSUE TITLE
[MOVIE]: Harry Potter and the Deathly Hallows: Part 1 (2010)

### ISSUE THREAD

**Issue by Mike-Blade037** [LizardByte/ThemerrDB#4211]
### Database URL

https://www.themoviedb.org/movie/12444-harry-potter-and-the-deathly-hallows-part-1

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=485nkxcYZEo

**Comment by jjnether** [comment]
A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
