### ISSUE TITLE
[MOVIE]: Harry Potter and the Deathly Hallows: Part 2 (2011)

### ISSUE THREAD

**Issue by Mike-Blade037** [LizardByte/ThemerrDB#4212]
### Database URL

https://www.themoviedb.org/movie/12445-harry-potter-and-the-deathly-hallows-part-2

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=OyOU9txmf9c

**Comment by jjnether** [comment]
A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
