### ISSUE TITLE
[MOVIE COLLECTION]: Pirates of the Caribbean Collection

### ISSUE THREAD

**Issue by Mike-Blade037** [LizardByte/ThemerrDB#4214]
### Database URL

https://www.themoviedb.org/collection/295-pirates-of-the-caribbean-collection

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=jfvFWTujDtY

**Comment by jjnether** [comment]
A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
