### ISSUE TITLE
[MOVIE]: Pirates of the Caribbean: The Curse of the Black Pearl (2003)

### ISSUE THREAD

**Issue by Mike-Blade037** [LizardByte/ThemerrDB#4215]
### Database URL

https://www.themoviedb.org/movie/22-pirates-of-the-caribbean-the-curse-of-the-black-pearl

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=20f3ThOiz7s

**Comment by jjnether** [comment]
A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
