### ISSUE TITLE
[MOVIE]: Pirates of the Caribbean: Dead Man's Chest (2006)

### ISSUE THREAD

**Issue by Mike-Blade037** [LizardByte/ThemerrDB#4216]
### Database URL

https://www.themoviedb.org/movie/58-pirates-of-the-caribbean-dead-man-s-chest

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=Tjp8cj8Vzyo

**Comment by jjnether** [comment]
A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
