### ISSUE TITLE
[MOVIE]: Pirates of the Caribbean: On Stranger Tides (2011)

### ISSUE THREAD

**Issue by Mike-Blade037** [LizardByte/ThemerrDB#4218]
### Database URL

https://www.themoviedb.org/movie/1865-pirates-of-the-caribbean-on-stranger-tides

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=_5MQabnB5No

**Comment by jjnether** [comment]
A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
