### ISSUE TITLE
[MOVIE]: Pirates of the Caribbean: Dead Men Tell No Tales (2017)

### ISSUE THREAD

**Issue by Mike-Blade037** [LizardByte/ThemerrDB#4219]
### Database URL

https://www.themoviedb.org/movie/166426-pirates-of-the-caribbean-dead-men-tell-no-tales

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=DRgUdLGzT_g

**Comment by jjnether** [comment]
A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
