### ISSUE TITLE
[MOVIE COLLECTION]: The Lord of the Rings Collection

### ISSUE THREAD

**Issue by Mike-Blade037** [LizardByte/ThemerrDB#4221]
### Database URL

https://www.themoviedb.org/collection/119-the-lord-of-the-rings-collection

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=ehAgMszCHU4

**Comment by jjnether** [comment]
A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
