### ISSUE TITLE
[MOVIE]: The Lord of the Rings: The Fellowship of the Ring (2001)

### ISSUE THREAD

**Issue by Mike-Blade037** [LizardByte/ThemerrDB#4222]
### Database URL

https://www.themoviedb.org/movie/120-the-lord-of-the-rings-the-fellowship-of-the-ring

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=tVV7ijh01jo&list=PL480A36B593520453&index=2

**Comment by jjnether** [comment]
A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
