### ISSUE TITLE
[MOVIE]: The Lord of the Rings: The Two Towers (2002)

### ISSUE THREAD

**Issue by Mike-Blade037** [LizardByte/ThemerrDB#4223]
### Database URL

https://www.themoviedb.org/movie/121-the-lord-of-the-rings-the-two-towers

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=zi8CUdK3HY0&list=PL480A36B593520453&index=20

**Comment by jjnether** [comment]
A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
