### ISSUE TITLE
[MOVIE]: The Lord of the Rings: The Return of the King (2003)

### ISSUE THREAD

**Issue by Mike-Blade037** [LizardByte/ThemerrDB#4224]
### Database URL

https://www.themoviedb.org/movie/122-the-lord-of-the-rings-the-return-of-the-king

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=k6aLLo-Vr70&list=PL480A36B593520453&index=39

**Comment by jjnether** [comment]
A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
