### ISSUE TITLE
[MOVIE COLLECTION]: The Hobbit Collection

### ISSUE THREAD

**Issue by Mike-Blade037** [LizardByte/ThemerrDB#4225]
### Database URL

https://www.themoviedb.org/collection/121938-the-hobbit-collection

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=Z7aWG57MM7c

**Comment by jjnether** [comment]
A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
