### ISSUE TITLE
[MOVIE]: The Hobbit: An Unexpected Journey (2012)

### ISSUE THREAD

**Issue by Mike-Blade037** [LizardByte/ThemerrDB#4226]
### Database URL

https://www.themoviedb.org/movie/49051-the-hobbit-an-unexpected-journey

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=2_M0kiKNozE

**Comment by jjnether** [comment]
A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
