### ISSUE TITLE
[MOVIE]: The Hobbit: The Desolation of Smaug (2013)

### ISSUE THREAD

**Issue by Mike-Blade037** [LizardByte/ThemerrDB#4227]
### Database URL

https://www.themoviedb.org/movie/57158-the-hobbit-the-desolation-of-smaug

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=DzD12qo1knM

**Comment by jjnether** [comment]
A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
