### ISSUE TITLE
[MOVIE]: The Hobbit: The Battle of the Five Armies (2014)

### ISSUE THREAD

**Issue by Mike-Blade037** [LizardByte/ThemerrDB#4228]
### Database URL

https://www.themoviedb.org/movie/122917-the-hobbit-the-battle-of-the-five-armies

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=7fKvLoj3nD0

**Comment by jjnether** [comment]
A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
