### ISSUE TITLE
[MOVIE COLLECTION]: Maleficent Collection

### ISSUE THREAD

**Issue by Mike-Blade037** [LizardByte/ThemerrDB#4229]
### Database URL

https://www.themoviedb.org/collection/531331-maleficent-collection

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=26kV4UcZ1mU

**Comment by jjnether** [comment]
A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
