### ISSUE TITLE
[MOVIE]: Maleficent (2014)

### ISSUE THREAD

**Issue by Mike-Blade037** [LizardByte/ThemerrDB#4230]
### Database URL

https://www.themoviedb.org/movie/102651-maleficent

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=2TCEtsiugXw&list=PLQvL6GLJiX93q_l0JsFN5nNylCt3Eof6q&index=23

**Comment by jjnether** [comment]
A theme for this already exists or was submitted before yours. When replacing a theme, please mark that you're replacing a theme and the reason for it in the submission.
