### ISSUE TITLE
[MOVIE]: The Huntsman: Winter's War (2016)

### ISSUE THREAD

**Issue by Mike-Blade037** [LizardByte/ThemerrDB#4234]
### Database URL

https://www.themoviedb.org/movie/290595-the-huntsman-winter-s-war

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=UkmxaDQCvhI&list=PLQvL6GLJiX92gONR_mL86zTsVvs7WRPXd

**Comment by jjnether** [comment]
@LizardByte-bot approve
