### ISSUE TITLE
[MOVIE]: Fantastic Beasts and Where to Find Them (2016)

### ISSUE THREAD

**Issue by Mike-Blade037** [LizardByte/ThemerrDB#4240]
### Database URL

https://www.themoviedb.org/movie/259316-fantastic-beasts-and-where-to-find-them

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=WBOMpfxsUpk&list=PLBKadB95sF46S0OjNmQr0GeXMXZ-Byso3

**Comment by jjnether** [comment]
A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
