### ISSUE TITLE
[MOVIE]: Fantastic Beasts: The Crimes of Grindelwald (2018)

### ISSUE THREAD

**Issue by Mike-Blade037** [LizardByte/ThemerrDB#4241]
### Database URL

https://www.themoviedb.org/movie/338952-fantastic-beasts-the-crimes-of-grindelwald

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=KtE-nxgQOZM&list=PLBKadB95sF44VTP9GcFOP_CjtkD9U_2pv&index=1

**Comment by jjnether** [comment]
A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
