### ISSUE TITLE
[MOVIE]: Where the Crawdads Sing (2022)

### ISSUE THREAD

**Issue by jj3005** [LizardByte/ThemerrDB#4249]
### Database URL

https://www.themoviedb.org/movie/682507

### YouTube Theme Song Video URL

https://youtu.be/EvnzfDW8-lY?feature=shared

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
