### ISSUE TITLE
[MOVIE]: Space Pirate Captain Harlock (2013)

### ISSUE THREAD

**Issue by toeiazarothis** [LizardByte/ThemerrDB#4253]
### Database URL

https://www.themoviedb.org/movie/192577

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=__-tmU_k1jw

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
