### ISSUE TITLE
[MOVIE]: The Admiral: Roaring Currents (2014)

### ISSUE THREAD

**Issue by OcifferAction** [LizardByte/ThemerrDB#4259]
### Database URL

https://www.themoviedb.org/movie/282631

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=HMC-yqpXtpM

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
