### ISSUE TITLE
[MOVIE]: The Angriest Man in Brooklyn (2014)

### ISSUE THREAD

**Issue by OcifferAction** [LizardByte/ThemerrDB#4267]
### Database URL

https://www.themoviedb.org/movie/152790

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=g8hscQX2oiY

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
