### ISSUE TITLE
[MOVIE]: A Bag of Marbles (2017)

### ISSUE THREAD

**Issue by OcifferAction** [LizardByte/ThemerrDB#4277]
### Database URL

https://www.themoviedb.org/movie/398924

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=xyCNQk9e42w

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
