### ISSUE TITLE
[MOVIE]: The Birth of a Nation (2016)

### ISSUE THREAD

**Issue by OcifferAction** [LizardByte/ThemerrDB#4286]
### Database URL

https://www.themoviedb.org/movie/339408

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=FzqK1Bb0388

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
