### ISSUE TITLE
[TV SHOW]: The Irregular at Magic High School (2014)

### ISSUE THREAD

**Issue by DoctorGC** [LizardByte/ThemerrDB#4293]
### Database URL

https://www.themoviedb.org/tv/60833

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=GFW7P55j0-g

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
