### ISSUE TITLE
[TV SHOW]: Sailor Moon Crystal (2014)

### ISSUE THREAD

**Issue by DoctorGC** [LizardByte/ThemerrDB#4297]
### Database URL

https://www.themoviedb.org/tv/61339

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=c0Va228UhRs

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
