### ISSUE TITLE
[TV SHOW]: Chivalry of a Failed Knight (2015)

### ISSUE THREAD

**Issue by DoctorGC** [LizardByte/ThemerrDB#4298]
### Database URL

https://www.themoviedb.org/tv/67154

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=7_1IdKbYidA

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
