### ISSUE TITLE
[MOVIE]: 10 Things I Hate About You (1999)

### ISSUE THREAD

**Issue by peacemans** [LizardByte/ThemerrDB#4306]
### Database URL

https://www.themoviedb.org/movie/4951

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=-SpB6F6JgQQ&list=PL4LQdjpPDToMOHhFBE0dRuz157pmoBczA&index=2

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
