### ISSUE TITLE
[MOVIE]: Taken 3 (2014)

### ISSUE THREAD

**Issue by peacemans** [LizardByte/ThemerrDB#4307]
### Database URL

https://www.themoviedb.org/movie/260346

### YouTube Theme Song Video URL

https://youtu.be/dYwWrgjEULM?si=DkWMmcLxGWWd0PPt

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@peacemans Not really much audio for the beginning, and not really much of a theme. How about this instead?

https://youtu.be/dYwWrgjEULM?si=DkWMmcLxGWWd0PPt

**Comment by jjnether** [comment]
@LizardByte-bot edit https://youtu.be/dYwWrgjEULM?si=DkWMmcLxGWWd0PPt
