### ISSUE TITLE
[MOVIE]: The Spectacular Now (2013)

### ISSUE THREAD

**Issue by CityKingsClub** [LizardByte/ThemerrDB#4309]
### Database URL

https://www.themoviedb.org/movie/157386

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=Ndgf3OKz2MQ

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
