### ISSUE TITLE
[MOVIE]: Godzilla Minus One (2023)

### ISSUE THREAD

**Issue by CityKingsClub** [LizardByte/ThemerrDB#4310]
### Database URL

https://www.themoviedb.org/movie/940721

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=qkIJidLfHjk

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
A theme for this already exists or was submitted before yours. When replacing a theme, please mark that you're replacing a theme and the reason for it in the submission.
