### ISSUE TITLE
[MOVIE]: Boo! A Madea Halloween (2016)

### ISSUE THREAD

**Issue by OcifferAction** [LizardByte/ThemerrDB#4313]
### Database URL

https://www.themoviedb.org/movie/380124

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=bzYXCxzU9Io

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
