### ISSUE TITLE
[MOVIE]: Boo 2! A Madea Halloween (2017)

### ISSUE THREAD

**Issue by OcifferAction** [LizardByte/ThemerrDB#4314]
### Database URL

https://www.themoviedb.org/movie/459202

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=D5aGpKwZaIU

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
