### ISSUE TITLE
[MOVIE]: A Bridge Too Far (1977)

### ISSUE THREAD

**Issue by OcifferAction** [LizardByte/ThemerrDB#4315]
### Database URL

https://www.themoviedb.org/movie/5902

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=y9QPM0rwGI8

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
