### ISSUE TITLE
[MOVIE]: Call Me by Your Name (2017)

### ISSUE THREAD

**Issue by OcifferAction** [LizardByte/ThemerrDB#4319]
### Database URL

https://www.themoviedb.org/movie/398818

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=6zN98dHSFgQ

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
