### ISSUE TITLE
[MOVIE]: The Catcher Was a Spy (2018)

### ISSUE THREAD

**Issue by OcifferAction** [LizardByte/ThemerrDB#4326]
### Database URL

https://www.themoviedb.org/movie/467952

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=1ddPOiRH1v4

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
