### ISSUE TITLE
[MOVIE]: Cherry (2021)

### ISSUE THREAD

**Issue by OcifferAction** [LizardByte/ThemerrDB#4336]
### Database URL

https://www.themoviedb.org/movie/544401

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=5FZ5sXwVHt0

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve

**Comment by jjnether** [comment]
@OcifferAction You're a regular contributor and seem to have a good idea in our guidelines for proper themes. Would you be interested in becoming an approver for the project?
