### ISSUE TITLE
[MOVIE]: Back to Black (2024)

### ISSUE THREAD

**Issue by MadaxDeLuXe** [LizardByte/ThemerrDB#4339]
### Database URL

https://www.themoviedb.org/movie/998846

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=VpvSJ7H-nSI

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
