### ISSUE TITLE
[TV SHOW]: Law & Order Toronto: Criminal Intent (2024)

### ISSUE THREAD

**Issue by KevinHneen** [LizardByte/ThemerrDB#4343]
### Database URL

https://www.themoviedb.org/tv/228026

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=JFa323OsuOk

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@KevinHneen video is unavailable in the US. Please replace with a working video link that doesn't have such georestrictions

**Comment by KevinHneen** [comment]
@jjnether apologies, the video was available in my country and I was not aware. 
Heres the same video from alternative source 
https://www.youtube.com/watch?v=3fZsFfl5UKo

Heres a similar video with the an introductory guy talking
https://www.youtube.com/watch?v=c9MV35_zQN0 

Idk if these will be blocked but these are the only other sources unless you would like me to send the audio file from the original.

**Comment by jjnether** [comment]
@KevinHneen Unfortunately neither of those links work, and the theme needs to be a youtube link. You can check georestriction of a video using this website:

https://watannetwork.com/tools/blocked/

**Comment by KevinHneen** [comment]
@jjnether Thanks for tool, this one seems to be working in US acorrding to that site 
https://www.youtube.com/watch?v=JFa323OsuOk

**Comment by jjnether** [comment]
@LizardByte-bot edit https://www.youtube.com/watch?v=JFa323OsuOk

**Comment by jjnether** [comment]
@LizardByte-bot approve
