### ISSUE TITLE
[MOVIE]: Dirty Grandpa (2016)

### ISSUE THREAD

**Issue by OcifferAction** [LizardByte/ThemerrDB#4372]
### Database URL

https://www.themoviedb.org/movie/291870

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=aXYdDzvZgwo

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@OcifferAction You're a regular contributor and seem to have a good idea in our guidelines for proper themes. Would you be interested in becoming an approver for the project?

**Comment by OcifferAction** [comment]
I would be happy to help out.

**Comment by jjnether** [comment]
@OcifferAction Please join the Lizardbyte discord and we can discuss further there (https://discord.com/invite/lizardbyte-804382334370578482)

**Comment by jjnether** [comment]
@OcifferAction After you join, ping me in one of the main channels

**Comment by jjnether** [comment]
@LizardByte-bot approve
