### ISSUE TITLE
[TV SHOW]: The Acolyte (2024)

### ISSUE THREAD

**Issue by i-am-the-real-guru** [LizardByte/ThemerrDB#4374]
### Database URL

https://www.themoviedb.org/tv/114479

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=i97aKk1H6lo

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@i-am-the-real-guru The theme you gave is from the trailer, not that actual show. How about this instead?

https://youtu.be/2LHDRL7l88g?si=mVygbSG3aBc6TT03

**Comment by i-am-the-real-guru** [comment]
> @i-am-the-real-guru The theme you gave is from the trailer, not that actual show. How about this instead?
> 
> https://youtu.be/2LHDRL7l88g?si=mVygbSG3aBc6TT03


I agree, but I believe the trailer version is the more appropriate choice. The link you provided is 'End Credits', which is not the correct one.

**Comment by jjnether** [comment]
@LizardByte-bot approve
