### ISSUE TITLE
[MOVIE]: Furiosa: A Mad Max Saga (2024)

### ISSUE THREAD

**Issue by tylerreed19** [LizardByte/ThemerrDB#4456]
### Database URL

https://www.themoviedb.org/movie/786892

### YouTube Theme Song Video URL

https://youtu.be/wvVBTMeBD-M?si=bBGoBiAhc1irOSol

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
