### ISSUE TITLE
[MOVIE]: Kingdom of the Planet of the Apes (2024)

### ISSUE THREAD

**Issue by tylerreed19** [LizardByte/ThemerrDB#4457]
### Database URL

https://www.themoviedb.org/movie/653346

### YouTube Theme Song Video URL

https://youtu.be/4sajgI7C-vA?si=qxtnPdrApRUOIOZO

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
