### ISSUE TITLE
[MOVIE]: Rebel Moon - Part Two: The Scargiver (2024)

### ISSUE THREAD

**Issue by tylerreed19** [LizardByte/ThemerrDB#4459]
### Database URL

https://www.themoviedb.org/movie/934632

### YouTube Theme Song Video URL

https://youtu.be/vwzej3RDrdA?si=73QjwFBDWAarbwyW

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
