### ISSUE TITLE
[TV SHOW]: Akashic Records of Bastard Magic Instructor (2017)

### ISSUE THREAD

**Issue by DoctorGC** [LizardByte/ThemerrDB#4463]
### Database URL

https://www.themoviedb.org/tv/70637

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=URRcX_RCjTo

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
