### ISSUE TITLE
[TV SHOW]: Blue Exorcist (2011)

### ISSUE THREAD

**Issue by DoctorGC** [LizardByte/ThemerrDB#4464]
### Database URL

https://www.themoviedb.org/tv/38464

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=nKTLOdjWBCM

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
