### ISSUE TITLE
[TV SHOW]: BUILD-DIVIDE (2021)

### ISSUE THREAD

**Issue by DoctorGC** [LizardByte/ThemerrDB#4465]
### Database URL

https://www.themoviedb.org/tv/123670

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=6db5DVjwHls

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
