### ISSUE TITLE
[TV SHOW]: Dead Mount Death Play (2023)

### ISSUE THREAD

**Issue by DoctorGC** [LizardByte/ThemerrDB#4466]
### Database URL

https://www.themoviedb.org/tv/214540

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=QGmvHbxsxME

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
