### ISSUE TITLE
[TV SHOW]: Digimon Frontier (2002)

### ISSUE THREAD

**Issue by DoctorGC** [LizardByte/ThemerrDB#4467]
### Database URL

https://www.themoviedb.org/tv/8991

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=ehoaPNSIC0U

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
