### ISSUE TITLE
[TV SHOW]: Dragon Ball GT (1996)

### ISSUE THREAD

**Issue by DoctorGC** [LizardByte/ThemerrDB#4468]
### Database URL

https://www.themoviedb.org/tv/12697

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=tndKYpPz2RU

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
