### ISSUE TITLE
[TV SHOW]: Fate/Extra Last Encore (2018)

### ISSUE THREAD

**Issue by DoctorGC** [LizardByte/ThemerrDB#4470]
### Database URL

https://www.themoviedb.org/tv/76123

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=uuZKRK3IYFo

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
