### ISSUE TITLE
[TV SHOW]: Fate/Zero (2011)

### ISSUE THREAD

**Issue by DoctorGC** [LizardByte/ThemerrDB#4471]
### Database URL

https://www.themoviedb.org/tv/45845

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=gCnCFtbY0ZI

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
