### ISSUE TITLE
[TV SHOW]: Fuuto PI (2022)

### ISSUE THREAD

**Issue by DoctorGC** [LizardByte/ThemerrDB#4472]
### Database URL

https://www.themoviedb.org/tv/122369

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=wwf_pTbSnf4

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
