### ISSUE TITLE
[TV SHOW]: Girlfriend, Girlfriend (2021)

### ISSUE THREAD

**Issue by DoctorGC** [LizardByte/ThemerrDB#4474]
### Database URL

https://www.themoviedb.org/tv/113137

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=aLtT1rJ6O9M

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
