### ISSUE TITLE
[TV SHOW]: ID: INVADED (2020)

### ISSUE THREAD

**Issue by DoctorGC** [LizardByte/ThemerrDB#4476]
### Database URL

https://www.themoviedb.org/tv/92602

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=sfpCjy7Q8_M

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
