### ISSUE TITLE
[TV SHOW]: Inazuma Eleven (2008)

### ISSUE THREAD

**Issue by DoctorGC** [LizardByte/ThemerrDB#4477]
### Database URL

https://www.themoviedb.org/tv/42912

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=FHSHKe9cK6Q

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
