### ISSUE TITLE
[TV SHOW]: The Asterisk War (2015)

### ISSUE THREAD

**Issue by DoctorGC** [LizardByte/ThemerrDB#4478]
### Database URL

https://www.themoviedb.org/tv/64671

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=m1yMzjMwlOk

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
