### ISSUE TITLE
[TV SHOW]: The Misfit of Demon King Academy (2020)

### ISSUE THREAD

**Issue by DoctorGC** [LizardByte/ThemerrDB#4479]
### Database URL

https://www.themoviedb.org/tv/97617

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=hiopy_jxPIU

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
