### ISSUE TITLE
[TV SHOW]: The Testament of Sister New Devil (2015)

### ISSUE THREAD

**Issue by DoctorGC** [LizardByte/ThemerrDB#4480]
### Database URL

https://www.themoviedb.org/tv/64163

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=3pOM-3vslLg

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
