### ISSUE TITLE
[TV SHOW]: Yu Yu Hakusho (1992)

### ISSUE THREAD

**Issue by DoctorGC** [LizardByte/ThemerrDB#4481]
### Database URL

https://www.themoviedb.org/tv/30669

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=MZliGG7Outg

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
