### ISSUE TITLE
[TV SHOW]: Yu-Gi-Oh! 5D's (2008)

### ISSUE THREAD

**Issue by DoctorGC** [LizardByte/ThemerrDB#4482]
### Database URL

https://www.themoviedb.org/tv/20695

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=idhjkQ4TwBM

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
