### ISSUE TITLE
[TV SHOW]: Yu-Gi-Oh! GX (2004)

### ISSUE THREAD

**Issue by DoctorGC** [LizardByte/ThemerrDB#4483]
### Database URL

https://www.themoviedb.org/tv/12536

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=aSnMNV2d-ms

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
