### ISSUE TITLE
[TV SHOW]: Yu-Gi-Oh! VRAINS (2017)

### ISSUE THREAD

**Issue by DoctorGC** [LizardByte/ThemerrDB#4484]
### Database URL

https://www.themoviedb.org/tv/71360

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=AtpBMQJjYwY

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
