### ISSUE TITLE
[TV SHOW]: Digimon Tamers (2001)

### ISSUE THREAD

**Issue by DoctorGC** [LizardByte/ThemerrDB#4485]
### Database URL

https://www.themoviedb.org/tv/9302

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=Se-2l5A2wu4

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
