### ISSUE TITLE
[TV SHOW]: Digimon Data Squad (2006)

### ISSUE THREAD

**Issue by DoctorGC** [LizardByte/ThemerrDB#4486]
### Database URL

https://www.themoviedb.org/tv/39980

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=M0KsrADzag4

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
