### ISSUE TITLE
[TV SHOW]: BOFURI: I Don't Want to Get Hurt, so I'll Max Out My Defense. (2020)

### ISSUE THREAD

**Issue by DoctorGC** [LizardByte/ThemerrDB#4487]
### Database URL

https://www.themoviedb.org/tv/96402

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=ckxYNTKSVD0

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
