### ISSUE TITLE
[TV SHOW]: Absolute Duo (2015)

### ISSUE THREAD

**Issue by DoctorGC** [LizardByte/ThemerrDB#4488]
### Database URL

https://www.themoviedb.org/tv/65764

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=1CBctbw3c0s

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
