### ISSUE TITLE
[TV SHOW]: Blood Blockade Battlefront (2015)

### ISSUE THREAD

**Issue by DoctorGC** [LizardByte/ThemerrDB#4489]
### Database URL

https://www.themoviedb.org/tv/62327

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=0nkJ8wPseSM

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
