### ISSUE TITLE
[MOVIE]: Octopussy (1983)

### ISSUE THREAD

**Issue by sbg71** [LizardByte/ThemerrDB#4490]
### Database URL

https://www.themoviedb.org/movie/700

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=nn4TA-CBT4Y

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
A theme for this already exists or was submitted before yours. When replacing a theme, please comment your reason for the theme replacement.
