### ISSUE TITLE
[MOVIE]: Never Say Never Again (1983)

### ISSUE THREAD

**Issue by sbg71** [LizardByte/ThemerrDB#4491]
### Database URL

https://www.themoviedb.org/movie/36670

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=47rbbS9XNJE

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
A theme for this already exists or was submitted before yours. When replacing a theme, please mark and comment your reason for the theme replacement.
