### ISSUE TITLE
[MOVIE]: Moonraker (1979)

### ISSUE THREAD

**Issue by sbg71** [LizardByte/ThemerrDB#4492]
### Database URL

https://www.themoviedb.org/movie/698

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=3gDboKGn-Sw

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
A theme for this already exists or was submitted before yours. When replacing a theme, please mark and comment your reason for the theme replacement.
