### ISSUE TITLE
[MOVIE]: The Great Gatsby (2013)

### ISSUE THREAD

**Issue by OcifferAction** [LizardByte/ThemerrDB#4521]
### Database URL

https://www.themoviedb.org/movie/64682

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=Ed1gyX8Jbzs

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
