### ISSUE TITLE
[MOVIE]: Halloween II (1981)

### ISSUE THREAD

**Issue by OcifferAction** [LizardByte/ThemerrDB#4555]
### Database URL

https://www.themoviedb.org/movie/11281

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=8JflWFBreok

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
Someone else submitted same theme which I approved before yours
