### ISSUE TITLE
[TV SHOW]: Digimon: Digital Monsters (1999)

### ISSUE THREAD

**Issue by DoctorGC** [LizardByte/ThemerrDB#4568]
### Database URL

https://www.themoviedb.org/tv/31654

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=WkHntdc3gKQ

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
