### ISSUE TITLE
[TV SHOW]: Shakugan no Shana (2005)

### ISSUE THREAD

**Issue by DoctorGC** [LizardByte/ThemerrDB#4569]
### Database URL

https://www.themoviedb.org/tv/22634

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=Cbq3GpTewmk

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
