### ISSUE TITLE
[TV SHOW]: Yu-Gi-Oh! Zexal (2011)

### ISSUE THREAD

**Issue by DoctorGC** [LizardByte/ThemerrDB#4571]
### Database URL

https://www.themoviedb.org/tv/45854

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=VCQaSklVtb8

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
