### ISSUE TITLE
[TV SHOW]: Eric (2024)

### ISSUE THREAD

**Issue by jj3005** [LizardByte/ThemerrDB#4573]
### Database URL

https://www.themoviedb.org/tv/217667

### YouTube Theme Song Video URL

https://youtu.be/PU9A-kY6JxM?si=jSlg_TN1DZbSTBwT

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
