### ISSUE TITLE
[TV SHOW]: The Cramp Twins (2003)

### ISSUE THREAD

**Issue by Chapster5** [LizardByte/ThemerrDB#4574]
### Database URL

https://www.themoviedb.org/tv/3003

### YouTube Theme Song Video URL

https://youtu.be/qLiMLxPqzQs

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
The video listed has character sounds from the intro. I believe the video below would be better, do you agree?

[https://youtu.be/qLiMLxPqzQs](https://youtu.be/qLiMLxPqzQs)

**Comment by OcifferAction** [comment]
@LizardByte-bot edit https://youtu.be/qLiMLxPqzQs

**Comment by OcifferAction** [comment]
@LizardByte-bot approve

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
