### ISSUE TITLE
[MOVIE]: 1917 (2019)

### ISSUE THREAD

**Issue by JetMick** [LizardByte/ThemerrDB#4575]
### Database URL

https://www.themoviedb.org/movie/530915

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=gqo46lt-8Q4

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
Theme already exists in the database and there's no replacement reason listed. Closing as duplicate.
