### ISSUE TITLE
[MOVIE]: The Great Wall (2016)

### ISSUE THREAD

**Issue by i-am-the-real-guru** [LizardByte/ThemerrDB#4577]
### Database URL

https://www.themoviedb.org/movie/311324

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=P1IGMM-djb4&t=9s

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
