### ISSUE TITLE
[TV SHOW]: Fawlty Towers (1975)

### ISSUE THREAD

**Issue by Chapster5** [LizardByte/ThemerrDB#4580]
### Database URL

https://www.themoviedb.org/tv/2207

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=PseBNmbIzGg

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
