### ISSUE TITLE
[TV SHOW]: Brickleberry (2012)

### ISSUE THREAD

**Issue by ledbasedpaint** [LizardByte/ThemerrDB#4584]
### Database URL

https://www.themoviedb.org/tv/44169

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=UzZjIQDYdN0

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
Theme is too short. How about this instead?

https://www.youtube.com/watch?v=q_-40pHICC4
