### ISSUE TITLE
[MOVIE]: Fright Night (1985)

### ISSUE THREAD

**Issue by necrome99** [LizardByte/ThemerrDB#4587]
### Database URL

https://www.themoviedb.org/movie/11797

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=re_IEpPFdmA&pp=ygUYZnJpZ2h0IG5pZ2h0IDE5ODUgdGhlbWVc

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
