### ISSUE TITLE
[MOVIE]: Stand by Me Doraemon (2014)

### ISSUE THREAD

**Issue by jelosoda** [LizardByte/ThemerrDB#4589]
### Database URL

https://www.themoviedb.org/movie/265712

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=rKsQ-3N-Bks

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
