### ISSUE TITLE
[TV SHOW]: Godzilla Singular Point (2021)

### ISSUE THREAD

**Issue by weatherluvr** [LizardByte/ThemerrDB#4591]
### Database URL

https://www.themoviedb.org/tv/111177

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=C0y2rhgDy4g

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
