### ISSUE TITLE
[TV SHOW]: Behind Her Eyes (2021)

### ISSUE THREAD

**Issue by Meowweb01** [LizardByte/ThemerrDB#4594]
### Database URL

https://www.themoviedb.org/tv/97173

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=7ylCCinShcs

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by Meowweb01** [comment]
Trailer song

**Comment by jjnether** [comment]
@Meowweb01 song is from trailer, not actual show. How about this theme instead?

https://youtu.be/EihumWFaqL4?si=y1xRLXraNry7Z23Z
