### ISSUE TITLE
[TV SHOW]: Arifureta: From Commonplace to World's Strongest (2019)

### ISSUE THREAD

**Issue by SonicCraft** [LizardByte/ThemerrDB#4608]
### Database URL

https://www.themoviedb.org/tv/86034

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=jekubzaLQ3w

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
