### ISSUE TITLE
[MOVIE]: Captain Underpants: The First Epic Movie (2017)

### ISSUE THREAD

**Issue by SonicCraft** [LizardByte/ThemerrDB#4609]
### Database URL

https://www.themoviedb.org/movie/268531

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=41xQ9gLwpHo

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
