### ISSUE TITLE
[MOVIE]: Rambo: Last Blood (2019)

### ISSUE THREAD

**Issue by SonicCraft** [LizardByte/ThemerrDB#4611]
### Database URL

https://www.themoviedb.org/movie/522938

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=z7bQW6yq3P0

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
