### ISSUE TITLE
[TV SHOW]: Saga of Tanya the Evil (2017)

### ISSUE THREAD

**Issue by SonicCraft** [LizardByte/ThemerrDB#4612]
### Database URL

https://www.themoviedb.org/tv/69346

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=w4saikdG9pQ

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
