### ISSUE TITLE
[TV SHOW]: The Chosen (2019)

### ISSUE THREAD

**Issue by SonicCraft** [LizardByte/ThemerrDB#4613]
### Database URL

https://www.themoviedb.org/tv/85077

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=GzIf0R8HtqY

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
