### ISSUE TITLE
[TV SHOW]: Sonic Boom (2014)

### ISSUE THREAD

**Issue by SonicCraft** [LizardByte/ThemerrDB#4614]
### Database URL

https://www.themoviedb.org/tv/62211

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=bPvPuheBxsg

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

### Replacement Reason

Note: This is the closest thing I could find to a theme for the TV show, even though its from the game adaptation.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
