### ISSUE TITLE
[TV SHOW]: Ranking of Kings (2021)

### ISSUE THREAD

**Issue by SonicCraft** [LizardByte/ThemerrDB#4615]
### Database URL

https://www.themoviedb.org/tv/112613

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=TXt4rLLo8ks

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
