### ISSUE TITLE
[TV SHOW]: Sonic Prime (2022)

### ISSUE THREAD

**Issue by SonicCraft** [LizardByte/ThemerrDB#4616]
### Database URL

https://www.themoviedb.org/tv/115577

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=OLK0_cFXrsA

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

### Replacement Reason

Note: This is an extended version of the trailer music, since the opening for this show is like 10 seconds long.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
