### ISSUE TITLE
[MOVIE]: Bad Country (2014)

### ISSUE THREAD

**Issue by SonicCraft** [LizardByte/ThemerrDB#4618]
### Database URL

https://www.themoviedb.org/movie/256731

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=sjvxN7j0L_E

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

### Replacement Reason

Note: Closest thing to a theme song I could find for this movie. There is a cover of this song in the movie.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
