### ISSUE TITLE
[MOVIE]: Bad Words (2013)

### ISSUE THREAD

**Issue by SonicCraft** [LizardByte/ThemerrDB#4619]
### Database URL

https://www.themoviedb.org/movie/209403

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=u8o98fg8-8k

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

### Replacement Reason

Song picked from: https://www.youtube.com/playlist?list=PLu5noyS9Xz6Y1ulC0NJCqzyzQ6iJBiQHX

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
