### ISSUE TITLE
[MOVIE]: Batman: The Killing Joke (2016)

### ISSUE THREAD

**Issue by SonicCraft** [LizardByte/ThemerrDB#4620]
### Database URL

https://www.themoviedb.org/movie/382322

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=xHBSebt4d-c

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

### Replacement Reason

Song picked from: https://www.youtube.com/playlist?list=OLAK5uy_nL7PVx84nzgamkJqc-Eto1zIGLosE0gQY

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
