### ISSUE TITLE
[MOVIE]: Cleanskin (2012)

### ISSUE THREAD

**Issue by SonicCraft** [LizardByte/ThemerrDB#4621]
### Database URL

https://www.themoviedb.org/movie/95516

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=-247nWnmnd4

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

### Replacement Reason

Song picked from: https://www.youtube.com/playlist?list=OLAK5uy_lOiTq7CK1CVxU0lBuR6ksuSHOYQjzI3QE

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
