### ISSUE TITLE
[MOVIE]: Epic (2013)

### ISSUE THREAD

**Issue by SonicCraft** [LizardByte/ThemerrDB#4623]
### Database URL

https://www.themoviedb.org/movie/116711

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=RSjJsetDnVM

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

### Replacement Reason

Song picked from: https://www.youtube.com/playlist?list=PLRW80bBvVD3VqhOb3y19gVfWyH4JusFtx

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
