### ISSUE TITLE
[MOVIE]: Tombstone (1993)

### ISSUE THREAD

**Issue by SonicCraft** [LizardByte/ThemerrDB#4624]
### Database URL

https://www.themoviedb.org/movie/11969

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=t0CBIFkpv4A

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

### Replacement Reason

Song picked from: https://www.youtube.com/playlist?list=PLD8BDB1865D501A9C

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
