### ISSUE TITLE
[MOVIE]: The Mitchells vs. the Machines (2021)

### ISSUE THREAD

**Issue by SonicCraft** [LizardByte/ThemerrDB#4625]
### Database URL

https://www.themoviedb.org/movie/501929

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=0rnrfvLgpWE

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

### Replacement Reason

Song picked from: https://www.youtube.com/playlist?list=PLRW80bBvVD3XXbeZ2gbsSLtJOnbBJZaTq

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
