### ISSUE TITLE
[TV SHOW]: The Owl House (2020)

### ISSUE THREAD

**Issue by maybeanerd** [LizardByte/ThemerrDB#4631]
### Database URL

https://www.themoviedb.org/tv/92685

### YouTube Theme Song Video URL

https://youtu.be/9cfgPSdO3u4

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
The provided link has various versions of the same theme song in a 5 minute long video. Would this version work instead? If so please replace the original YouTube link with this one.

[https://www.youtube.com/watch?v=BqE6KiijtH0](https://www.youtube.com/watch?v=BqE6KiijtH0)

**Comment by maybeanerd** [comment]
It would, but I thought it'd be nice to have all versions included, as they slightly differ between seasons
But If we don't want that, I can ofc change it

**Comment by OcifferAction** [comment]
I appreciate you getting back to me quickly. As it happens, there was another user who requested the theme before you with the aforementioned song. I went ahead and approved theirs so there's no need for further action on your part.
