### ISSUE TITLE
[TV SHOW]: The Cuphead Show! (2022)

### ISSUE THREAD

**Issue by SpaceEnergy** [LizardByte/ThemerrDB#4633]
### Database URL

https://www.themoviedb.org/tv/103786

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=DJEvss4W7fc

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
