### ISSUE TITLE
[TV SHOW]: 2 Broke Girls (2011)

### ISSUE THREAD

**Issue by mrpimpky** [LizardByte/ThemerrDB#4634]
### Database URL

https://www.themoviedb.org/tv/39340

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=LQXvGGzueWA

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
