### ISSUE TITLE
[TV SHOW]: Abbott Elementary (2021)

### ISSUE THREAD

**Issue by mrpimpky** [LizardByte/ThemerrDB#4636]
### Database URL

https://www.themoviedb.org/tv/125935

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=xSxqxClIyWI

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
