### ISSUE TITLE
[TV SHOW]: The X-Files (1993)

### ISSUE THREAD

**Issue by mrpimpky** [LizardByte/ThemerrDB#4638]
### Database URL

https://www.themoviedb.org/tv/4087

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=v4-GcS1UQyg

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
