### ISSUE TITLE
[TV SHOW]: Family Matters (1989)

### ISSUE THREAD

**Issue by mrpimpky** [LizardByte/ThemerrDB#4640]
### Database URL

https://www.themoviedb.org/tv/2685

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=KS6yHCOp3WY

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
