### ISSUE TITLE
[TV SHOW]: Based on a True Story (2023)

### ISSUE THREAD

**Issue by mrpimpky** [LizardByte/ThemerrDB#4642]
### Database URL

https://www.themoviedb.org/tv/197373

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=2PjBZEb4kC0

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
