### ISSUE TITLE
[TV SHOW]: Batman (1966)

### ISSUE THREAD

**Issue by mrpimpky** [LizardByte/ThemerrDB#4643]
### Database URL

https://www.themoviedb.org/tv/2287

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=EZ9ymE2Rcxo

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
The YouTube link provided is a pretty low quality video which would not sound great on Plex. I believe this higher quality version would work better? If you agree, please replace the original YouTube link with this one.

[https://www.youtube.com/watch?v=EZ9ymE2Rcxo](https://www.youtube.com/watch?v=EZ9ymE2Rcxo)

**Comment by mrpimpky** [comment]
I cannot view that video due to

> This video contains content from SME, who has blocked it in your country on copyright grounds.

But I trust your opinion :) I changed the link.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
