### ISSUE TITLE
[TV SHOW]: I Dream of Jeannie (1965)

### ISSUE THREAD

**Issue by mrpimpky** [LizardByte/ThemerrDB#4644]
### Database URL

https://www.themoviedb.org/tv/1660

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=4KxjZCuAwO0

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
This is a video of the intro to the show with all sound effects. I was able to find a higher quality video without the sound effects? Would this video work instead? If so please replace the original YouTube link with this one.

[](https://www.youtube.com/watch?v=4KxjZCuAwO0)

**Comment by mrpimpky** [comment]
It's a replayed version, not the original theme, but there aren't any videos without those effects as far as I can see. So let's take yours.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
