### ISSUE TITLE
[TV SHOW]: Inspector Black Cat (1984)

### ISSUE THREAD

**Issue by baiyebeiou** [LizardByte/ThemerrDB#4649]
### Database URL

https://www.themoviedb.org/tv/91068

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=CgpqTID_3bQ

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
