### ISSUE TITLE
[TV SHOW]: Halo Legends (2010)

### ISSUE THREAD

**Issue by SonicCraft** [LizardByte/ThemerrDB#4650]
### Database URL

https://www.themoviedb.org/tv/60879

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=WzeTOTlOlOY

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

### Replacement Reason

Song picked from: https://www.youtube.com/playlist?list=PL48A6288F943EF294

**Comment by jjnether** [comment]
@LizardByte-bot approve
