### ISSUE TITLE
[MOVIE]: Child 44 (2015)

### ISSUE THREAD

**Issue by OcifferAction** [LizardByte/ThemerrDB#4728]
### Database URL

https://www.themoviedb.org/movie/181283

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=V4QtgbSEciY

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by 7AXEL** [comment]
Check out this project: https://github.com/7AXEL/Web2APK

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
