### ISSUE TITLE
[MOVIE]: Hacksaw Ridge (2016)

### ISSUE THREAD

**Issue by webysther** [LizardByte/ThemerrDB#4736]
### Database URL

https://www.themoviedb.org/movie/324786

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=duPXV-OsfEU

### Additional Information

- [X] This is a replacement request. If checked, please provide a reason below.

### Replacement Reason

video not found

**Comment by jjnether** [comment]
@webysther It's a bit longer, but I think this is more the main theme of the movie. Are you ok with changing to that?

https://www.youtube.com/watch?v=duPXV-OsfEU

**Comment by webysther** [comment]
> @webysther It's a bit longer, but I think this is more the main theme of the movie. Are you ok with changing to that?
> 
> https://www.youtube.com/watch?v=duPXV-OsfEU

I don't know the correct one, i just change for a version that works and looks the theme song, but I don't now how to choose one song from a full OST

**Comment by jjnether** [comment]
Ok no worries, I'll change and approve

**Comment by jjnether** [comment]
@LizardByte-bot edit https://www.youtube.com/watch?v=duPXV-OsfEU

**Comment by jjnether** [comment]
@LizardByte-bot approve
