### ISSUE TITLE
[MOVIE]: Rock 'n' Roll High School (1979)

### ISSUE THREAD

**Issue by ItsMeRyanClark** [LizardByte/ThemerrDB#4773]
### Database URL

https://www.themoviedb.org/movie/26326

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=Tx8fPaZL3MQ

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
Editing with video that doesn't have sounds in the beginning

**Comment by jjnether** [comment]
@LizardByte-bot edit https://www.youtube.com/watch?v=Tx8fPaZL3MQ

**Comment by jjnether** [comment]
@LizardByte-bot approve
