### ISSUE TITLE
[MOVIE]: Bottoms (2023)

### ISSUE THREAD

**Issue by ItsMeRyanClark** [LizardByte/ThemerrDB#4774]
### Database URL

https://www.themoviedb.org/movie/814776

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=o47lSkL8pyY

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
