### ISSUE TITLE
[MOVIE]: Pet Sematary (1989)

### ISSUE THREAD

**Issue by ItsMeRyanClark** [LizardByte/ThemerrDB#4775]
### Database URL

https://www.themoviedb.org/movie/8913

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=HJWFsZ_YUc4

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
