### ISSUE TITLE
[TV SHOW]: Smiling Friends (2020)

### ISSUE THREAD

**Issue by ItsMeRyanClark** [LizardByte/ThemerrDB#4776]
### Database URL

https://www.themoviedb.org/tv/126506

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=xDxgI4l8orc&t=4s

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
