### ISSUE TITLE
[TV SHOW]: Sherlock (2010)

### ISSUE THREAD

**Issue by SonicCraft** [LizardByte/ThemerrDB#4844]
### Database URL

https://www.themoviedb.org/tv/19885

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=pFy94O0RLOg

### Additional Information

- [X] This is a replacement request. If checked, please provide a reason below.

### Replacement Reason

Higher quality audio request. Original youtube url for comparison: https://www.youtube.com/watch?v=gzCEIBaV1Es

**Comment by jjnether** [comment]
@LizardByte-bot approve
