### ISSUE TITLE
[MOVIE]: Hamlet (1996)

### ISSUE THREAD

**Issue by SonicCraft** [LizardByte/ThemerrDB#4845]
### Database URL

https://www.themoviedb.org/movie/10549

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=XfJVbKZZwWs

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

### Replacement Reason

Song picked from: https://www.youtube.com/playlist?list=PLY0HG7j1maOj_92izZYm34yHfnpVejdC7

**Comment by jjnether** [comment]
@LizardByte-bot approve
