### ISSUE TITLE
[MOVIE]: Green Lantern (2011)

### ISSUE THREAD

**Issue by SonicCraft** [LizardByte/ThemerrDB#4846]
### Database URL

https://www.themoviedb.org/movie/44912

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=VJmTEYgF-tI

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

### Replacement Reason

Song picked from: https://www.youtube.com/playlist?list=PL949FJOPKjEGOMmhdK9M3hdYqKd_dDpXi

**Comment by jjnether** [comment]
@LizardByte-bot approve
