### ISSUE TITLE
[MOVIE]: The Lord of the Rings: The Fellowship of the Ring (2001)

### ISSUE THREAD

**Issue by grapethegreat** [LizardByte/ThemerrDB#4847]
### Database URL

https://www.themoviedb.org/movie/120

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=ehAgMszCHU4

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@grapethegreat A theme for this already exists or was submitted before yours. When replacing a theme, please mark that you're replacing a theme and the reason for it in the submission.
