### ISSUE TITLE
[MOVIE]: Despicable Me (2010)

### ISSUE THREAD

**Issue by Poiaman** [LizardByte/ThemerrDB#4849]
### Database URL

https://www.themoviedb.org/movie/20352

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=Ussd5jXHTTc&list=PLLQyrCIfk22eGzTSDCu5r7g-6Xm8nuQGk&index=1&ab_channel=DamM012

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
A theme for this already exists or was submitted before yours. When replacing a theme, please mark that you're replacing a theme and the reason for it in the submission.
