### ISSUE TITLE
[MOVIE]: Despicable Me 3 (2017)

### ISSUE THREAD

**Issue by Poiaman** [LizardByte/ThemerrDB#4851]
### Database URL

https://www.themoviedb.org/movie/324852

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=KzRMxu-GIcs&ab_channel=MoneyBoys

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
A theme for this already exists or was submitted before yours. When replacing a theme, please mark that you're replacing a theme and the reason for it in the submission.
