### ISSUE TITLE
[MOVIE]: Sonic the Hedgehog (2020)

### ISSUE THREAD

**Issue by SonicCraft** [LizardByte/ThemerrDB#4852]
### Database URL

https://www.themoviedb.org/movie/454626

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=UbiR5xNo-3Q

### Additional Information

- [x] This is a replacement request. If checked, please provide a reason below.

### Replacement Reason

Song picked from: https://www.youtube.com/playlist?list=OLAK5uy_kctsyIT7fXOIZtHN2Tu1FZuRhNDosnUO0

**Comment by jjnether** [comment]
A theme for this already exists or was submitted before yours. When replacing a theme, please mark that you're replacing a theme and the reason for it in the submission.

**Comment by SonicCraft** [comment]
Apologies! The plugin was showing that it had no theme for this so I submitted one. I just took a look and it seems that issue #150 was the original submission, and has a dead link, thus causing the lack of a theme on my end.

**Comment by jjnether** [comment]
> Apologies! The plugin was showing that it had no theme for this so I submitted one. I just took a look and it seems that issue #151 was the original submission, and has a dead link, thus causing the lack of a theme on my end.

No worries, please just add the reason for the replacement when you submit the issue next time. We close duplicate issues that don't state a reason.

**Comment by jjnether** [comment]
@LizardByte-bot approve
