### ISSUE TITLE
[MOVIE]: 20 Days in Mariupol (2023)

### ISSUE THREAD

**Issue by sahara101** [LizardByte/ThemerrDB#4853]
### Database URL

https://www.themoviedb.org/movie/1058616

### YouTube Theme Song Video URL

https://youtu.be/yHaL6G1BCTc?si=R61XCPVbAXtfwqvF

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
