### ISSUE TITLE
[MOVIE]: Agent Recon (2024)

### ISSUE THREAD

**Issue by sahara101** [LizardByte/ThemerrDB#4854]
### Database URL

https://www.themoviedb.org/movie/1198899

### YouTube Theme Song Video URL

https://youtu.be/bv5_7SrR5AE?si=j6qrxQiaOM_TYg3z

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
