### ISSUE TITLE
[MOVIE]: American Factory (2019)

### ISSUE THREAD

**Issue by sahara101** [LizardByte/ThemerrDB#4855]
### Database URL

https://www.themoviedb.org/movie/565716

### YouTube Theme Song Video URL

https://youtu.be/bAh27FwAMsE?si=TJQ_hT1e0trumn86

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
