### ISSUE TITLE
[MOVIE]: Be Water (2020)

### ISSUE THREAD

**Issue by sahara101** [LizardByte/ThemerrDB#4856]
### Database URL

https://www.themoviedb.org/movie/653733

### YouTube Theme Song Video URL

https://youtu.be/9K4g7SWhzTk?si=1Bi3CAKzXEabHmR-

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
