### ISSUE TITLE
[TV SHOW]: Super Dragon Ball Heroes (2018)

### ISSUE THREAD

**Issue by sahara101** [LizardByte/ThemerrDB#4857]
### Database URL

https://www.themoviedb.org/tv/80020

### YouTube Theme Song Video URL

https://youtu.be/FM4hOyexiNg?si=kTvcMsAWvfhcP3tt

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
