### ISSUE TITLE
[MOVIE]: Turbo: A Power Rangers Movie (1997)

### ISSUE THREAD

**Issue by weatherluvr** [LizardByte/ThemerrDB#4858]
### Database URL

https://www.themoviedb.org/movie/6499

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=UUqlgWjpTpM

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
