### ISSUE TITLE
[TV SHOW]: The King's Avatar (2019)

### ISSUE THREAD

**Issue by weatherluvr** [LizardByte/ThemerrDB#4859]
### Database URL

https://www.themoviedb.org/tv/91470

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=EvO3tdyPIzs

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
