### ISSUE TITLE
[MOVIE]: The Devil Wears Prada (2006)

### ISSUE THREAD

**Issue by weatherluvr** [LizardByte/ThemerrDB#4861]
### Database URL

https://www.themoviedb.org/movie/350

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=cwKnszWPnuY

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
A theme for this already exists or was submitted before yours. When replacing a theme, please mark that you're replacing a theme and the reason for it in the submission.

**Comment by weatherluvr** [comment]
> A theme for this already exists or was submitted before yours. When replacing a theme, please mark that you're replacing a theme and the reason for it in the submission.

Was this recently added?  Thermerr is reporting it as no theme existing:
![image](https://github.com/LizardByte/ThemerrDB/assets/170429187/6fb9dd7e-ece7-4446-a754-5b17f0b6d964)

Though, I do get a dashboard update error whenever I go into the plugin, so not sure if that would be why I'm seeing it reflected as no theme/having the ability to request/provide a theme.

**Comment by jjnether** [comment]
It was added many months ago, my guess is your Themerr just hasn't downloaded it yet. If you're having issues with the plugin, please join the discord server and open new thread under Themerr.
