### ISSUE TITLE
[TV SHOW]: Steven Universe Future (2019)

### ISSUE THREAD

**Issue by weatherluvr** [LizardByte/ThemerrDB#4862]
### Database URL

https://www.themoviedb.org/tv/94280

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=1LMGVx31zso

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
