### ISSUE TITLE
[TV SHOW]: Sense8 (2015)

### ISSUE THREAD

**Issue by weatherluvr** [LizardByte/ThemerrDB#4863]
### Database URL

https://www.themoviedb.org/tv/61664

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=f9ZqGFiKwA8

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
