### ISSUE TITLE
[TV SHOW]: Schitt's Creek (2015)

### ISSUE THREAD

**Issue by weatherluvr** [LizardByte/ThemerrDB#4864]
### Database URL

https://www.themoviedb.org/tv/61662

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=fnI8cPgV3Jo

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
