### ISSUE TITLE
[TV SHOW]: Power Rangers (1993)

### ISSUE THREAD

**Issue by weatherluvr** [LizardByte/ThemerrDB#4865]
### Database URL

https://www.themoviedb.org/tv/2328

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=BwbHW8MeHDU

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
