### ISSUE TITLE
[MOVIE]: Rebirth of Mothra (1996)

### ISSUE THREAD

**Issue by weatherluvr** [LizardByte/ThemerrDB#4866]
### Database URL

https://www.themoviedb.org/movie/36214

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=2urxpxx2MWE

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
