### ISSUE TITLE
[MOVIE]: Rebirth of Mothra II (1997)

### ISSUE THREAD

**Issue by weatherluvr** [LizardByte/ThemerrDB#4867]
### Database URL

https://www.themoviedb.org/movie/36212

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=YDYGtqPioRs

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
