### ISSUE TITLE
[MOVIE]: Rebirth of Mothra III (1998)

### ISSUE THREAD

**Issue by weatherluvr** [LizardByte/ThemerrDB#4868]
### Database URL

https://www.themoviedb.org/movie/36247

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=a1bQ-ktOFxA

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
