### ISSUE TITLE
[MOVIE]: Mighty Morphin Power Rangers: The Movie (1995)

### ISSUE THREAD

**Issue by weatherluvr** [LizardByte/ThemerrDB#4869]
### Database URL

https://www.themoviedb.org/movie/9070

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=eFUkzfIcxPA

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
