### ISSUE TITLE
[MOVIE]: Mighty Morphin Power Rangers: Once & Always (2023)

### ISSUE THREAD

**Issue by weatherluvr** [LizardByte/ThemerrDB#4870]
### Database URL

https://www.themoviedb.org/movie/1068141

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=KYNq-b3KpBo

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
