### ISSUE TITLE
[TV SHOW]: Kotaro Lives Alone (2022)

### ISSUE THREAD

**Issue by weatherluvr** [LizardByte/ThemerrDB#4871]
### Database URL

https://www.themoviedb.org/tv/134581

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=Pf47ZNJhJ38

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
