### ISSUE TITLE
[TV SHOW]: Sabrina, the Teenage Witch (1996)

### ISSUE THREAD

**Issue by weatherluvr** [LizardByte/ThemerrDB#4874]
### Database URL

https://www.themoviedb.org/tv/605

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=1-dhDas5iEg

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
