### ISSUE TITLE
[TV SHOW]: Attack on Titan (2013)

### ISSUE THREAD

**Issue by Eddie-Server** [LizardByte/ThemerrDB#4875]
### Database URL

https://www.themoviedb.org/tv/1429

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=6TolbTZXDjI

### Additional Information

- [X] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
A theme for this already exists or was submitted before yours. When replacing a theme, please mark that you're replacing a theme and the reason for it in the submission.
