### ISSUE TITLE
[MOVIE]: Sonic the Hedgehog 2 (2022)

### ISSUE THREAD

**Issue by SonicCraft** [LizardByte/ThemerrDB#5036]
### Database URL

https://www.themoviedb.org/movie/675353

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=j3C3Z-ldjVA

### Additional Information

- [X] This is a replacement request. If checked, please provide a reason below.

### Replacement Reason

Original video has muffled parts throughout and is a fan mix of the trailer track plus parts from the behind the scenes "thrills and quills" video, neither of witch was ever used in the movie at all. Suggestion picked from: https://www.youtube.com/playlist?list=PLohYzz4btpaQXbCYetMBF5vfeXeSR-W_V

**Comment by jjnether** [comment]
@LizardByte-bot approve
