### ISSUE TITLE
[TV SHOW]: Azumanga Daioh (2002)

### ISSUE THREAD

**Issue by Bundas18** [LizardByte/ThemerrDB#5077]
### Database URL

https://www.themoviedb.org/tv/12143

### YouTube Theme Song Video URL

https://youtu.be/bsGAsJBW6zM?si=fcB2IVXUXWRcrBgu

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
