### ISSUE TITLE
[TV SHOW]: Trailer Park Boys (2001)

### ISSUE THREAD

**Issue by RJSkudra** [LizardByte/ThemerrDB#5127]
### Database URL

https://www.themoviedb.org/tv/3796

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=1bhC0cbmre4

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
