### ISSUE TITLE
[MOVIE]: Airplane! (1980)

### ISSUE THREAD

**Issue by RJSkudra** [LizardByte/ThemerrDB#5129]
### Database URL

https://www.themoviedb.org/movie/813

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=y5Hkpvs6W04

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
A theme for this already exists or was submitted before yours. When replacing a theme in the future, please mark that you're replacing a theme and the reason for it in the submission.
