### ISSUE TITLE
[MOVIE]: Venom: Let There Be Carnage (2021)

### ISSUE THREAD

**Issue by RJSkudra** [LizardByte/ThemerrDB#5132]
### Database URL

https://www.themoviedb.org/movie/580489

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=ojeR-YVv-ag

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
A theme for this already exists or was submitted before yours. When replacing a theme in the future, please mark that you're replacing a theme and the reason for it in the submission.
