### ISSUE TITLE
[TV SHOW]: My Adventures with Superman (2023)

### ISSUE THREAD

**Issue by Cwavs** [LizardByte/ThemerrDB#5134]
### Database URL

https://www.themoviedb.org/tv/125928

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=H8zqDd4bdmE

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
