### ISSUE TITLE
[TV SHOW]: Life on Mars (2006)

### ISSUE THREAD

**Issue by Cwavs** [LizardByte/ThemerrDB#5135]
### Database URL

https://www.themoviedb.org/tv/2973

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=kzntDgOLox8

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by Cwavs** [comment]
Unfortunately couldn't find one without the narration, that said it's inclusion does have a certain charm.

**Comment by jjnether** [comment]
@Cwavs How about this instead? We really shouldn't be having any themes with dialogue like that in the theme.

https://youtu.be/0oWUcpwu_pE?si=XSdo198kW5M4ThkN

**Comment by Cwavs** [comment]
This doesn't play that often in the show, they don't tend to repeat soundtracks that often, switching between quite a few 70s songs. Might be best just leaving this without a theme?

**Comment by jjnether** [comment]
> This doesn't play that often in the show, they don't tend to repeat soundtracks that often, switching between quite a few 70s songs. Might be best just leaving this without a theme?

I think it's fine to add a theme, it just needs to be one without dialogue. You know the show, so if you find a specific 70's song or soundtrack song that you think is appropriate, we can use that
