### ISSUE TITLE
[MOVIE]: A Christmas Story 2 (2012)

### ISSUE THREAD

**Issue by the-rodriguez** [LizardByte/ThemerrDB#5136]
### Database URL

https://www.themoviedb.org/movie/125504

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=9uwFMvsmNA8

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
