### ISSUE TITLE
[TV SHOW]: Last Week Tonight with John Oliver (2014)

### ISSUE THREAD

**Issue by ropiteaux** [LizardByte/ThemerrDB#5137]
### Database URL

https://www.themoviedb.org/tv/60694

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=ZqG6fEXFhL0

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
