### ISSUE TITLE
[TV SHOW]: The White Lotus (2021)

### ISSUE THREAD

**Issue by ropiteaux** [LizardByte/ThemerrDB#5138]
### Database URL

https://www.themoviedb.org/tv/111803

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=l2wj6lJtg_8

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
