### ISSUE TITLE
[TV SHOW]: Silicon Valley (2014)

### ISSUE THREAD

**Issue by ropiteaux** [LizardByte/ThemerrDB#5139]
### Database URL

https://www.themoviedb.org/tv/60573

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=LfzRlnfl09Q

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
