### ISSUE TITLE
[TV SHOW]: A Gentleman in Moscow (2024)

### ISSUE THREAD

**Issue by ropiteaux** [LizardByte/ThemerrDB#5140]
### Database URL

https://www.themoviedb.org/tv/208942

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=Q3eP1vNRw-8

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
There's about 5 seconds before the opening starts. I've found another version that does not have the long pause in the beginning. Does this work instead? If so please replace the original link with the new one.

[https://www.youtube.com/watch?v=Q3eP1vNRw-8](https://www.youtube.com/watch?v=Q3eP1vNRw-8)

**Comment by ropiteaux** [comment]
✅

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
