### ISSUE TITLE
[TV SHOW]: New Amsterdam (2018)

### ISSUE THREAD

**Issue by ropiteaux** [LizardByte/ThemerrDB#5141]
### Database URL

https://www.themoviedb.org/tv/80350

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=8y-Ug699fDI

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
