### ISSUE TITLE
[TV SHOW]: The Wire (2002)

### ISSUE THREAD

**Issue by ropiteaux** [LizardByte/ThemerrDB#5142]
### Database URL

https://www.themoviedb.org/tv/1438

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=pz9D1SybuVE

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@ropiteaux video seems to be age-restricted. Please replace with a non-age restricted theme

**Comment by ropiteaux** [comment]
tested on private browsing, should be good now

**Comment by jjnether** [comment]
@LizardByte-bot approve
