### ISSUE TITLE
[TV SHOW]: Mayor of Kingstown (2021)

### ISSUE THREAD

**Issue by ropiteaux** [LizardByte/ThemerrDB#5143]
### Database URL

https://www.themoviedb.org/tv/97951

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=QfIetfELdwo

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
