### ISSUE TITLE
[TV SHOW]: Slow Horses (2022)

### ISSUE THREAD

**Issue by ropiteaux** [LizardByte/ThemerrDB#5144]
### Database URL

https://www.themoviedb.org/tv/95480

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=mmuW6XCvBcw

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
