### ISSUE TITLE
[MOVIE]: Transcendence (2014)

### ISSUE THREAD

**Issue by ropiteaux** [LizardByte/ThemerrDB#5147]
### Database URL

https://www.themoviedb.org/movie/157353

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=KW-LyZMU5JI

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
We typically try to shy away from trailer music being used as theme music. I've found the original score album on YouTube. How does this song work instead?

[https://www.youtube.com/watch?v=KW-LyZMU5JI](https://www.youtube.com/watch?v=KW-LyZMU5JI)

**Comment by ropiteaux** [comment]
lgtm!

**Comment by OcifferAction** [comment]
@LizardByte-bot edit https://www.youtube.com/watch?v=KW-LyZMU5JI

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
