### ISSUE TITLE
[MOVIE]: Beverly Hills Cop: Axel F (2024)

### ISSUE THREAD

**Issue by RJSkudra** [LizardByte/ThemerrDB#5150]
### Database URL

https://www.themoviedb.org/movie/280180

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=Jw1aKwElnNY

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
