### ISSUE TITLE
[MOVIE]: Braddock: Missing in Action III (1988)

### ISSUE THREAD

**Issue by sahara101** [LizardByte/ThemerrDB#5153]
### Database URL

https://www.themoviedb.org/movie/27352

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=MQU97TRaSYY

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
The requested song has a lot of background noise and low bitrate. I couldn't find a better version on YouTube. Would this theme from the original score work instead?

[https://www.youtube.com/watch?v=MQU97TRaSYY](https://www.youtube.com/watch?v=MQU97TRaSYY)

**Comment by OcifferAction** [comment]
@LizardByte-bot edit https://www.youtube.com/watch?v=MQU97TRaSYY

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
