### ISSUE TITLE
[MOVIE]: Bruce Lee and Kung Fu Mania (1992)

### ISSUE THREAD

**Issue by sahara101** [LizardByte/ThemerrDB#5154]
### Database URL

https://www.themoviedb.org/movie/167620

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=ISK97vb9IPc

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve

**Comment by jjnether** [comment]
@sahara101 Please add a theme without dialogue in the beginning
