### ISSUE TITLE
[MOVIE]: Bruce Lee: A Warrior's Journey (2000)

### ISSUE THREAD

**Issue by sahara101** [LizardByte/ThemerrDB#5155]
### Database URL

https://www.themoviedb.org/movie/37588

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=s3tNX2Z3psc

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by sahara101** [comment]
Sorry, this one: https://www.youtube.com/watch?v=-kZrfaTw088

**Comment by OcifferAction** [comment]
@LizardByte-bot edit https://www.youtube.com/watch?v=s3tNX2Z3psc

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
