### ISSUE TITLE
[MOVIE]: Bruce Lee: The Legend (1984)

### ISSUE THREAD

**Issue by sahara101** [LizardByte/ThemerrDB#5156]
### Database URL

https://www.themoviedb.org/movie/44645

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=EGyhaKXJA2g

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
