### ISSUE TITLE
[MOVIE]: Bruce Lee: The Legend Lives On (1999)

### ISSUE THREAD

**Issue by sahara101** [LizardByte/ThemerrDB#5157]
### Database URL

https://www.themoviedb.org/movie/167684

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=Likzk5YtgCE

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
