### ISSUE TITLE
[TV SHOW]: Alya Sometimes Hides Her Feelings in Russian (2024)

### ISSUE THREAD

**Issue by Shubham-C12** [LizardByte/ThemerrDB#5158]
### Database URL

https://www.themoviedb.org/tv/235758

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=ddo9uNqdjYY

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
