### ISSUE TITLE
[MOVIE]: Bruce Lee: The Man and the Legend (1973)

### ISSUE THREAD

**Issue by sahara101** [LizardByte/ThemerrDB#5159]
### Database URL

https://www.themoviedb.org/movie/154114

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=losFkjxaRgQ

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
