### ISSUE TITLE
[MOVIE]: Chuck Norris vs Communism (2015)

### ISSUE THREAD

**Issue by sahara101** [LizardByte/ThemerrDB#5160]
### Database URL

https://www.themoviedb.org/movie/312152

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=6PYecRtYPkE

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
