### ISSUE TITLE
[MOVIE]: The Curse of the Dragon (1993)

### ISSUE THREAD

**Issue by sahara101** [LizardByte/ThemerrDB#5162]
### Database URL

https://www.themoviedb.org/movie/72680

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=9vNKUjNRf9M

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
