### ISSUE TITLE
[TV SHOW]: Regular Show (2010)

### ISSUE THREAD

**Issue by Nalon37** [LizardByte/ThemerrDB#5163]
### Database URL

https://www.themoviedb.org/tv/31132

### YouTube Theme Song Video URL

https://youtu.be/l13QI3mzRXE?si=5HJ3NrxEbySLmz_w

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by Nalon37** [comment]
@LizardByte-bot approve

**Comment by jjnether** [comment]
@LizardByte-bot approve
