### ISSUE TITLE
[TV SHOW]: A Good Girl's Guide to Murder (2024)

### ISSUE THREAD

**Issue by SonicCraft** [LizardByte/ThemerrDB#5164]
### Database URL

https://www.themoviedb.org/tv/218342

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=l0yB1nf42CU

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

### Replacement Reason

This is the clean version of the song used in the trailer for the show.

**Comment by jjnether** [comment]
@LizardByte-bot approve
