### ISSUE TITLE
[MOVIE]: Chariots of Fire (1981)

### ISSUE THREAD

**Issue by webysther** [LizardByte/ThemerrDB#5165]
### Database URL

https://www.themoviedb.org/movie/9443

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=8a-HfNE3EIo

### Additional Information

- [X] This is a replacement request. If checked, please provide a reason below.

### Replacement Reason

Video unavailable

**Comment by jjnether** [comment]
@LizardByte-bot approve
