### ISSUE TITLE
[TV SHOW]: Friends (1994)

### ISSUE THREAD

**Issue by pbf801** [LizardByte/ThemerrDB#5166]
### Database URL

https://www.themoviedb.org/tv/1668

### YouTube Theme Song Video URL

https://youtu.be/Xs-HbHCcK58

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
A theme for this already exists or was submitted before yours. When replacing a theme in the future, please mark that you're replacing a theme and the reason for it in the submission.
