### ISSUE TITLE
[MOVIE]: Hop (2011)

### ISSUE THREAD

**Issue by SonicCraft** [LizardByte/ThemerrDB#5168]
### Database URL

https://www.themoviedb.org/movie/50359

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=gXuf8nBib3U

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

### Replacement Reason

Song picked from: https://www.youtube.com/playlist?list=OLAK5uy_l0dPhKoaJ2auvhIvzrapj6l1yEToghUPM

**Comment by jjnether** [comment]
@LizardByte-bot approve
