### ISSUE TITLE
[MOVIE]: Home (2015)

### ISSUE THREAD

**Issue by SonicCraft** [LizardByte/ThemerrDB#5169]
### Database URL

https://www.themoviedb.org/movie/228161

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=HhEFEbmsgfU

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

### Replacement Reason

Song picked from: https://www.youtube.com/playlist?list=PL3DWxOE1cte_i-hSydd7IydE9UKZc1XnG

**Comment by jjnether** [comment]
@LizardByte-bot approve
