### ISSUE TITLE
[MOVIE]: The Devil Wears Prada (2006)

### ISSUE THREAD

**Issue by weatherluvr** [LizardByte/ThemerrDB#5190]
### Database URL

https://www.themoviedb.org/movie/350

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=cwKnszWPnuY

### Additional Information

- [X] This is a replacement request. If checked, please provide a reason below.

### Replacement Reason

Old YT Video (https://www.youtube.com/watch?v=ydRn4b_93J8) is no longer available as the associated account is terminated.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
