### ISSUE TITLE
[MOVIE]: 1492: Conquest of Paradise (1992)

### ISSUE THREAD

**Issue by Markus231086** [LizardByte/ThemerrDB#5192]
### Database URL

https://www.themoviedb.org/movie/1492

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=7ufkMTshjz8

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
