### ISSUE TITLE
[MOVIE]: The Man Who Knew Too Little (1997)

### ISSUE THREAD

**Issue by Markus231086** [LizardByte/ThemerrDB#5210]
### Database URL

https://www.themoviedb.org/movie/9414

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=mRajTuZhXtg

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
