### ISSUE TITLE
[MOVIE]: Alice in the Cities (1974)

### ISSUE THREAD

**Issue by Markus231086** [LizardByte/ThemerrDB#5211]
### Database URL

https://www.themoviedb.org/movie/2204

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=GAgS1IjxcQ4

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
