### ISSUE TITLE
[MOVIE]: Despicable Me 3 (2017)

### ISSUE THREAD

**Issue by iNfRaS0NiC** [LizardByte/ThemerrDB#5215]
### Database URL

https://www.themoviedb.org/movie/324852

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=Ng_Lmb0-aTk

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
Movie already has theme in database and no replacement reason was listed. Closing as duplicate.
