### ISSUE TITLE
[TV SHOW]: 7th Heaven (1996)

### ISSUE THREAD

**Issue by OzZy02100** [LizardByte/ThemerrDB#5217]
### Database URL

https://www.themoviedb.org/tv/4550

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=Obr9NNNU8IQ

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by SonicCraft** [comment]
Maybe https://www.youtube.com/watch?v=Obr9NNNU8IQ would work?

**Comment by jjnether** [comment]
@LizardByte-bot edit https://www.youtube.com/watch?v=Obr9NNNU8IQ

**Comment by jjnether** [comment]
@LizardByte-bot approve
