### ISSUE TITLE
[MOVIE]: Garfield (2004)

### ISSUE THREAD

**Issue by iNfRaS0NiC** [LizardByte/ThemerrDB#5247]
### Database URL

https://www.themoviedb.org/movie/8920

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=WY-kjz86ewY

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@iNfRaS0NiC Please add a theme without the 20th century fox opening
