### ISSUE TITLE
[TV SHOW]: 16bit Sensation: Another Layer (2023)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5302]
### Database URL

https://www.themoviedb.org/tv/217512

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=yhYCblIxfU0

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
