### ISSUE TITLE
[TV SHOW]: Aldnoah.Zero (2014)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5304]
### Database URL

https://www.themoviedb.org/tv/61259

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=lVyKLLW3NB0

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
