### ISSUE TITLE
[TV SHOW]: Am I Actually the Strongest? (2023)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5305]
### Database URL

https://www.themoviedb.org/tv/209649

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=kEp_ZMPWWdU

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
