### ISSUE TITLE
[TV SHOW]: Heaven's Lost Property (2009)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5307]
### Database URL

https://www.themoviedb.org/tv/37437

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=vLl9_djr9LE

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
