### ISSUE TITLE
[TV SHOW]: Ao-chan Can't Study! (2019)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5308]
### Database URL

https://www.themoviedb.org/tv/87462

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=IqxqhMclCs8

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
