### ISSUE TITLE
[TV SHOW]: Code Geass: Rozé of the Recapture (2024)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5310]
### Database URL

https://www.themoviedb.org/tv/255107

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=pGUjIgq2BlY

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
