### ISSUE TITLE
[TV SHOW]: Unnamed Memory (2024)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5311]
### Database URL

https://www.themoviedb.org/tv/216272

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=dpEdweWbHiU

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
