### ISSUE TITLE
[TV SHOW]: ARK: The Animated Series (2024)

### ISSUE THREAD

**Issue by SpaceEnergy** [LizardByte/ThemerrDB#5351]
### Database URL

https://www.themoviedb.org/tv/123625

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=MDBywUFGNoI

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
