### ISSUE TITLE
[TV SHOW]: DAHMER - Monster: The Jeffrey Dahmer Story (2022)

### ISSUE THREAD

**Issue by SpaceEnergy** [LizardByte/ThemerrDB#5352]
### Database URL

https://www.themoviedb.org/tv/113988

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=KXMtcsoLb8g

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
