### ISSUE TITLE
[TV SHOW]: Sweet Tooth (2021)

### ISSUE THREAD

**Issue by SpaceEnergy** [LizardByte/ThemerrDB#5355]
### Database URL

https://www.themoviedb.org/tv/103768

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=UdkwJmccc9s

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
