### ISSUE TITLE
[MOVIE]: Only Yesterday (1991)

### ISSUE THREAD

**Issue by SpaceEnergy** [LizardByte/ThemerrDB#5356]
### Database URL

https://www.themoviedb.org/movie/15080

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=ogy5JVextNA

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
