### ISSUE TITLE
[MOVIE]: From Up on Poppy Hill (2011)

### ISSUE THREAD

**Issue by SpaceEnergy** [LizardByte/ThemerrDB#5357]
### Database URL

https://www.themoviedb.org/movie/83389

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=BNkG8fFxQcE

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
