### ISSUE TITLE
[MOVIE]: The Imaginary (2023)

### ISSUE THREAD

**Issue by SpaceEnergy** [LizardByte/ThemerrDB#5358]
### Database URL

https://www.themoviedb.org/movie/913001

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=XmmpiW2X6Eo

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
