### ISSUE TITLE
[MOVIE]: Cobweb (2023)

### ISSUE THREAD

**Issue by iNfRaS0NiC** [LizardByte/ThemerrDB#5361]
### Database URL

https://www.themoviedb.org/movie/709631

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=gtcbh-BFJI0

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
