### ISSUE TITLE
[MOVIE]: The Garfield Movie (2024)

### ISSUE THREAD

**Issue by iNfRaS0NiC** [LizardByte/ThemerrDB#5362]
### Database URL

https://www.themoviedb.org/movie/748783

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=KgdFHkx3kUQ

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
The video provided is a part of a playlist and will not import properly. Can you update your link to provide only that video?

**Comment by iNfRaS0NiC** [comment]
@OcifferAction updated in the OP - https://www.youtube.com/watch?v=KgdFHkx3kUQ

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
