### ISSUE TITLE
[TV SHOW]: Black Summoner (2022)

### ISSUE THREAD

**Issue by SonicCraft** [LizardByte/ThemerrDB#5364]
### Database URL

https://www.themoviedb.org/tv/157842

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=UQgv8MBxCuU

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

### Replacement Reason

Full song from: https://www.youtube.com/watch?v=1ev6YeMqDdI

**Comment by jjnether** [comment]
@LizardByte-bot approve
