### ISSUE TITLE
[TV SHOW]: By the Grace of the Gods (2020)

### ISSUE THREAD

**Issue by SonicCraft** [LizardByte/ThemerrDB#5365]
### Database URL

https://www.themoviedb.org/tv/102086

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=OWhP3q73D50

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

### Replacement Reason

Full song from: https://www.youtube.com/watch?v=ERVo4Z2D10s

**Comment by jjnether** [comment]
@LizardByte-bot approve
