### ISSUE TITLE
[TV SHOW]: Horimiya: The Missing Pieces (2023)

### ISSUE THREAD

**Issue by SonicCraft** [LizardByte/ThemerrDB#5367]
### Database URL

https://www.themoviedb.org/tv/228663

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=NXoUBMx3BJE

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

### Replacement Reason

Note: Horimiya: The Missing Pieces is also called Horimiya: Pieces

**Comment by jjnether** [comment]
@LizardByte-bot approve
