### ISSUE TITLE
[TV SHOW]: Obi-Wan Kenobi (2022)

### ISSUE THREAD

**Issue by SonicCraft** [LizardByte/ThemerrDB#5368]
### Database URL

https://www.themoviedb.org/tv/92830

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=HLn8e3aU7eI

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
