### ISSUE TITLE
[TV SHOW]: Kakegurui (2017)

### ISSUE THREAD

**Issue by weatherluvr** [LizardByte/ThemerrDB#5371]
### Database URL

https://www.themoviedb.org/tv/72305

### YouTube Theme Song Video URL

https://youtu.be/PeYHU_qMQuI?si=96P5U3zStsj8-wrK

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@weatherluvr this is the theme from Devil Wears Prada. Please provide a theme from the TV Show you are submitting for

**Comment by weatherluvr** [comment]
> @weatherluvr this is the theme from Devil Wears Prada. Please provide a theme from the TV Show you are submitting for

Updated with the new link. Sorry! Copy paste error.

**Comment by jjnether** [comment]
> > @weatherluvr this is the theme from Devil Wears Prada. Please provide a theme from the TV Show you are submitting for
> 
> Updated with the new link. Sorry! Copy paste error.

no worries!

**Comment by jjnether** [comment]
@LizardByte-bot approve
