### ISSUE TITLE
[TV SHOW]: THE NEW GATE (2024)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5372]
### Database URL

https://www.themoviedb.org/tv/239161

### YouTube Theme Song Video URL

https://youtu.be/6Rdw3zrjwzo?si=ZSHePn5awlb6irHL

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by sebrilax** [comment]
Change link, previous private

https://youtu.be/6Rdw3zrjwzo?si=ZSHePn5awlb6irHL

**Comment by jjnether** [comment]
@LizardByte-bot edit https://youtu.be/6Rdw3zrjwzo?si=ZSHePn5awlb6irHL

**Comment by jjnether** [comment]
@LizardByte-bot approve
