### ISSUE TITLE
[TV SHOW]: Death March to the Parallel World Rhapsody (2018)

### ISSUE THREAD

**Issue by SonicCraft** [LizardByte/ThemerrDB#5373]
### Database URL

https://www.themoviedb.org/tv/76122

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=SjeJ05MatOE

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

### Replacement Reason

Full song from: https://www.youtube.com/watch?v=qMeC9fydMaI

**Comment by jjnether** [comment]
@LizardByte-bot approve
