### ISSUE TITLE
[TV SHOW]: Shikimori's Not Just a Cutie (2022)

### ISSUE THREAD

**Issue by SonicCraft** [LizardByte/ThemerrDB#5374]
### Database URL

https://www.themoviedb.org/tv/115694

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=wE0N7NcpzQ4

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

### Replacement Reason

Full song from: https://www.youtube.com/watch?v=Bme2siFikIs

**Comment by jjnether** [comment]
@LizardByte-bot approve
