### ISSUE TITLE
[MOVIE]: Mary Poppins (1964)

### ISSUE THREAD

**Issue by SonicCraft** [LizardByte/ThemerrDB#5375]
### Database URL

https://www.themoviedb.org/movie/433

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=FS8ydFYw8Sw

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

### Replacement Reason

Song picked from: https://www.youtube.com/playlist?list=PLtlRsnKr2ic9-Fe4t98mQ8ceA30juh--u (picked the overture as it was instrumental and, well, an overture :D)

**Comment by jjnether** [comment]
@LizardByte-bot approve
