### ISSUE TITLE
[TV SHOW]: 'Tis Time for "Torture," Princess (2024)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5376]
### Database URL

https://www.themoviedb.org/tv/229443

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=L8WDAYNTaz8

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
