### ISSUE TITLE
[TV SHOW]: A Condition Called Love (2024)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5378]
### Database URL

https://www.themoviedb.org/tv/239214

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=HI24Dh3fNRg

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
