### ISSUE TITLE
[TV SHOW]: A Couple of Cuckoos (2022)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5379]
### Database URL

https://www.themoviedb.org/tv/122587

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=zKSg-Y2MsZM

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
