### ISSUE TITLE
[TV SHOW]: A Galaxy Next Door (2023)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5380]
### Database URL

https://www.themoviedb.org/tv/200732

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=plXjVrAlpWo

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
