### ISSUE TITLE
[TV SHOW]: A Playthrough of a Certain Dude's VRMMO Life (2023)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5381]
### Database URL

https://www.themoviedb.org/tv/229610

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=e9athtafL7w

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
