### ISSUE TITLE
[TV SHOW]: How a Realist Hero Rebuilt the Kingdom (2021)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5382]
### Database URL

https://www.themoviedb.org/tv/102088

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=i-ltrrEAFFs

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
