### ISSUE TITLE
[TV SHOW]: Adam's Sweet Agony (2024)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5384]
### Database URL

https://www.themoviedb.org/tv/241002

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=zY4nPubLRhc

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
