### ISSUE TITLE
[MOVIE]: Fantastic Beasts: The Secrets of Dumbledore (2022)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5386]
### Database URL

https://www.themoviedb.org/movie/338953

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=0tx57i7lG1Q

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
A theme for this already exists or was submitted before yours. When replacing a theme in the future, please mark that you're replacing a theme and the reason for it in the submission.

**Comment by sebrilax** [comment]
Thanks, it's just that the plugin gives it to me without a theme, so I requested it.
