### ISSUE TITLE
[TV SHOW]: ASSASSINS PRIDE (2019)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5389]
### Database URL

https://www.themoviedb.org/tv/91299

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=mLzo5gmPrAI

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
