### ISSUE TITLE
[TV SHOW]: Ayakashi Triangle (2023)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5391]
### Database URL

https://www.themoviedb.org/tv/153697

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=BcqDPAtPFG8

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
