### ISSUE TITLE
[TV SHOW]: Banished from the Hero's Party, I Decided to Live a Quiet Life in the Countryside (2021)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5392]
### Database URL

https://www.themoviedb.org/tv/113256

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=Rusgd3y1F5w

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
