### ISSUE TITLE
[TV SHOW]: Beast Tamer (2022)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5393]
### Database URL

https://www.themoviedb.org/tv/203780

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=6YoVGDsw2Lo

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
