### ISSUE TITLE
[TV SHOW]: Berserk of Gluttony (2023)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5395]
### Database URL

https://www.themoviedb.org/tv/213331

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=KaZkcxebysI

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
