### ISSUE TITLE
[TV SHOW]: Blade Dance of Elementalers (2014)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5397]
### Database URL

https://www.themoviedb.org/tv/61287

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=BNkJWRm4IoY

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
