### ISSUE TITLE
[TV SHOW]: Bottom-Tier Character Tomozaki (2021)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5399]
### Database URL

https://www.themoviedb.org/tv/99083

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=LbtFdf7pgA0

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
