### ISSUE TITLE
[TV SHOW]: Butareba -The Story of a Man Turned Into a Pig- (2023)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5400]
### Database URL

https://www.themoviedb.org/tv/153336

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=O_Th1vCb2UM

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
