### ISSUE TITLE
[TV SHOW]: By the Grace of the Gods (2020)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5401]
### Database URL

https://www.themoviedb.org/tv/102086

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=YvtHGcnMCQg

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
