### ISSUE TITLE
[TV SHOW]: Chillin' in Another World with Level 2 Super Cheat Powers (2024)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5403]
### Database URL

https://www.themoviedb.org/tv/237233

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=aRy6ucmZXXA

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
