### ISSUE TITLE
[TV SHOW]: Gushing Over Magical Girls (2024)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5405]
### Database URL

https://www.themoviedb.org/tv/236338

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=15ENTdUgBYY

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
