### ISSUE TITLE
[TV SHOW]: Xuan Yuan Sword Luminary (2018)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5407]
### Database URL

https://www.themoviedb.org/tv/82692

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=9aAj_lPNbQs

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
