### ISSUE TITLE
[TV SHOW]: The Demon Sword Master of Excalibur Academy (2023)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5408]
### Database URL

https://www.themoviedb.org/tv/136840

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=aL2QsRwx1Co

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
