### ISSUE TITLE
[TV SHOW]: Quality Assurance in Another World (2024)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5411]
### Database URL

https://www.themoviedb.org/tv/222925

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=dpiUQnnB3ok

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
