### ISSUE TITLE
[TV SHOW]: BARTENDER Glass of God (2024)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5412]
### Database URL

https://www.themoviedb.org/tv/225168

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=ifRNu3_lGBI

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
