### ISSUE TITLE
[TV SHOW]: The Vexations of a Shut-In Vampire Princess (2023)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5414]
### Database URL

https://www.themoviedb.org/tv/217755

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=eA_cqmJEuwo

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
