### ISSUE TITLE
[TV SHOW]: Vermeil in Gold (2022)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5416]
### Database URL

https://www.themoviedb.org/tv/194774

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=-jUrOSiTTgs

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
