### ISSUE TITLE
[TV SHOW]: Twisted Metal (2023)

### ISSUE THREAD

**Issue by rajvadranam** [LizardByte/ThemerrDB#5423]
### Database URL

https://www.themoviedb.org/tv/133748

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=5QNZ44zKzjo

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
A theme for this already exists or was submitted before yours. When replacing a theme in the future, please mark that you're replacing a theme and the reason for it in the submission.
