### ISSUE TITLE
[TV SHOW]: Arcane (2021)

### ISSUE THREAD

**Issue by SpaceEnergy** [LizardByte/ThemerrDB#5427]
### Database URL

https://www.themoviedb.org/tv/94605

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=cp0KO42YXf4

### Additional Information

- [X] This is a replacement request. If checked, please provide a reason below.

### Replacement Reason

even if there is already a title song it is shown as missing so i change the link

**Comment by jjnether** [comment]
@LizardByte-bot approve
