### ISSUE TITLE
[TV SHOW]: Baby Reindeer (2024)

### ISSUE THREAD

**Issue by RaianIE** [LizardByte/ThemerrDB#5430]
### Database URL

https://www.themoviedb.org/tv/241259

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=hcqnSdYDdgo&list=PLLv3qeuV3YDpHXmda4byjDgCbi7-LzO7N&index=1

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
