### ISSUE TITLE
[MOVIE]: Batman: Soul of the Dragon (2021)

### ISSUE THREAD

**Issue by RaianIE** [LizardByte/ThemerrDB#5431]
### Database URL

https://www.themoviedb.org/movie/732450

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=O5bBPkadUGc

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
