### ISSUE TITLE
[TV SHOW]: Batman: The Animated Series (1992)

### ISSUE THREAD

**Issue by RaianIE** [LizardByte/ThemerrDB#5432]
### Database URL

https://www.themoviedb.org/tv/2098

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=rrmUk2YUm14

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
