### ISSUE TITLE
[MOVIE]: The Forever Purge (2021)

### ISSUE THREAD

**Issue by CrowMash** [LizardByte/ThemerrDB#5433]
### Database URL

https://www.themoviedb.org/movie/602223

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=pqwSAmV2dAU

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
