### ISSUE TITLE
[MOVIE]: Arcadian (2024)

### ISSUE THREAD

**Issue by CrowMash** [LizardByte/ThemerrDB#5434]
### Database URL

https://www.themoviedb.org/movie/1051896

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=mNLGpKLPrlg

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
The video provided is a low bitrate with background noise. How does this song from the end credits work instead?

https://www.youtube.com/watch?v=mNLGpKLPrlg

**Comment by CrowMash** [comment]
Perfect!

**Comment by jjnether** [comment]
@LizardByte-bot edit https://www.youtube.com/watch?v=mNLGpKLPrlg

**Comment by jjnether** [comment]
@LizardByte-bot approve
