### ISSUE TITLE
[TV SHOW]: Avenue 5 (2020)

### ISSUE THREAD

**Issue by CrowMash** [LizardByte/ThemerrDB#5435]
### Database URL

https://www.themoviedb.org/tv/90811

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=MwV3-snrb0g

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
