### ISSUE TITLE
[TV SHOW]: Dopesick (2021)

### ISSUE THREAD

**Issue by CrowMash** [LizardByte/ThemerrDB#5441]
### Database URL

https://www.themoviedb.org/tv/110695

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=AN3ruyJxiZQ

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
