### ISSUE TITLE
[TV SHOW]: The Good Doctor (2017)

### ISSUE THREAD

**Issue by CrowMash** [LizardByte/ThemerrDB#5445]
### Database URL

https://www.themoviedb.org/tv/71712

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=sesHVJPXBTU

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
