### ISSUE TITLE
[TV SHOW]: Krypton (2018)

### ISSUE THREAD

**Issue by CrowMash** [LizardByte/ThemerrDB#5448]
### Database URL

https://www.themoviedb.org/tv/71340

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=VOC30X8sYtU

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
The video provided doesn't appear to be from the TV show. How does this song work instead?

**Comment by CrowMash** [comment]
Yes you're right! Maybe this video has better sound quality: https://www.youtube.com/watch?v=VOC30X8sYtU

**Comment by jjnether** [comment]
@LizardByte-bot edit https://www.youtube.com/watch?v=VOC30X8sYtU

**Comment by jjnether** [comment]
@LizardByte-bot approve
