### ISSUE TITLE
[TV SHOW]: Malcolm in the Middle (2000)

### ISSUE THREAD

**Issue by CrowMash** [LizardByte/ThemerrDB#5450]
### Database URL

https://www.themoviedb.org/tv/2004

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=ZtKqQNpFJCo

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
