### ISSUE TITLE
[TV SHOW]: Reginald the Vampire (2022)

### ISSUE THREAD

**Issue by CrowMash** [LizardByte/ThemerrDB#5454]
### Database URL

https://www.themoviedb.org/tv/155437

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=IqAC8gMiPCY

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
