### ISSUE TITLE
[TV SHOW]: Stargate Universe (2009)

### ISSUE THREAD

**Issue by CrowMash** [LizardByte/ThemerrDB#5457]
### Database URL

https://www.themoviedb.org/tv/5148

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=a7whz8DdeeQ

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
