### ISSUE TITLE
[TV SHOW]: Strange Planet (2023)

### ISSUE THREAD

**Issue by CrowMash** [LizardByte/ThemerrDB#5458]
### Database URL

https://www.themoviedb.org/tv/204358

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=Ki1W0wPtfR0

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
