### ISSUE TITLE
[TV SHOW]: Swamp Thing (2019)

### ISSUE THREAD

**Issue by CrowMash** [LizardByte/ThemerrDB#5459]
### Database URL

https://www.themoviedb.org/tv/79240

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=4IXDTnfkkEA

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
