### ISSUE TITLE
[TV SHOW]: The Last Man on Earth (2015)

### ISSUE THREAD

**Issue by CrowMash** [LizardByte/ThemerrDB#5460]
### Database URL

https://www.themoviedb.org/tv/61888

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=h5vcJAOzWqA

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
