### ISSUE TITLE
[TV SHOW]: 7th Heaven (1996)

### ISSUE THREAD

**Issue by OzZy02100** [LizardByte/ThemerrDB#5464]
### Database URL

https://www.themoviedb.org/tv/4550

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=FmznoPzzWfM

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
