### ISSUE TITLE
[TV SHOW]: American Crime Story (2016)

### ISSUE THREAD

**Issue by OzZy02100** [LizardByte/ThemerrDB#5465]
### Database URL

https://www.themoviedb.org/tv/64513

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=E7aZPGqW1sE

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
