### ISSUE TITLE
[TV SHOW]: American Pickers (2010)

### ISSUE THREAD

**Issue by OzZy02100** [LizardByte/ThemerrDB#5466]
### Database URL

https://www.themoviedb.org/tv/32025

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=Ef4iapDc8Mg

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
Please provide a theme for the TV show that does not include dialogue.

**Comment by OcifferAction** [comment]
No update provided. Closing issue.
