### ISSUE TITLE
[MOVIE]: Bloodsport (1988)

### ISSUE THREAD

**Issue by OzZy02100** [LizardByte/ThemerrDB#5467]
### Database URL

https://www.themoviedb.org/movie/11690

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=5QOmNwgcYWE

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
