### ISSUE TITLE
[TV SHOW]: Blue Bloods (2010)

### ISSUE THREAD

**Issue by OzZy02100** [LizardByte/ThemerrDB#5468]
### Database URL

https://www.themoviedb.org/tv/32692

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=zzmqITF6Tgk

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
