### ISSUE TITLE
[TV SHOW]: Dawson's Creek (1998)

### ISSUE THREAD

**Issue by OzZy02100** [LizardByte/ThemerrDB#5471]
### Database URL

https://www.themoviedb.org/tv/2327

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=izpNuTxGIrM

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
