### ISSUE TITLE
[TV SHOW]: Desperate Housewives (2004)

### ISSUE THREAD

**Issue by OzZy02100** [LizardByte/ThemerrDB#5472]
### Database URL

https://www.themoviedb.org/tv/693

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=5wxOXoLYeKs

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
