### ISSUE TITLE
[MOVIE]: Investigation of a Citizen Above Suspicion (1970)

### ISSUE THREAD

**Issue by OzZy02100** [LizardByte/ThemerrDB#5473]
### Database URL

https://www.themoviedb.org/movie/26451

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=_OyP2fQRSzI

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
