### ISSUE TITLE
[MOVIE]: The Exorcist (1973)

### ISSUE THREAD

**Issue by OzZy02100** [LizardByte/ThemerrDB#5476]
### Database URL

https://www.themoviedb.org/movie/9552

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=Hj83ugShbic

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
A theme for this already exists or was submitted before yours. When replacing a theme in the future, please mark that you're replacing a theme and the reason for it in the submission.
