### ISSUE TITLE
[TV SHOW]: The Pretender (1996)

### ISSUE THREAD

**Issue by OzZy02100** [LizardByte/ThemerrDB#5477]
### Database URL

https://www.themoviedb.org/tv/1706

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=P3dzIYcVgN4

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
