### ISSUE TITLE
[MOVIE]: The Simpsons Movie (2007)

### ISSUE THREAD

**Issue by ChilliSawse** [LizardByte/ThemerrDB#5482]
### Database URL

https://www.themoviedb.org/movie/35

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=Fttst9dG6Ko

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
A theme for this already exists or was submitted before yours. When replacing a theme in the future, please mark that you're replacing a theme and the reason for it in the submission.
