### ISSUE TITLE
[MOVIE]: Kingdom of the Planet of the Apes (2024)

### ISSUE THREAD

**Issue by warzook** [LizardByte/ThemerrDB#5483]
### Database URL

https://www.themoviedb.org/movie/653346

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=WC9gvJU2LLM

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
A theme for this already exists or was submitted before yours. When replacing a theme in the future, please mark that you're replacing a theme and the reason for it in the submission.
