### ISSUE TITLE
[MOVIE]: Kingdom of the Planet of the Apes (2024)

### ISSUE THREAD

**Issue by warzook** [LizardByte/ThemerrDB#5484]
### Database URL

https://www.themoviedb.org/movie/653346

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=myF0GvqltYY&t=10s

### Additional Information

- [X] This is a replacement request. If checked, please provide a reason below.

### Replacement Reason

theme Video unavailable

**Comment by jjnether** [comment]
@warzook the theme you gave is trailer music. Please pick a song from the actual movie
