### ISSUE TITLE
[TV SHOW]: CSI: Crime Scene Investigation (2000)

### ISSUE THREAD

**Issue by reun100e** [LizardByte/ThemerrDB#5486]
### Database URL

https://www.themoviedb.org/tv/1431

### YouTube Theme Song Video URL

https://youtu.be/KnATBxelyJE?si=w8v7oA-lChRTIgqW

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
