### ISSUE TITLE
[MOVIE]: Saw X (2023)

### ISSUE THREAD

**Issue by warzook** [LizardByte/ThemerrDB#5490]
### Database URL

https://www.themoviedb.org/movie/951491

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=CNxBhIS7YiU&list=RDCNxBhIS7YiU

### Additional Information

- [X] This is a replacement request. If checked, please provide a reason below.

### Replacement Reason

Video unavailable

**Comment by jjnether** [comment]
@warzook Theme is too long, please edit with a shorter one
