### ISSUE TITLE
[TV SHOW]: Classroom of the Elite (2017)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5494]
### Database URL

https://www.themoviedb.org/tv/72517

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=lOGwN-W1fpM

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
