### ISSUE TITLE
[TV SHOW]: Clockwork Planet (2017)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5495]
### Database URL

https://www.themoviedb.org/tv/70636

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=BjVHvEAaM_g

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
