### ISSUE TITLE
[TV SHOW]: Combatants Will Be Dispatched! (2021)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5496]
### Database URL

https://www.themoviedb.org/tv/100567

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=K-CodXtslc0

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
