### ISSUE TITLE
[MOVIE]: Gremlins 2: The New Batch (1990)

### ISSUE THREAD

**Issue by songochain** [LizardByte/ThemerrDB#5499]
### Database URL

https://www.themoviedb.org/movie/928

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=53uV5z4zEsc

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
Please refer to the [correct](https://github.com/LizardByte/ThemerrDB/blob/master/docs/YouTube_Share.md) YouTube video URLs. The link should be "https://www.youtube.com/watch?v=53uV5z4zEsc" Please update your link with the correct link.

**Comment by OcifferAction** [comment]
@LizardByte-bot edit https://www.youtube.com/watch?v=53uV5z4zEsc

**Comment by OcifferAction** [comment]
@LizardByte-bot edit https://www.youtube.com/watch?v=53uV5z4zEsc

**Comment by jjnether** [comment]
@LizardByte-bot edit https://www.youtube.com/watch?v=53uV5z4zEsc

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
