### ISSUE TITLE
[MOVIE]: Neon Genesis Evangelion: The End of Evangelion (1997)

### ISSUE THREAD

**Issue by Bundas18** [LizardByte/ThemerrDB#5501]
### Database URL

https://www.themoviedb.org/movie/18491

### YouTube Theme Song Video URL

https://youtu.be/6kguaGI7aZg

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
