### ISSUE TITLE
[MOVIE]: Spiral: From the Book of Saw (2021)

### ISSUE THREAD

**Issue by ryanjames122** [LizardByte/ThemerrDB#5505]
### Database URL

https://www.themoviedb.org/movie/602734

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=oJdq3QZTV8w

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
