### ISSUE TITLE
[MOVIE]: Klaus (2019)

### ISSUE THREAD

**Issue by LetsGoDude** [LizardByte/ThemerrDB#5507]
### Database URL

https://www.themoviedb.org/movie/508965-klaus

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=jT0Osp5tlvc

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
