### ISSUE TITLE
[MOVIE]: Perfect Days (2023)

### ISSUE THREAD

**Issue by LA208602-Gouthiere** [LizardByte/ThemerrDB#5510]
### Database URL

https://www.themoviedb.org/movie/976893

### YouTube Theme Song Video URL

https://youtu.be/SmQkv6wIYug

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
A theme already exists for this movie and since no replacement reason was listed I'm closing this as a duplicate.

**Comment by OcifferAction** [comment]
A theme already exists for this movie and since no replacement reason was listed I'm closing this as a duplicate.

**Comment by OcifferAction** [comment]
A theme already exists for this movie and since no replacement reason was listed I'm closing this as a duplicate.
