### ISSUE TITLE
[MOVIE]: Perfect Days (2023)

### ISSUE THREAD

**Issue by LA208602-Gouthiere** [LizardByte/ThemerrDB#5514]
### Database URL

https://www.themoviedb.org/movie/976893

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=SmQkv6wIYug

### Additional Information

- [X] This is a replacement request. If checked, please provide a reason below.

### Replacement Reason

This is the cover of Lou Reed - Perfect Day (the previous theme song) made for the movie.

**Comment by jjnether** [comment]
@LizardByte-bot approve
