### ISSUE TITLE
[MOVIE]: 24 Hours to Live (2017)

### ISSUE THREAD

**Issue by CrowMash** [LizardByte/ThemerrDB#5515]
### Database URL

https://www.themoviedb.org/movie/470114

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=PY8_gJlXJF8

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
