### ISSUE TITLE
[MOVIE]: An Adventure in Space and Time (2013)

### ISSUE THREAD

**Issue by minastiris** [LizardByte/ThemerrDB#5545]
### Database URL

https://www.themoviedb.org/movie/210024

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=YN7pCuNtO6Q&ab_channel=irkaiel

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
