### ISSUE TITLE
[MOVIE]: Bad Boys: Ride or Die (2024)

### ISSUE THREAD

**Issue by CrowMash** [LizardByte/ThemerrDB#5547]
### Database URL

https://www.themoviedb.org/movie/573435

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=Bu9tVwgKMiA

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
https://www.youtube.com/watch?v=Bu9tVwgKMiA
