### ISSUE TITLE
[MOVIE]: Battle Royale II: Requiem (2003)

### ISSUE THREAD

**Issue by CrowMash** [LizardByte/ThemerrDB#5548]
### Database URL

https://www.themoviedb.org/movie/3177

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=pE3-YkIL6NA

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
