### ISSUE TITLE
[MOVIE]: Boyz n the Hood (1991)

### ISSUE THREAD

**Issue by CrowMash** [LizardByte/ThemerrDB#5551]
### Database URL

https://www.themoviedb.org/movie/650

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=7_-eabvlMzI

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
