### ISSUE TITLE
[MOVIE]: My Best Friend's Girl (1983)

### ISSUE THREAD

**Issue by zdimension** [LizardByte/ThemerrDB#5558]
### Database URL

https://www.themoviedb.org/movie/64504

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=uwCHRw_38C4

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
