### ISSUE TITLE
[MOVIE]: The Family (2013)

### ISSUE THREAD

**Issue by HomerBeer** [LizardByte/ThemerrDB#5616]
### Database URL

https://www.themoviedb.org/movie/112205

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=bDA1VCHh4l0&list=OLAK5uy_mV8rkRlFXBpLr-JDv3y_asaNB19dQJ6VI

### Additional Information

- [X] This is a replacement request. If checked, please provide a reason below.

### Replacement Reason

The other one is private

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
