### ISSUE TITLE
[MOVIE]: Above the Shadows (2019)

### ISSUE THREAD

**Issue by HomerBeer** [LizardByte/ThemerrDB#5623]
### Database URL

https://www.themoviedb.org/movie/609734

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=orcRx8s9-JA

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
