### ISSUE TITLE
[MOVIE]: After Everything (2023)

### ISSUE THREAD

**Issue by HomerBeer** [LizardByte/ThemerrDB#5636]
### Database URL

https://www.themoviedb.org/movie/820525

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=IOT7TYulzow&list=PLLv3qeuV3YDorm-7R_kMmZbrAXtd3pB6F

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
