### ISSUE TITLE
[MOVIE]: Air Force One Down (2024)

### ISSUE THREAD

**Issue by HomerBeer** [LizardByte/ThemerrDB#5644]
### Database URL

https://www.themoviedb.org/movie/1124127

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=iDyn2IVMFJU

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
