### ISSUE TITLE
[MOVIE]: All of Us Strangers (2023)

### ISSUE THREAD

**Issue by HomerBeer** [LizardByte/ThemerrDB#5645]
### Database URL

https://www.themoviedb.org/movie/994108

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=zgB8JNl51eM

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
