### ISSUE TITLE
[MOVIE]: All the Old Knives (2022)

### ISSUE THREAD

**Issue by HomerBeer** [LizardByte/ThemerrDB#5647]
### Database URL

https://www.themoviedb.org/movie/294793

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=MvbDGH5vmOM

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
