### ISSUE TITLE
[MOVIE]: Am I OK? (2024)

### ISSUE THREAD

**Issue by HomerBeer** [LizardByte/ThemerrDB#5649]
### Database URL

https://www.themoviedb.org/movie/641934

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=pB08AUiTP3w&list=PLEVH-6-s-tVUka4KQpU0rgS54FK0MKCGI

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
