### ISSUE TITLE
[MOVIE]: American Dreamer (2022)

### ISSUE THREAD

**Issue by HomerBeer** [LizardByte/ThemerrDB#5653]
### Database URL

https://www.themoviedb.org/movie/931461

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=cQ-fqWcQ6gI

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
The song provided is from the trailer and we try to avoid using trailer music for themes. How does this video from the original score work instead?

https://www.youtube.com/watch?v=cQ-fqWcQ6gI

**Comment by HomerBeer** [comment]
Ah yes, you are right. That one works great, good one. Thanx!

**Comment by OcifferAction** [comment]
@LizardByte-bot edit https://www.youtube.com/watch?v=cQ-fqWcQ6gI

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
