### ISSUE TITLE
[TV SHOW]: Everybody Loves Raymond (1996)

### ISSUE THREAD

**Issue by iNfRaS0NiC** [LizardByte/ThemerrDB#5673]
### Database URL

https://www.themoviedb.org/tv/2140

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=6uD60H_rD1g

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
