### ISSUE TITLE
[MOVIE]: National Lampoon's Loaded Weapon 1 (1993)

### ISSUE THREAD

**Issue by KyleIH** [LizardByte/ThemerrDB#5714]
### Database URL

https://www.themoviedb.org/movie/9644

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=rgZpHiwTzi0

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
