### ISSUE TITLE
[MOVIE]: The Map of Tiny Perfect Things (2021)

### ISSUE THREAD

**Issue by KyleIH** [LizardByte/ThemerrDB#5715]
### Database URL

https://www.themoviedb.org/movie/672647

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=qFXrfxjDOis

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
