### ISSUE TITLE
[MOVIE]: The Naked Gun 2½: The Smell of Fear (1991)

### ISSUE THREAD

**Issue by KyleIH** [LizardByte/ThemerrDB#5716]
### Database URL

https://www.themoviedb.org/movie/37137

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=P9eQ7CLgOBY

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
