### ISSUE TITLE
[MOVIE]: Palm Springs (2020)

### ISSUE THREAD

**Issue by KyleIH** [LizardByte/ThemerrDB#5717]
### Database URL

https://www.themoviedb.org/movie/587792

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=fzSrU3TeJ4Y

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
