### ISSUE TITLE
[MOVIE]: Alice, Darling (2022)

### ISSUE THREAD

**Issue by sean6789** [LizardByte/ThemerrDB#5721]
### Database URL

https://www.themoviedb.org/movie/850028

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=Y3GWsTq6GRU

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
