### ISSUE TITLE
[MOVIE]: 5 Centimeters per Second (2007)

### ISSUE THREAD

**Issue by alsoGAMER** [LizardByte/ThemerrDB#5725]
### Database URL

https://www.themoviedb.org/movie/38142-5

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=cFtAEFCSxzg

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
Theme is already available in the database and no replacement reason was listed. Closing as duplicate.

**Comment by alsoGAMER** [comment]
i figured but... 
![image](https://github.com/user-attachments/assets/4417e8bb-97b1-4824-9c6e-cdced40f28ae)

**Comment by ReenigneArcher** [comment]
There's probably another reason it's not showing as available for you.

**Comment by alsoGAMER** [comment]
> maybe a geo-restriction

at which front?
also, is there a way for me to test for that?

**Comment by ReenigneArcher** [comment]
Well you can access GitHub (hosts our database), so it would have to be YouTube.

Maybe: https://watannetwork.com/tools/blocked/#url=e8X_bUyrUfg but according to this it's not geo-resticted. Could be something else. Impossible to know without logs. I'd suggest opening a post on our discord server.

**Comment by alsoGAMER** [comment]
Done, thank you
