### ISSUE TITLE
[MOVIE]: Belle (2021)

### ISSUE THREAD

**Issue by alsoGAMER** [LizardByte/ThemerrDB#5726]
### Database URL

https://www.themoviedb.org/movie/776305

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=R3V4sAXUJ-g

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
Theme is already available in the database and no replacement reason was listed. Closing as duplicate.

**Comment by alsoGAMER** [comment]
same as #5725
