### ISSUE TITLE
[MOVIE]: Evangelion: 1.0 You Are (Not) Alone (2007)

### ISSUE THREAD

**Issue by alsoGAMER** [LizardByte/ThemerrDB#5727]
### Database URL

https://www.themoviedb.org/movie/15137

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=AsE-DwCmlPM

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by alsoGAMER** [comment]
youtube bruh moment
this one works https://www.youtube.com/watch?v=AsE-DwCmlPM

**Comment by OcifferAction** [comment]
@LizardByte-bot edit https://www.youtube.com/watch?v=AsE-DwCmlPM

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
