### ISSUE TITLE
[MOVIE]: Evangelion: 3.0+1.0 Thrice Upon a Time (2021)

### ISSUE THREAD

**Issue by alsoGAMER** [LizardByte/ThemerrDB#5729]
### Database URL

https://www.themoviedb.org/movie/283566

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=0Dq2FTMnqX4

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
