### ISSUE TITLE
[MOVIE]: Evangelion: 3.0 You Can (Not) Redo (2012)

### ISSUE THREAD

**Issue by alsoGAMER** [LizardByte/ThemerrDB#5730]
### Database URL

https://www.themoviedb.org/movie/75629

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=P7Hx0GYIs4k

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
