### ISSUE TITLE
[MOVIE]: The Boy and the Heron (2023)

### ISSUE THREAD

**Issue by alsoGAMER** [LizardByte/ThemerrDB#5734]
### Database URL

https://www.themoviedb.org/movie/508883

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=abKcYyQ1V7Y

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
Theme is already available in the database and no replacement reason was listed. Closing as duplicate.

**Comment by alsoGAMER** [comment]
same as #5725
