### ISSUE TITLE
[MOVIE]: Angel's Egg (1985)

### ISSUE THREAD

**Issue by alsoGAMER** [LizardByte/ThemerrDB#5735]
### Database URL

https://www.themoviedb.org/movie/15916

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=0Fsb1OBpCN0

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by alsoGAMER** [comment]
full playlist here: https://www.youtube.com/watch?v=0Fsb1OBpCN0&list=PLc51OvsgwphmKWNJhyK4CLvIxDqh8bJ_v&index=3

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
