### ISSUE TITLE
[MOVIE]: Pompo the Cinephile (2021)

### ISSUE THREAD

**Issue by alsoGAMER** [LizardByte/ThemerrDB#5737]
### Database URL

https://www.themoviedb.org/movie/678458

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=KD14CW-j2sA

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
