### ISSUE TITLE
[TV SHOW]: Akiba Maid War (2022)

### ISSUE THREAD

**Issue by NeoKnux** [LizardByte/ThemerrDB#5741]
### Database URL

https://www.themoviedb.org/tv/204716

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=jxN-HbcE0XQ

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
