### ISSUE TITLE
[TV SHOW]: Baby Steps (2014)

### ISSUE THREAD

**Issue by NeoKnux** [LizardByte/ThemerrDB#5742]
### Database URL

https://www.themoviedb.org/tv/60844

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=gmbjqe9g7g0

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
