### ISSUE TITLE
[TV SHOW]: The Banished Former Hero Lives as He Pleases (2024)

### ISSUE THREAD

**Issue by NeoKnux** [LizardByte/ThemerrDB#5743]
### Database URL

https://www.themoviedb.org/tv/229108

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=dJTUWqL23cg

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
