### ISSUE TITLE
[MOVIE]: Weathering with You (2019)

### ISSUE THREAD

**Issue by alsoGAMER** [LizardByte/ThemerrDB#5745]
### Database URL

https://www.themoviedb.org/movie/568160

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=4YBNqNPjVM0

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
Theme is already available in the database and no replacement reason was listed. Closing as duplicate.

**Comment by alsoGAMER** [comment]
same as #5725
