### ISSUE TITLE
[TV SHOW]: El-Hazard: The Magnificent World (1995)

### ISSUE THREAD

**Issue by NeoKnux** [LizardByte/ThemerrDB#5747]
### Database URL

https://www.themoviedb.org/tv/44775

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=_AjIjBFx90U

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
