### ISSUE TITLE
[TV SHOW]: El-Hazard: The Wanderers (1995)

### ISSUE THREAD

**Issue by NeoKnux** [LizardByte/ThemerrDB#5748]
### Database URL

https://www.themoviedb.org/tv/22098

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=hDwgBtKLmqo

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
