### ISSUE TITLE
[MOVIE]: Revue Starlight: The Movie (2021)

### ISSUE THREAD

**Issue by alsoGAMER** [LizardByte/ThemerrDB#5749]
### Database URL

https://www.themoviedb.org/movie/645440

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=CBaWQxBuxe0

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
Video provided is too long, please edit your original link with a shorter video.

**Comment by alsoGAMER** [comment]
is this one ok? https://www.youtube.com/watch?v=CBaWQxBuxe0

**Comment by OcifferAction** [comment]
> is this one ok? https://www.youtube.com/watch?v=CBaWQxBuxe0

Perfect, thanks

**Comment by OcifferAction** [comment]
@LizardByte-bot edit https://www.youtube.com/watch?v=CBaWQxBuxe0

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
