### ISSUE TITLE
[TV SHOW]: Final Fantasy: Unlimited (2001)

### ISSUE THREAD

**Issue by NeoKnux** [LizardByte/ThemerrDB#5750]
### Database URL

https://www.themoviedb.org/tv/11316

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=R5KDSkuLl14

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
