### ISSUE TITLE
[MOVIE]: Revue Starlight: Rondo Rondo Rondo (2020)

### ISSUE THREAD

**Issue by alsoGAMER** [LizardByte/ThemerrDB#5752]
### Database URL

https://www.themoviedb.org/movie/645439

### YouTube Theme Song Video URL

https://youtu.be/b7AR9yrYrvo

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
