### ISSUE TITLE
[TV SHOW]: Final Fantasy: Legend of the Crystals (1994)

### ISSUE THREAD

**Issue by NeoKnux** [LizardByte/ThemerrDB#5754]
### Database URL

https://www.themoviedb.org/tv/67037

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=VprZLQ_B5kE

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
