### ISSUE TITLE
[TV SHOW]: Gundam Build Divers (2018)

### ISSUE THREAD

**Issue by NeoKnux** [LizardByte/ThemerrDB#5755]
### Database URL

https://www.themoviedb.org/tv/76821

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=C11p0Ny6gSY

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
