### ISSUE TITLE
[TV SHOW]: From Me to You: Kimi ni Todoke (2009)

### ISSUE THREAD

**Issue by alsoGAMER** [LizardByte/ThemerrDB#5756]
### Database URL

https://www.themoviedb.org/tv/68854-kimi-ni-todoke

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=h8WpL3TJSDQ

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by alsoGAMER** [comment]
song release: https://www.youtube.com/watch?v=h8WpL3TJSDQ

**Comment by OcifferAction** [comment]
@LizardByte-bot edit https://www.youtube.com/watch?v=h8WpL3TJSDQ

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
