### ISSUE TITLE
[TV SHOW]: Gundam Build Fighters (2013)

### ISSUE THREAD

**Issue by NeoKnux** [LizardByte/ThemerrDB#5757]
### Database URL

https://www.themoviedb.org/tv/60667

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=no7ecRAOscU

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
