### ISSUE TITLE
[TV SHOW]: Gundam Build Metaverse (2023)

### ISSUE THREAD

**Issue by NeoKnux** [LizardByte/ThemerrDB#5758]
### Database URL

https://www.themoviedb.org/tv/229606

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=b5O9j2uYOLU

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
