### ISSUE TITLE
[TV SHOW]: Showa Genroku Rakugo Shinju (2016)

### ISSUE THREAD

**Issue by alsoGAMER** [LizardByte/ThemerrDB#5759]
### Database URL

https://www.themoviedb.org/tv/66862-showa-genroku-rakugo-shinju

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=iSUx8PjWB8c

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
