### ISSUE TITLE
[TV SHOW]: Gundam Build Real (2021)

### ISSUE THREAD

**Issue by NeoKnux** [LizardByte/ThemerrDB#5760]
### Database URL

https://www.themoviedb.org/tv/127786

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=uRSvcUozBOc

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
