### ISSUE TITLE
[TV SHOW]: GUNDAM EVOLVE (2003)

### ISSUE THREAD

**Issue by NeoKnux** [LizardByte/ThemerrDB#5761]
### Database URL

https://www.themoviedb.org/tv/101719

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=cOHhiKJYDTo

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
