### ISSUE TITLE
[TV SHOW]: FLCL (2000)

### ISSUE THREAD

**Issue by alsoGAMER** [LizardByte/ThemerrDB#5763]
### Database URL

https://www.themoviedb.org/tv/5895-flcl

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=9cC8Q8RAEso

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
