### ISSUE TITLE
[TV SHOW]: Flip Flappers (2016)

### ISSUE THREAD

**Issue by alsoGAMER** [LizardByte/ThemerrDB#5764]
### Database URL

https://www.themoviedb.org/tv/68272

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=Es_jAYigpII

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
