### ISSUE TITLE
[TV SHOW]: Revue Starlight (2018)

### ISSUE THREAD

**Issue by alsoGAMER** [LizardByte/ThemerrDB#5766]
### Database URL

https://www.themoviedb.org/tv/80834

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=CBda5UCtFjs

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
