### ISSUE TITLE
[TV SHOW]: Penguindrum (2011)

### ISSUE THREAD

**Issue by alsoGAMER** [LizardByte/ThemerrDB#5767]
### Database URL

https://www.themoviedb.org/tv/39657

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=ux5E1h1n1-c

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
