### ISSUE TITLE
[TV SHOW]: Nagi-Asu: A Lull in the Sea (2013)

### ISSUE THREAD

**Issue by alsoGAMER** [LizardByte/ThemerrDB#5769]
### Database URL

https://www.themoviedb.org/tv/61408-nagi-no-asukara

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=mMQKvHRddJo

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
