### ISSUE TITLE
[TV SHOW]: Noein: To Your Other Self (2005)

### ISSUE THREAD

**Issue by alsoGAMER** [LizardByte/ThemerrDB#5770]
### Database URL

https://www.themoviedb.org/tv/9041-noein

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=Pl0Saxnj9eQ

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
