### ISSUE TITLE
[MOVIE]: One Piece Film Red (2022)

### ISSUE THREAD

**Issue by alsoGAMER** [LizardByte/ThemerrDB#5771]
### Database URL

https://www.themoviedb.org/movie/900667-one-piece-film-red

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=ViOzYSYWCMM

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
Theme is already available in the database and no replacement reason was listed. Closing as duplicate.

**Comment by OcifferAction** [comment]
Theme is already available in the database and no replacement reason was listed. Closing as duplicate.

**Comment by alsoGAMER** [comment]
same as #5725
