### ISSUE TITLE
[TV SHOW]: Princess Tutu (2002)

### ISSUE THREAD

**Issue by alsoGAMER** [LizardByte/ThemerrDB#5772]
### Database URL

https://www.themoviedb.org/tv/34132-princess-tutu

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=tITsAJE-X7A

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
