### ISSUE TITLE
[TV SHOW]: Gurren Lagann (2007)

### ISSUE THREAD

**Issue by alsoGAMER** [LizardByte/ThemerrDB#5773]
### Database URL

https://www.themoviedb.org/tv/21729

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=svO1L1uIxjM

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
