### ISSUE TITLE
[TV SHOW]: Tengoku Daimakyo (2023)

### ISSUE THREAD

**Issue by alsoGAMER** [LizardByte/ThemerrDB#5774]
### Database URL

https://www.themoviedb.org/tv/208891

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=Z83mEbMJ_zk

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
