### ISSUE TITLE
[TV SHOW]: The Elusive Samurai (2024)

### ISSUE THREAD

**Issue by alsoGAMER** [LizardByte/ThemerrDB#5775]
### Database URL

https://www.themoviedb.org/tv/222623-the-elusive-samurai

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=k2fOCQEHpVA

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
