### ISSUE TITLE
[TV SHOW]: The Magical Girl and the Evil Lieutenant Used to Be Archenemies (2024)

### ISSUE THREAD

**Issue by alsoGAMER** [LizardByte/ThemerrDB#5776]
### Database URL

https://www.themoviedb.org/tv/239764-katsute-mahou-shoujo-to-aku-wa-tekitai-shite-ita

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=wG8_0zwkOME

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
