### ISSUE TITLE
[TV SHOW]: YATAGARASU: The Raven Does Not Choose Its Master (2024)

### ISSUE THREAD

**Issue by alsoGAMER** [LizardByte/ThemerrDB#5777]
### Database URL

https://www.themoviedb.org/tv/243141

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=_EFWxbDtl-g

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@LizardByte-bot approve
