### ISSUE TITLE
[MOVIE]: Digimon Adventure 02: The Beginning (2023)

### ISSUE THREAD

**Issue by alsoGAMER** [LizardByte/ThemerrDB#5778]
### Database URL

https://www.themoviedb.org/movie/872976-02-the-beginning

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=a6CSA_iO9q0

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
