### ISSUE TITLE
[TV SHOW]: Puella Magi Madoka Magica (2011)

### ISSUE THREAD

**Issue by alsoGAMER** [LizardByte/ThemerrDB#5779]
### Database URL

https://www.themoviedb.org/tv/39218-puella-magi-madoka-magica

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=ADIP3Um32Gc

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
