### ISSUE TITLE
[MOVIE]: Puella Magi Madoka Magica the Movie Part I: Beginnings (2012)

### ISSUE THREAD

**Issue by alsoGAMER** [LizardByte/ThemerrDB#5780]
### Database URL

https://www.themoviedb.org/movie/152042

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=FXakcMAZpBM

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
