### ISSUE TITLE
[MOVIE]: Puella Magi Madoka Magica the Movie Part III: Rebellion (2013)

### ISSUE THREAD

**Issue by alsoGAMER** [LizardByte/ThemerrDB#5782]
### Database URL

https://www.themoviedb.org/movie/212162

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=NWK7R45gfl0

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
