### ISSUE TITLE
[TV SHOW]: The Highschool Life of a Fudanshi (2016)

### ISSUE THREAD

**Issue by NeoKnux** [LizardByte/ThemerrDB#5783]
### Database URL

https://www.themoviedb.org/tv/67013

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=YrAni2QPHkk

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
