### ISSUE TITLE
[TV SHOW]: Hitorijime My Hero (2017)

### ISSUE THREAD

**Issue by NeoKnux** [LizardByte/ThemerrDB#5784]
### Database URL

https://www.themoviedb.org/tv/72526

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=pgQsGCAIe2g

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
