### ISSUE TITLE
[TV SHOW]: Insomniacs After School (2023)

### ISSUE THREAD

**Issue by NeoKnux** [LizardByte/ThemerrDB#5785]
### Database URL

https://www.themoviedb.org/tv/155440

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=j0dQmivkJTw

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
