### ISSUE TITLE
[TV SHOW]: KONOSUBA – An Explosion on This Wonderful World! (2023)

### ISSUE THREAD

**Issue by NeoKnux** [LizardByte/ThemerrDB#5786]
### Database URL

https://www.themoviedb.org/tv/203040

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=IfiQMJ3QlG4

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
