### ISSUE TITLE
[TV SHOW]: Lupin the Third: The Woman Called Fujiko Mine (2012)

### ISSUE THREAD

**Issue by NeoKnux** [LizardByte/ThemerrDB#5787]
### Database URL

https://www.themoviedb.org/tv/45860

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=Kqyx-1oaksE

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
