### ISSUE TITLE
[TV SHOW]: LUPIN ZERO (2022)

### ISSUE THREAD

**Issue by NeoKnux** [LizardByte/ThemerrDB#5788]
### Database URL

https://www.themoviedb.org/tv/213044

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=V6pqP_HuuTw

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
