### ISSUE TITLE
[TV SHOW]: Mission: Yozakura Family (2024)

### ISSUE THREAD

**Issue by NeoKnux** [LizardByte/ThemerrDB#5790]
### Database URL

https://www.themoviedb.org/tv/216467

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=0NQ5NYjPr9U

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
