### ISSUE TITLE
[TV SHOW]: Mobile Suit Gundam SEED C.E.73 -STARGAZER- (2006)

### ISSUE THREAD

**Issue by NeoKnux** [LizardByte/ThemerrDB#5791]
### Database URL

https://www.themoviedb.org/tv/43142

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=r0B0Kl_25AM

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
