### ISSUE TITLE
[TV SHOW]: Mobile Suit Gundam: The Origin - Advent of the Red Comet (2019)

### ISSUE THREAD

**Issue by NeoKnux** [LizardByte/ThemerrDB#5792]
### Database URL

https://www.themoviedb.org/tv/88865

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=P4wy9lr0Fjw

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
