### ISSUE TITLE
[TV SHOW]: Model Suit Gunpla Builders Beginning G (2010)

### ISSUE THREAD

**Issue by NeoKnux** [LizardByte/ThemerrDB#5793]
### Database URL

https://www.themoviedb.org/tv/45148

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=RoBpLtfDf1M

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
