### ISSUE TITLE
[TV SHOW]: Otaku Elf (2023)

### ISSUE THREAD

**Issue by NeoKnux** [LizardByte/ThemerrDB#5795]
### Database URL

https://www.themoviedb.org/tv/204112

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=c8mJrbYdMWw

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
