### ISSUE TITLE
[TV SHOW]: Re:Monster (2024)

### ISSUE THREAD

**Issue by NeoKnux** [LizardByte/ThemerrDB#5796]
### Database URL

https://www.themoviedb.org/tv/235389

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=dr2akE4Ei50

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
