### ISSUE TITLE
[TV SHOW]: Sasaki and Miyano (2022)

### ISSUE THREAD

**Issue by NeoKnux** [LizardByte/ThemerrDB#5797]
### Database URL

https://www.themoviedb.org/tv/127549

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=k6Z9chmXIxE

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
