### ISSUE TITLE
[TV SHOW]: A Sign of Affection (2024)

### ISSUE THREAD

**Issue by NeoKnux** [LizardByte/ThemerrDB#5798]
### Database URL

https://www.themoviedb.org/tv/230059

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=OfAnMY7ALE4

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
