### ISSUE TITLE
[TV SHOW]: Starship Troopers (1988)

### ISSUE THREAD

**Issue by NeoKnux** [LizardByte/ThemerrDB#5800]
### Database URL

https://www.themoviedb.org/tv/79334

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=bkXeMAYmuvo

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
