### ISSUE TITLE
[TV SHOW]: Tadaima, Okaeri (2024)

### ISSUE THREAD

**Issue by NeoKnux** [LizardByte/ThemerrDB#5801]
### Database URL

https://www.themoviedb.org/tv/235978

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=ZaasZ4-_KUI

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
