### ISSUE TITLE
[TV SHOW]: Urusei Yatsura (2022)

### ISSUE THREAD

**Issue by NeoKnux** [LizardByte/ThemerrDB#5804]
### Database URL

https://www.themoviedb.org/tv/154524

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=3QH4N6g0EYo

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
