### ISSUE TITLE
[TV SHOW]: Vampire Dormitory (2024)

### ISSUE THREAD

**Issue by NeoKnux** [LizardByte/ThemerrDB#5805]
### Database URL

https://www.themoviedb.org/tv/238903

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=X4n-SPH6GHk

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
