### ISSUE TITLE
[TV SHOW]: Zoids: Genesis (2005)

### ISSUE THREAD

**Issue by NeoKnux** [LizardByte/ThemerrDB#5806]
### Database URL

https://www.themoviedb.org/tv/45143

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=a8jzMhseSsk

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
