### ISSUE TITLE
[TV SHOW]: Zoids: Fuzors (2004)

### ISSUE THREAD

**Issue by NeoKnux** [LizardByte/ThemerrDB#5808]
### Database URL

https://www.themoviedb.org/tv/34769

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=u6J0U7AlVZE

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
