### ISSUE TITLE
[TV SHOW]: Zoids: New Century (2001)

### ISSUE THREAD

**Issue by NeoKnux** [LizardByte/ThemerrDB#5809]
### Database URL

https://www.themoviedb.org/tv/29540

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=9gFat9NeK5w

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
