### ISSUE TITLE
[MOVIE COLLECTION]: Dragon Ball Collection

### ISSUE THREAD

**Issue by NeoKnux** [LizardByte/ThemerrDB#5810]
### Database URL

https://www.themoviedb.org/collection/386410

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=VyaKCN5rljw

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
