### ISSUE TITLE
[MOVIE COLLECTION]: One Piece Collection

### ISSUE THREAD

**Issue by NeoKnux** [LizardByte/ThemerrDB#5811]
### Database URL

https://www.themoviedb.org/collection/23456

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=_wFSkyR0XO0

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
