### ISSUE TITLE
[MOVIE]: Ghidorah, the Three-Headed Monster (1964)

### ISSUE THREAD

**Issue by weatherluvr** [LizardByte/ThemerrDB#5815]
### Database URL

https://www.themoviedb.org/movie/15766

### YouTube Theme Song Video URL

https://youtu.be/2bjv4hFCseY?si=_O2_ChDjKznFbLr6

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
