### ISSUE TITLE
[MOVIE]: Godzilla vs. Hedorah (1971)

### ISSUE THREAD

**Issue by weatherluvr** [LizardByte/ThemerrDB#5817]
### Database URL

https://www.themoviedb.org/movie/39464

### YouTube Theme Song Video URL

https://youtu.be/SwlEfC-tfCU?si=hR2qs3VpmVLEWIY0

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
