### ISSUE TITLE
[MOVIE]: Invasion of Astro-Monster (1965)

### ISSUE THREAD

**Issue by weatherluvr** [LizardByte/ThemerrDB#5818]
### Database URL

https://www.themoviedb.org/movie/19545

### YouTube Theme Song Video URL

https://youtu.be/XMkEXULdvTo?si=jMl0PitySMJqsCRr

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
