### ISSUE TITLE
[MOVIE]: King Kong vs. Godzilla (1962)

### ISSUE THREAD

**Issue by weatherluvr** [LizardByte/ThemerrDB#5819]
### Database URL

https://www.themoviedb.org/movie/1680

### YouTube Theme Song Video URL

https://youtu.be/l5TxOq2Bx3Y?si=fEEU741EiQ0A3-32

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
