### ISSUE TITLE
[MOVIE]: Mothra (1961)

### ISSUE THREAD

**Issue by weatherluvr** [LizardByte/ThemerrDB#5822]
### Database URL

https://www.themoviedb.org/movie/39410

### YouTube Theme Song Video URL

https://youtu.be/eC6t7JeFuDw?si=KSsDfJU6Lv4P0111

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
