### ISSUE TITLE
[MOVIE]: Son of Godzilla (1967)

### ISSUE THREAD

**Issue by weatherluvr** [LizardByte/ThemerrDB#5823]
### Database URL

https://www.themoviedb.org/movie/18627

### YouTube Theme Song Video URL

https://youtu.be/MYN3QrRX7zI?si=0VDedDuYtStKhhhv

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
