### ISSUE TITLE
[TV SHOW]: The Newsroom (2012)

### ISSUE THREAD

**Issue by weatherluvr** [LizardByte/ThemerrDB#5824]
### Database URL

https://www.themoviedb.org/tv/15621

### YouTube Theme Song Video URL

https://youtu.be/OeRLOOEYrSw?si=x0QlVoOviXEUoweH

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
