### ISSUE TITLE
[TV SHOW]: X-Men (1992)

### ISSUE THREAD

**Issue by weatherluvr** [LizardByte/ThemerrDB#5825]
### Database URL

https://www.themoviedb.org/tv/4574

### YouTube Theme Song Video URL

https://youtu.be/di6DocEkruk?si=h3KFnrglbL8w2L8H

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
