### ISSUE TITLE
[TV SHOW]: RIPLEY (2024)

### ISSUE THREAD

**Issue by RJSkudra** [LizardByte/ThemerrDB#5826]
### Database URL

https://www.themoviedb.org/tv/94028

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=MKKX8Hw2FzE

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
