### ISSUE TITLE
[MOVIE]: Star Wars: The Clone Wars (2008)

### ISSUE THREAD

**Issue by RJSkudra** [LizardByte/ThemerrDB#5827]
### Database URL

https://www.themoviedb.org/movie/12180

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=RM0sSV1DNsM

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
