### ISSUE TITLE
[TV SHOW]: The Decameron (2024)

### ISSUE THREAD

**Issue by jj3005** [LizardByte/ThemerrDB#5829]
### Database URL

https://www.themoviedb.org/tv/250162

### YouTube Theme Song Video URL

https://www.youtube.com/watch?app=desktop&v=4AsPkRwNwRk

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot edit https://www.youtube.com/watch?app=desktop&v=4AsPkRwNwRk

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
