### ISSUE TITLE
[MOVIE]: Guardians of the Galaxy Vol. 3 (2023)

### ISSUE THREAD

**Issue by HomerBeer** [LizardByte/ThemerrDB#5832]
### Database URL

https://www.themoviedb.org/movie/447365

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=gdOGgFXqxLw

### Additional Information

- [X] This is a replacement request. If checked, please provide a reason below.

### Replacement Reason

Video not available anymore

**Comment by jjnether** [comment]
@LizardByte-bot approve
