### ISSUE TITLE
[MOVIE]: American Hustle (2013)

### ISSUE THREAD

**Issue by HomerBeer** [LizardByte/ThemerrDB#5833]
### Database URL

https://www.themoviedb.org/movie/168672

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=sCgwFg6ti0c

### Additional Information

- [X] This is a replacement request. If checked, please provide a reason below.

### Replacement Reason

Video not available

**Comment by jjnether** [comment]
A theme for this already exists or was submitted before yours. When replacing a theme in the future, please mark that you're replacing a theme and the reason for it in the submission.

**Comment by jjnether** [comment]
@LizardByte-bot approve
