### ISSUE TITLE
[TV SHOW]: Hi Score Girl (2018)

### ISSUE THREAD

**Issue by NeoKnux** [LizardByte/ThemerrDB#5834]
### Database URL

https://www.themoviedb.org/tv/80665

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=Tbu_7WtAjU8

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
