### ISSUE TITLE
[MOVIE]: After Ever Happy (2022)

### ISSUE THREAD

**Issue by HomerBeer** [LizardByte/ThemerrDB#5835]
### Database URL

https://www.themoviedb.org/movie/744276

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=eFI0DBIlt_U

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
