### ISSUE TITLE
[MOVIE]: Army of Thieves (2021)

### ISSUE THREAD

**Issue by HomerBeer** [LizardByte/ThemerrDB#5837]
### Database URL

https://www.themoviedb.org/movie/796499

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=cPw6Q73bJAk

### Additional Information

- [x] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
@HomerBeer Video is not available in US, please change to a different one

**Comment by HomerBeer** [comment]
https://m.youtube.com/watch?v=cPw6Q73bJAk&pp=ygUmaGFucyB6aW1tZXIgYXJteSBvZiB0aGlldmVzIHNvdW5kdHJhY2s%3D

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
