### ISSUE TITLE
[MOVIE]: A Time to Kill (1996)

### ISSUE THREAD

**Issue by sean6789** [LizardByte/ThemerrDB#5849]
### Database URL

https://www.themoviedb.org/movie/1645

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=olYFq9CTZ4w&list=PLN96aN59_v5ds4NbAUp8NwWNbBAnhpLy9&index=1

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
