### ISSUE TITLE
[MOVIE]: Angel Heart (1987)

### ISSUE THREAD

**Issue by sean6789** [LizardByte/ThemerrDB#5852]
### Database URL

https://www.themoviedb.org/movie/635

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=Io0iLkFi1gI

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
The video provided is too long. How does this one work instead?

https://www.youtube.com/watch?v=iQnNUYiClzA

**Comment by sean6789** [comment]
That one is great! For future reference, what is the time limit, or size limit, for submitted songs?

**Comment by OcifferAction** [comment]
> That one is great! For future reference, what is the time limit, or size limit, for submitted songs?

All theme guidelines can be found [here](https://github.com/LizardByte/ThemerrDB/blob/master/docs/Theme_Guidelines.md)

**Comment by OcifferAction** [comment]
@LizardByte-bot edit https://www.youtube.com/watch?v=Io0iLkFi1gI

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
