### ISSUE TITLE
[TV SHOW]: Queen Charlotte: A Bridgerton Story (2023)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5853]
### Database URL

https://www.themoviedb.org/tv/196454

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=qigMb8oSh5c

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
