### ISSUE TITLE
[TV SHOW]: Giant Beasts of ARS (2023)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5854]
### Database URL

https://www.themoviedb.org/tv/211093

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=oD6e5vREbhI

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
