### ISSUE TITLE
[TV SHOW]: Liar, Liar (2023)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5855]
### Database URL

https://www.themoviedb.org/tv/122204

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=fgy8NXO8ZKQ

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
