### ISSUE TITLE
[TV SHOW]: Endo and Kobayashi Live! The Latest on Tsundere Villainess Lieselotte (2023)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5856]
### Database URL

https://www.themoviedb.org/tv/154098

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=nv0RrunMhCg

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
