### ISSUE TITLE
[TV SHOW]: Life With an Ordinary Guy Who Reincarnated Into a Total Fantasy Knockout (2022)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5857]
### Database URL

https://www.themoviedb.org/tv/125712

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=sht4Ci2fNfQ

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
