### ISSUE TITLE
[TV SHOW]: Log Horizon (2013)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5858]
### Database URL

https://www.themoviedb.org/tv/60846

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=eW6sEkTGbUc

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
