### ISSUE TITLE
[TV SHOW]: Masamune-kun's Revenge (2017)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5862]
### Database URL

https://www.themoviedb.org/tv/69295

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=EXh9ZFk_Q0c

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
