### ISSUE TITLE
[TV SHOW]: MAYONAKA PUNCH (2024)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5863]
### Database URL

https://www.themoviedb.org/tv/244617

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=uDdjID9tgh0

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
