### ISSUE TITLE
[MOVIE]: Minions: The Rise of Gru (2022)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5867]
### Database URL

https://www.themoviedb.org/movie/438148

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=od8buAKaHiY

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by jjnether** [comment]
A theme for this already exists or was submitted before yours. When replacing a theme in the future, please mark that you're replacing a theme and the reason for it in the submission.
