### ISSUE TITLE
[TV SHOW]: Miss Caretaker of Sunohara-sou (2018)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5868]
### Database URL

https://www.themoviedb.org/tv/80662

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=n-a5Obpfj9Q

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
