### ISSUE TITLE
[TV SHOW]: More Than a Married Couple, But Not Lovers (2022)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5870]
### Database URL

https://www.themoviedb.org/tv/139287

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=zQkMRNKeovM

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
