### ISSUE TITLE
[TV SHOW]: Mother of the Goddess' Dormitory (2021)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5871]
### Database URL

https://www.themoviedb.org/tv/103962

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=gclb1TCSaJc

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
