### ISSUE TITLE
[TV SHOW]: Muv-Luv Alternative (2021)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5872]
### Database URL

https://www.themoviedb.org/tv/112010

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=wGBXObhCThE

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
