### ISSUE TITLE
[TV SHOW]: Muv-Luv Alternative: Total Eclipse (2012)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5873]
### Database URL

https://www.themoviedb.org/tv/45241

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=wcRVZBeM3ek

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
