### ISSUE TITLE
[TV SHOW]: My Daughter Left the Nest and Returned an S-Rank Adventurer (2023)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5874]
### Database URL

https://www.themoviedb.org/tv/229609

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=aoluUL5DQ24

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
