### ISSUE TITLE
[TV SHOW]: My Dress-Up Darling (2022)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5875]
### Database URL

https://www.themoviedb.org/tv/123249

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=9fCNNuH-Grg

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
