### ISSUE TITLE
[TV SHOW]: My Isekai Life: I Gained a Second Character Class and Became the Strongest Sage in the World! (2022)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5876]
### Database URL

https://www.themoviedb.org/tv/117889

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=zQhHfdMolqo

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
