### ISSUE TITLE
[TV SHOW]: My One-Hit Kill Sister (2023)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5879]
### Database URL

https://www.themoviedb.org/tv/194829

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=_acJCqtn6Zw

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
