### ISSUE TITLE
[TV SHOW]: My Stepmom's Daughter Is My Ex (2022)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5880]
### Database URL

https://www.themoviedb.org/tv/129516

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=YjrYKwxZNbY

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
