### ISSUE TITLE
[TV SHOW]: My Tiny Senpai (2023)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5881]
### Database URL

https://www.themoviedb.org/tv/217390

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=34o31uJnXao

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
