### ISSUE TITLE
[TV SHOW]: My Unique Skill Makes Me OP Even at Level 1 (2023)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5882]
### Database URL

https://www.themoviedb.org/tv/201363

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=UJ8IKFMAvok

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
