### ISSUE TITLE
[TV SHOW]: Why the Hell Are You Here, Teacher!? (2019)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5883]
### Database URL

https://www.themoviedb.org/tv/86836

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=HFSiHZynaRs

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
