### ISSUE TITLE
[TV SHOW]: Ningen Fushin: Adventurers Who Don't Believe in Humanity Will Save the World (2023)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5884]
### Database URL

https://www.themoviedb.org/tv/131366

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=hXG2GW02eCo

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
