### ISSUE TITLE
[TV SHOW]: No Longer Allowed in Another World (2024)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5886]
### Database URL

https://www.themoviedb.org/tv/205743

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=H8UBtVs5Z4w

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
