### ISSUE TITLE
[TV SHOW]: Mr. Nobunaga's Young Bride (2019)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5887]
### Database URL

https://www.themoviedb.org/tv/87476

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=MejIxEC9xlQ

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
