### ISSUE TITLE
[TV SHOW]: Do You Love Your Mom and Her Two-Hit Multi-Target Attacks? (2019)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5888]
### Database URL

https://www.themoviedb.org/tv/88808

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=t-qcMP8L9i4

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
