### ISSUE TITLE
[TV SHOW]: ORESUKI Are you the only one who loves me? (2019)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5889]
### Database URL

https://www.themoviedb.org/tv/93019

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=d54zeL3vFgM

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
