### ISSUE TITLE
[TV SHOW]: Osamake: Romcom Where the Childhood Friend Won't Lose (2021)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5891]
### Database URL

https://www.themoviedb.org/tv/110975

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=pjBeYzARnX8

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
