### ISSUE TITLE
[TV SHOW]: UzaMaid! (2018)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5893]
### Database URL

https://www.themoviedb.org/tv/82864

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=_QNOS9oyVGI

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
