### ISSUE TITLE
[TV SHOW]: Outbreak Company (2013)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5894]
### Database URL

https://www.themoviedb.org/tv/62691

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=UxZm-LBAGZA

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
