### ISSUE TITLE
[TV SHOW]: Parallel World Pharmacy (2022)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5896]
### Database URL

https://www.themoviedb.org/tv/129195

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=-hgha7tEPts

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
