### ISSUE TITLE
[TV SHOW]: Peter Grill and the Philosopher's Time (2020)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5897]
### Database URL

https://www.themoviedb.org/tv/99080

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=l8JrmSAo7kI

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
