### ISSUE TITLE
[TV SHOW]: Pon no Michi (2024)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5899]
### Database URL

https://www.themoviedb.org/tv/234176

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=pocZ3dBTJ7Y

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
