### ISSUE TITLE
[TV SHOW]: Protocol: Rain (2023)

### ISSUE THREAD

**Issue by sebrilax** [LizardByte/ThemerrDB#5900]
### Database URL

https://www.themoviedb.org/tv/230288

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=rdxa0T6wOwg

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
