### ISSUE TITLE
[MOVIE]: Sixty Minutes (2023)

### ISSUE THREAD

**Issue by HomerBeer** [LizardByte/ThemerrDB#5904]
### Database URL

https://www.themoviedb.org/movie/1212073

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=cr1QLhin0zg

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
