### ISSUE TITLE
[MOVIE]: The Big Short (2015)

### ISSUE THREAD

**Issue by HomerBeer** [LizardByte/ThemerrDB#5905]
### Database URL

https://www.themoviedb.org/movie/318846

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=WqryvV-uNIU

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
Theme already exists in the database and no replacement reason listed. Closing as duplicate.
