### ISSUE TITLE
[MOVIE]: The Bricklayer (2023)

### ISSUE THREAD

**Issue by HomerBeer** [LizardByte/ThemerrDB#5910]
### Database URL

https://www.themoviedb.org/movie/927107

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=_XJP_vPh6T8

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
The video provided is too long. Please provide a shorter video. See [Theme Guidelines](https://github.com/LizardByte/ThemerrDB/blob/master/docs/Theme_Guidelines.md) for more details.

**Comment by HomerBeer** [comment]
Oeps, missed that. 

This one is shorter.
https://www.youtube.com/watch?v=_XJP_vPh6T8

**Comment by OcifferAction** [comment]
@LizardByte-bot approve

**Comment by OcifferAction** [comment]
@LizardByte-bot edit https://www.youtube.com/watch?v=_XJP_vPh6T8

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
