### ISSUE TITLE
[MOVIE]: Dune: Part Two (2024)

### ISSUE THREAD

**Issue by kajvanderlinden** [LizardByte/ThemerrDB#5915]
### Database URL

https://www.themoviedb.org/movie/693134

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=ZokzN16Fe1M

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
Theme already exists in the database and no replacement reason listed. Closing as duplicate.
