### ISSUE TITLE
[MOVIE]: Kingdom of the Planet of the Apes (2024)

### ISSUE THREAD

**Issue by kajvanderlinden** [LizardByte/ThemerrDB#5917]
### Database URL

https://www.themoviedb.org/movie/653346

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=mo6L5wh6sXc

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
Theme already exists in the database and no replacement reason listed. Closing as duplicate.
