### ISSUE TITLE
[MOVIE]: Saw X (2023)

### ISSUE THREAD

**Issue by kajvanderlinden** [LizardByte/ThemerrDB#5919]
### Database URL

https://www.themoviedb.org/movie/951491

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=CNxBhIS7YiU

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
Theme already exists in the database and no replacement reason listed. Closing as duplicate.
