### ISSUE TITLE
[TV SHOW]: Dungeon People (2024)

### ISSUE THREAD

**Issue by NeoKnux** [LizardByte/ThemerrDB#5924]
### Database URL

https://www.themoviedb.org/tv/250597

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=ya6edm0JpzE

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
