### ISSUE TITLE
[MOVIE]: Dogman (2023)

### ISSUE THREAD

**Issue by HomerBeer** [LizardByte/ThemerrDB#5925]
### Database URL

https://www.themoviedb.org/movie/944401

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=xw0J5QL_wqE

### Additional Information

- [X] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
Please provide a video that's available within the US.

**Comment by OcifferAction** [comment]
Video provided is not available within the US and video already in database is. No replacement reason was listed. Closing as duplicate.
