### ISSUE TITLE
[MOVIE]: Cirque du Soleil: Kooza (2008)

### ISSUE THREAD

**Issue by ianmdesign** [LizardByte/ThemerrDB#5927]
### Database URL

https://www.themoviedb.org/movie/28348

### YouTube Theme Song Video URL

https://youtu.be/x4QqLhCuUwE

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
