### ISSUE TITLE
[TV SHOW]: Letterkenny (2016)

### ISSUE THREAD

**Issue by ianmdesign** [LizardByte/ThemerrDB#5929]
### Database URL

https://www.themoviedb.org/tv/65798

### YouTube Theme Song Video URL

https://youtu.be/0HQ8nL9AZ7A

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by ianmdesign** [comment]
The full theme song is over 6 minutes long (https://youtu.be/ArdUkG3NXOQ), so I thought this original that was made for the final season would fit better.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
