### ISSUE TITLE
[MOVIE]: Spy Kids 3-D: Game Over (2003)

### ISSUE THREAD

**Issue by ianmdesign** [LizardByte/ThemerrDB#5931]
### Database URL

https://www.themoviedb.org/movie/12279

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=yEZkA5lAKkk

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
