### ISSUE TITLE
[TV SHOW]: Vikings: Valhalla (2022)

### ISSUE THREAD

**Issue by celticslment** [LizardByte/ThemerrDB#5934]
### Database URL

https://www.themoviedb.org/tv/116135

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=CNgUC1gDVSo

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
