### ISSUE TITLE
[TV SHOW]: Euphoria (2019)

### ISSUE THREAD

**Issue by celticslment** [LizardByte/ThemerrDB#5936]
### Database URL

https://www.themoviedb.org/tv/85552

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=pwTe7DrJoWE

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
Theme already exists in the database and no replacement reason listed. Closing as duplicate.
