### ISSUE TITLE
[TV SHOW]: House of the Dragon (2022)

### ISSUE THREAD

**Issue by celticslment** [LizardByte/ThemerrDB#5937]
### Database URL

https://www.themoviedb.org/tv/94997

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=9Dk3OOgXlzo

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
Theme already exists in the database and no replacement reason listed. Closing as duplicate.
