### ISSUE TITLE
[MOVIE]: The Figo Affair: The Transfer That Changed Football (2022)

### ISSUE THREAD

**Issue by HomerBeer** [LizardByte/ThemerrDB#5940]
### Database URL

https://www.themoviedb.org/movie/1014779

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=NbGLjQXD0RQ

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
