### ISSUE TITLE
[MOVIE]: Danger Close: The Battle of Long Tan (2019)

### ISSUE THREAD

**Issue by HomerBeer** [LizardByte/ThemerrDB#5948]
### Database URL

https://www.themoviedb.org/movie/508664

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=WlRvlfmRtqY

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
