### ISSUE TITLE
[MOVIE]: Pink Floyd - The Reunion Concert (2005)

### ISSUE THREAD

**Issue by ianmdesign** [LizardByte/ThemerrDB#5953]
### Database URL

https://www.themoviedb.org/movie/115101

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=x-xTttimcNk

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
