### ISSUE TITLE
[MOVIE]: Easter Bloody Easter (2024)

### ISSUE THREAD

**Issue by HomerBeer** [LizardByte/ThemerrDB#5955]
### Database URL

https://www.themoviedb.org/movie/1201176

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=zB-QyEqeSCw

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
