### ISSUE TITLE
[MOVIE]: Gasoline Alley (2022)

### ISSUE THREAD

**Issue by HomerBeer** [LizardByte/ThemerrDB#5962]
### Database URL

https://www.themoviedb.org/movie/916821

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=7_cZtprCCfY

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
