### ISSUE TITLE
[MOVIE]: Heart of the Hunter (2024)

### ISSUE THREAD

**Issue by HomerBeer** [LizardByte/ThemerrDB#5963]
### Database URL

https://www.themoviedb.org/movie/1181548

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=emxnNmR7dhA

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
