### ISSUE TITLE
[MOVIE]: Horizon: An American Saga - Chapter 1 (2024)

### ISSUE THREAD

**Issue by HomerBeer** [LizardByte/ThemerrDB#5965]
### Database URL

https://www.themoviedb.org/movie/932086

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=N4GGIxd3g_Q

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
