### ISSUE TITLE
[MOVIE]: Gurren Lagann the Movie: The Lights in the Sky Are Stars (2009)

### ISSUE THREAD

**Issue by NeoKnux** [LizardByte/ThemerrDB#5966]
### Database URL

https://www.themoviedb.org/movie/23452

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=I1IVX9P9kVk

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
