### ISSUE TITLE
[MOVIE]: Gurren Lagann the Movie: Childhood's End (2008)

### ISSUE THREAD

**Issue by NeoKnux** [LizardByte/ThemerrDB#5967]
### Database URL

https://www.themoviedb.org/movie/20986

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=I1IVX9P9kVk

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
