### ISSUE TITLE
[TV SHOW]: Burger Quiz (2001)

### ISSUE THREAD

**Issue by CrowMash** [LizardByte/ThemerrDB#5970]
### Database URL

https://www.themoviedb.org/tv/53007

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=8p3f6S1njhU

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
