### ISSUE TITLE
[MOVIE]: How to Train Your Dragon 2 (2014)

### ISSUE THREAD

**Issue by CrowMash** [LizardByte/ThemerrDB#5971]
### Database URL

https://www.themoviedb.org/movie/82702

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=TSoyuQHPuOg

### Additional Information

- [x] This is a replacement request. If checked, please provide a reason below.

### Replacement Reason

Old video is not available

**Comment by CrowMash** [comment]
Maybe this one is better: https://www.youtube.com/watch?v=TSoyuQHPuOg

**Comment by OcifferAction** [comment]
@LizardByte-bot edit https://www.youtube.com/watch?v=TSoyuQHPuOg

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
