### ISSUE TITLE
[MOVIE]: Dumbo (2019)

### ISSUE THREAD

**Issue by CrowMash** [LizardByte/ThemerrDB#5972]
### Database URL

https://www.themoviedb.org/movie/329996

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=V0-uOwhug1Q

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
I don't think the intro song represents the theme of the movie very well. How does this work instead?

https://www.youtube.com/watch?v=V0-uOwhug1Q

**Comment by CrowMash** [comment]
Perfect!

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
