### ISSUE TITLE
[MOVIE]: A River Runs Through It (1992)

### ISSUE THREAD

**Issue by CrowMash** [LizardByte/ThemerrDB#5973]
### Database URL

https://www.themoviedb.org/movie/293

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=MCn4UwPHyKs

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by CrowMash** [comment]
Maybe this one is better: https://www.youtube.com/watch?v=MCn4UwPHyKs

**Comment by OcifferAction** [comment]
@LizardByte-bot edit https://www.youtube.com/watch?v=MCn4UwPHyKs

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
