### ISSUE TITLE
[MOVIE]: Fast & Furious Presents: Hobbs & Shaw (2019)

### ISSUE THREAD

**Issue by CrowMash** [LizardByte/ThemerrDB#5974]
### Database URL

https://www.themoviedb.org/movie/384018

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=ahAX93Uo5Jk

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
