### ISSUE TITLE
[MOVIE]: Gemini Man (2019)

### ISSUE THREAD

**Issue by CrowMash** [LizardByte/ThemerrDB#5975]
### Database URL

https://www.themoviedb.org/movie/453405

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=oJ2_MQpK0Ew

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
