### ISSUE TITLE
[MOVIE]: Guns Akimbo (2020)

### ISSUE THREAD

**Issue by CrowMash** [LizardByte/ThemerrDB#5976]
### Database URL

https://www.themoviedb.org/movie/457335

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=Ke2PGc0Creo

### Additional Information

- [x] This is a replacement request. If checked, please provide a reason below.

### Replacement Reason

Cannot access old video

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
