### ISSUE TITLE
[MOVIE]: Iron Sky (2012)

### ISSUE THREAD

**Issue by CrowMash** [LizardByte/ThemerrDB#5978]
### Database URL

https://www.themoviedb.org/movie/10679

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=gwJH_vuVDJ4

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
