### ISSUE TITLE
[MOVIE]: Iron Sky: The Coming Race (2019)

### ISSUE THREAD

**Issue by CrowMash** [LizardByte/ThemerrDB#5979]
### Database URL

https://www.themoviedb.org/movie/302349

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=oEgNem_bPRA

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
