### ISSUE TITLE
[MOVIE]: The Lego Movie 2: The Second Part (2019)

### ISSUE THREAD

**Issue by CrowMash** [LizardByte/ThemerrDB#5980]
### Database URL

https://www.themoviedb.org/movie/280217

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=Q_HFm54lb04

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
