### ISSUE TITLE
[MOVIE]: Bāhubali: The Beginning (2015)

### ISSUE THREAD

**Issue by CrowMash** [LizardByte/ThemerrDB#5981]
### Database URL

https://www.themoviedb.org/movie/256040

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=Y6toKadvJlY

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
Video provided has scene audio as well. How does this video of just the song work instead?

https://www.youtube.com/watch?v=Y6toKadvJlY

**Comment by CrowMash** [comment]
Perfect!

**Comment by OcifferAction** [comment]
@LizardByte-bot edit https://www.youtube.com/watch?v=Y6toKadvJlY

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
