### ISSUE TITLE
[TV SHOW]: Doctor Who (2024)

### ISSUE THREAD

**Issue by Netfreak25** [LizardByte/ThemerrDB#6026]
### Database URL

https://www.themoviedb.org/tv/239770

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=u0_lqGZ2Fq4

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
