### ISSUE TITLE
[MOVIE]: Dogma (1999)

### ISSUE THREAD

**Issue by Netfreak25** [LizardByte/ThemerrDB#6033]
### Database URL

https://www.themoviedb.org/movie/1832

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=g5Gvce-92Tw&list=PLGYotK7q5kbUO2uo6XlukbmMF5nTaz_19

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
A theme for this movie was approved earlier today and should be available soon. Closing this as a duplicate.
