### ISSUE TITLE
[MOVIE]: Four Lions (2010)

### ISSUE THREAD

**Issue by Netfreak25** [LizardByte/ThemerrDB#6035]
### Database URL

https://www.themoviedb.org/movie/37495

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=MBFXJw7n-fU&list=PL6BB39D0F4152A6A4

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
