### ISSUE TITLE
[TV SHOW]: Warehouse 13 (2009)

### ISSUE THREAD

**Issue by Netfreak25** [LizardByte/ThemerrDB#6042]
### Database URL

https://www.themoviedb.org/tv/15819

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=ZboZV8yi9gE

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
