### ISSUE TITLE
[MOVIE]: Up in the Air (2009)

### ISSUE THREAD

**Issue by Netfreak25** [LizardByte/ThemerrDB#6045]
### Database URL

https://www.themoviedb.org/movie/22947

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=LfFEDVE4bR4

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
A theme already exists in the database for this movie and no replacement reason was listed. Closing as duplicate.

**Comment by Netfreak25** [comment]
OK sorry for that.
It was shown as missing in the Admin Area of Jellyfin
![image](https://github.com/user-attachments/assets/30d1987b-9cba-4f78-9011-886da9ac4f6f)

https://github.com/LizardByte/ThemerrDB/issues/new?assignees=&labels=request-theme&template=theme.yml&title=[MOVIE]:%20Up%20in%20the%20Air%20(2009)&database_url=https://www.themoviedb.org/movie/22947

**Comment by Netfreak25** [comment]
![image](https://github.com/user-attachments/assets/b43df581-6575-4836-8b89-64cde0c5cafb)
Also the Metadata seems to be correct - the Interface claims its missing.

But please close the issue if its an issue on my side.
