### ISSUE TITLE
[MOVIE]: The Harder They Come (1972)

### ISSUE THREAD

**Issue by Netfreak25** [LizardByte/ThemerrDB#6050]
### Database URL

https://www.themoviedb.org/movie/7514

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=7Znh0OM9jiA

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
