### ISSUE TITLE
[TV SHOW]: Batman: Caped Crusader (2024)

### ISSUE THREAD

**Issue by NeoKnux** [LizardByte/ThemerrDB#6056]
### Database URL

https://www.themoviedb.org/tv/125909

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=TakuT4-Ait4

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
