### ISSUE TITLE
[MOVIE]: A Taxi Driver (2017)

### ISSUE THREAD

**Issue by sean6789** [LizardByte/ThemerrDB#6058]
### Database URL

https://www.themoviedb.org/movie/437068

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=EkD4N_aLUNo

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
