### ISSUE TITLE
[MOVIE]: Ask Me to Dance (2022)

### ISSUE THREAD

**Issue by sean6789** [LizardByte/ThemerrDB#6059]
### Database URL

https://www.themoviedb.org/movie/1032124

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=v7om-ZQS1Ss

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
