### ISSUE TITLE
[TV SHOW]: Kengan Ashura (2019)

### ISSUE THREAD

**Issue by joao17017** [LizardByte/ThemerrDB#6099]
### Database URL

https://www.themoviedb.org/tv/90660

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=OxNeZiOr_zs&ab_channel=MYFIRSTSTORY-Topic

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
