### ISSUE TITLE
[TV SHOW]: Dragon Raja -The Blazing Dawn- (2022)

### ISSUE THREAD

**Issue by joao17017** [LizardByte/ThemerrDB#6100]
### Database URL

https://www.themoviedb.org/tv/107255

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=2dM0QtCoRTI&ab_channel=%E7%9C%BC%E3%81%89Melody

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
