### ISSUE TITLE
[TV SHOW]: Gate (2015)

### ISSUE THREAD

**Issue by joao17017** [LizardByte/ThemerrDB#6101]
### Database URL

https://www.themoviedb.org/tv/63663

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=jr-YAO5loV8&ab_channel=Crunchyroll

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
