### ISSUE TITLE
[TV SHOW]: Tower of God (2020)

### ISSUE THREAD

**Issue by joao17017** [LizardByte/ThemerrDB#6103]
### Database URL

https://www.themoviedb.org/tv/97860

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=7SPnJMGB9u4&ab_channel=StrayKidsJapanOfficialYouTube

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
