### ISSUE TITLE
[MOVIE]: Cirque du Soleil : KURIOS - Cabinet des curiosités (2018)

### ISSUE THREAD

**Issue by ianmdesign** [LizardByte/ThemerrDB#6108]
### Database URL

https://www.themoviedb.org/movie/558130

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=FYsnaLesV3o

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
