### ISSUE TITLE
[TV SHOW]: Revolutionary Girl Utena (1997)

### ISSUE THREAD

**Issue by alsoGAMER** [LizardByte/ThemerrDB#6109]
### Database URL

https://www.themoviedb.org/tv/1042-revolutionary-girl-utena

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=Y_0VKKoj-A0

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
