### ISSUE TITLE
[TV SHOW]: From the New World (2012)

### ISSUE THREAD

**Issue by alsoGAMER** [LizardByte/ThemerrDB#6110]
### Database URL

https://www.themoviedb.org/tv/53052-shin-sekai-yori

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=SDv-emUuTgQ

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
