### ISSUE TITLE
[TV SHOW]: BanG Dream! It's MyGO!!!!! (2023)

### ISSUE THREAD

**Issue by alsoGAMER** [LizardByte/ThemerrDB#6111]
### Database URL

https://www.themoviedb.org/tv/224207-bang-dream-it-s-mygo

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=cjyxTk_IfIY

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
