### ISSUE TITLE
[MOVIE]: The Tale of Genji (1987)

### ISSUE THREAD

**Issue by alsoGAMER** [LizardByte/ThemerrDB#6117]
### Database URL

https://www.themoviedb.org/movie/85811

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=oiw84tFeZxY

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
