### ISSUE TITLE
[TV SHOW]: Blue Orchestra (2023)

### ISSUE THREAD

**Issue by NeoKnux** [LizardByte/ThemerrDB#6118]
### Database URL

https://www.themoviedb.org/tv/197368

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=Ysgo4wjCjjM

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
