### ISSUE TITLE
[TV SHOW]: Redbad - The Legend (2020)

### ISSUE THREAD

**Issue by jj3005** [LizardByte/ThemerrDB#6119]
### Database URL

https://www.themoviedb.org/tv/205195

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=jVta7XeZeAc

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
