### ISSUE TITLE
[TV SHOW]: Battlestar Galactica (2003)

### ISSUE THREAD

**Issue by sean6789** [LizardByte/ThemerrDB#6123]
### Database URL

https://www.themoviedb.org/tv/71365

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=0bnHJZL-NVA

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
