### ISSUE TITLE
[MOVIE]: Birthright Outlaw (2023)

### ISSUE THREAD

**Issue by sean6789** [LizardByte/ThemerrDB#6125]
### Database URL

https://www.themoviedb.org/movie/1132016

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=NoC1l0mVZH8

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
