### ISSUE TITLE
[TV SHOW]: Tomo-chan Is a Girl! (2023)

### ISSUE THREAD

**Issue by NeoKnux** [LizardByte/ThemerrDB#6127]
### Database URL

https://www.themoviedb.org/tv/205308

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=JypMi-Dt_S8

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
