### ISSUE TITLE
[MOVIE]: I Want to Eat Your Pancreas (2018)

### ISSUE THREAD

**Issue by KoolKat15** [LizardByte/ThemerrDB#6130]
### Database URL

https://www.themoviedb.org/movie/504253

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=Vawlw-k7Xy8

### Additional Information

- [x] This is a replacement request. If checked, please provide a reason below.

### Replacement Reason

Use normal version

**Comment by jjnether** [comment]
@LizardByte-bot approve
