### ISSUE TITLE
[TV SHOW]: Land of the Lustrous (2017)

### ISSUE THREAD

**Issue by KoolKat15** [LizardByte/ThemerrDB#6131]
### Database URL

https://www.themoviedb.org/tv/74091

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=P2AGDM7YQyc

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
