### ISSUE TITLE
[MOVIE]: Werewolf by Night (2022)

### ISSUE THREAD

**Issue by weatherluvr** [LizardByte/ThemerrDB#6141]
### Database URL

https://www.themoviedb.org/movie/894205

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=6HilvaYudLE

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
