### ISSUE TITLE
[MOVIE]: World's Greatest Dad (2009)

### ISSUE THREAD

**Issue by Alethio36** [LizardByte/ThemerrDB#6224]
### Database URL

https://www.themoviedb.org/movie/20178

### YouTube Theme Song Video URL

https://youtu.be/5N-lSyjaTDU?si=k5xTZsPpFkpRBD-I

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
