### ISSUE TITLE
[TV SHOW]: Will & Grace (1998)

### ISSUE THREAD

**Issue by Alethio36** [LizardByte/ThemerrDB#6225]
### Database URL

https://www.themoviedb.org/tv/4454

### YouTube Theme Song Video URL

https://youtu.be/ZKACb5IkIqY?si=tGLWs_kSKGI95uxX

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
