### ISSUE TITLE
[MOVIE]: Kubo and the Two Strings (2016)

### ISSUE THREAD

**Issue by Alethio36** [LizardByte/ThemerrDB#6229]
### Database URL

https://www.themoviedb.org/movie/313297

### YouTube Theme Song Video URL

https://youtu.be/ND03o6BJczA?si=KhEz9Rxibl0w4MOJ

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
