### ISSUE TITLE
[MOVIE]: The Platform (2019)

### ISSUE THREAD

**Issue by alexdelfol** [LizardByte/ThemerrDB#6231]
### Database URL

https://www.themoviedb.org/movie/619264

### YouTube Theme Song Video URL

https://youtu.be/LUrySef06uw?si=kVHTGWopjuluZS-F

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
Theme already exists in the database and no replacement reason was listed. Closing as duplicate.
