### ISSUE TITLE
[MOVIE]: 2 Fast 2 Furious (2003)

### ISSUE THREAD

**Issue by khalil1342** [LizardByte/ThemerrDB#6267]
### Database URL

https://www.themoviedb.org/movie/584

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=A5stfHSFc6A

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
There is a theme in the database for this movie already and no replacement reason was listed. Closing as duplicate.
