### ISSUE TITLE
[MOVIE]: Alita: Battle Angel (2019)

### ISSUE THREAD

**Issue by ind0r90** [LizardByte/ThemerrDB#739]
### TheMovieDB URL

https://www.themoviedb.org/movie/399579

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=2K_CzTLFpAA&ab_channel=JunkieXL

**Comment by ReenigneArcher** [comment]
This one or #740 ?

**Comment by ind0r90** [comment]
tmdb link was wrong I corrected it
