### ISSUE TITLE
[MOVIE]: Black Panther (2018)

### ISSUE THREAD

**Issue by ind0r90** [LizardByte/ThemerrDB#745]
### TheMovieDB URL

https://www.themoviedb.org/movie/284054-black-panther

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=CNrLj8OWj7I&ab_channel=LuisMart%C3%ADnG.

**Comment by ReenigneArcher** [comment]
Can you edit the original issue? The YouTube video is for Black Panther.
