### ISSUE TITLE
[MOVIE]: Day Shift (2022)

### ISSUE THREAD

**Issue by ind0r90** [LizardByte/ThemerrDB#757]
### TheMovieDB URL

https://www.themoviedb.org/movie/755566

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=GxsDKffV_qg&ab_channel=CrucialMixtapes

**Comment by ReenigneArcher** [comment]
Can you try to find a clean version or instrumental?

**Comment by ind0r90** [comment]
done, i hope yt shorts also work couldn't find any other video with instrumentals

**Comment by ReenigneArcher** [comment]
It appears that shorts do not work. Sorry about that.

**Comment by ind0r90** [comment]
last try this is the intro of the movie + instrumental if this audio is also not fine you can close this issue thanks.
