### ISSUE TITLE
[MOVIE]: The Hobbit: The Desolation of Smaug (2013)

### ISSUE THREAD

**Issue by ind0r90** [LizardByte/ThemerrDB#787]
### TheMovieDB URL

https://www.themoviedb.org/movie/57158-the-hobbit-the-desolation-of-smaug

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=hDaVmXxqiy8&ab_channel=HowardShore-Topic

**Comment by ReenigneArcher** [comment]
This theme song is too long, ~25 minutes. Can you find a shorter one?

**Comment by ind0r90** [comment]
done
