### ISSUE TITLE
[MOVIE]: Shang-Chi and the Legend of the Ten Rings (2021)

### ISSUE THREAD

**Issue by TownyMontana** [LizardByte/ThemerrDB#797]
### TheMovieDB URL

https://www.themoviedb.org/movie/566525-shang-chi-and-the-legend-of-the-ten-rings?language=en-US

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=p_xlIUu8_hA

**Comment by ReenigneArcher** [comment]
Thank you for the submission... Please correct the link. TheMovieDB URL should be a link to the individual item, not to a search query.

The YouTube URL should be a link to an individual video, not including the playlist and channel.

**Comment by TownyMontana** [comment]
Request has been updated with correct links for TMDB and YT.

**Comment by TownyMontana** [comment]
Thanks a lot

**Comment by TownyMontana** [comment]
Can you add this movie

**Comment by ReenigneArcher** [comment]
Requests are processed in the order they're received. With that said. This movie is already in the database. Are you wanted to change the theme song or just didn't know it was in the database?

**Comment by TownyMontana** [comment]
I wasn't sure if it was in the database. We can stick with the first request. Please close this #797
