### ISSUE TITLE
[MOVIE]: 3 Idiots (2009)

### ISSUE THREAD

**Issue by TownyMontana** [LizardByte/ThemerrDB#801]
### TheMovieDB URL

https://www.themoviedb.org/movie/20453-3-idiots?language=en-US

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=WT05fQbtrTo

**Comment by ReenigneArcher** [comment]
This appears to be the opening scene, we'd prefer audio only if you can find it.

**Comment by TownyMontana** [comment]
YT link has been updates with BG Music
