### ISSUE TITLE
[MOVIE]: 21 Bridges (2019)

### ISSUE THREAD

**Issue by TownyMontana** [LizardByte/ThemerrDB#802]
### TheMovieDB URL

https://www.themoviedb.org/movie/535292-21-bridges?language=en-US

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=wkh_HM63q_Q

**Comment by TownyMontana** [comment]
Thanks a lot

**Comment by ReenigneArcher** [comment]
Why are you closing these... they're not added yet

**Comment by TownyMontana** [comment]
got it I will open it again. How do I know if they are added. What label should I looks for.

**Comment by ReenigneArcher** [comment]
Issues are closed automatically once they're processed.

**Comment by TownyMontana** [comment]
Got it. Thanks for the update.
