### ISSUE TITLE
[MOVIE]: 14 Phere (2021)

### ISSUE THREAD

**Issue by TownyMontana** [LizardByte/ThemerrDB#803]
### TheMovieDB URL

https://www.themoviedb.org/movie/732886-14-phere?language=en-US

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=PwDhdoGd2Cs

**Comment by TownyMontana** [comment]
Once this is added to the database do I need to update anything from my end other then Refreshing the Metadata of the Particular Movie. And when is the database updated?. Is it live or do I have to wait for the update to be pushed.

**Comment by ReenigneArcher** [comment]
New updates will be available everyday around 12:00 UTC.

If you're using our Plex plugin you only need to refresh the item. If our Jellyfin plugin, it will grab the updates automatically.

**Comment by TownyMontana** [comment]
> New updates will be available everyday around 12:00 UTC.
> 
> If you're using our Plex plugin you only need to refresh the item. If our Jellyfin plugin, it will grab the updates automatically.

Got it. Thanks a lot
