### ISSUE TITLE
[MOVIE]: Star Wars (1977)

### ISSUE THREAD

**Issue by samcro1967** [LizardByte/ThemerrDB#804]
### TheMovieDB URL

https://www.themoviedb.org/movie/11-star-wars?language=en-US

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=Vz69BumnD5g&t=10s

**Comment by samcro1967** [comment]
@ReenigneArcher I had three in a row that say automation failed.  Not sure if I did something wrong or if there is a glitch in the Matrix.

**Comment by ReenigneArcher** [comment]
We need TheMovieDB URL's not, IMDB. You can edit the issues to replace the URL. Thanks.

**Comment by samcro1967** [comment]
Doh!  Thanks for pointing out the obvious to me.  LOL
