### ISSUE TITLE
[MOVIE]: Robin Hood: Prince of Thieves (1991)

### ISSUE THREAD

**Issue by samcro1967** [LizardByte/ThemerrDB#834]
### TheMovieDB URL

https://www.themoviedb.org/movie/8367-robin-hood-prince-of-thieves?language=en-US

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=b5Edkb2Qo9c

**Comment by ReenigneArcher** [comment]
The first half of this is just the Morgan Creek intro. Can you try to find something different?

**Comment by samcro1967** [comment]
Added a different version

**Comment by ReenigneArcher** [comment]
It has the same thing in it. Maybe this will demonstrate what I mean. https://www.youtube.com/watch?v=PVqEyOhTmes

**Comment by samcro1967** [comment]
Didn't realize that intro was not part of the theme song.  Try this one.

**Comment by ReenigneArcher** [comment]
Okay, it appears it's part included in them all.

I'm not a fan of it being included but it is what it is.
