### ISSUE TITLE
[MOVIE]: La Bamba (1987)

### ISSUE THREAD

**Issue by samcro1967** [LizardByte/ThemerrDB#838]
### TheMovieDB URL

https://www.themoviedb.org/movie/16620-la-bamba?language=en-US

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=bfAZvP83-74

**Comment by ReenigneArcher** [comment]
I noticed you are included timestamps in your video links. For now, we don't support timestamps.

Additionally, try not to use theme videos that have other ambient sounds. For example in this one it had some noises of placing the record on the record player in the very beginning. Note, that I've already replaced the url.
