### ISSUE TITLE
[MOVIE]: Mission Majnu (2023)

### ISSUE THREAD

**Issue by TownyMontana** [LizardByte/ThemerrDB#958]
### TheMovieDB URL

https://www.themoviedb.org/movie/778946-mission-majnu?language=en-US

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=3NF5g9Ibg_Q&ab_channel=BlACKFAMILY%F0%9F%8E%A7

**Comment by ReenigneArcher** [comment]
Please select something else. We try to avoid ambient sounds and things like that.

**Comment by TownyMontana** [comment]
> Please select something else. We try to avoid ambient sounds and things like that.

Request has been edited and updated thats the best background music I could find for this movie
