### ISSUE TITLE
[MOVIE]: Ninja Scroll (1993)

### ISSUE THREAD

**Issue by jjnether** [LizardByte/ThemerrDB#971]
### TheMovieDB URL

https://www.themoviedb.org/movie/14282?language=en-US

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=dWntOQyVQ7E&ab_channel=SamuraiShowdownOST

**Comment by ReenigneArcher** [comment]
For playlists we use the first video... is that intentional or you want the one that opens on your link? If the latter option, please update the url to point to the exact video.

**Comment by jjnether** [comment]
Ahh my bad, I'll keep that in mind to not link playlists. I edited the comment with the updated link.
