### ISSUE TITLE
[MOVIE]: J.R.R. Tolkien's The Hobbit (2015)

### ISSUE THREAD

**Issue by jjnether** [LizardByte/ThemerrDB#975]
### TheMovieDB URL

https://www.themoviedb.org/movie/775417-j-r-r-tolkien-s-the-hobbit

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=mKVCd7IbtIk

**Comment by jjnether** [comment]
This is a fan edit of the Hobbit I have on my Plex. Plex can find the tmdb number and get all the metadata, but when I enter it on the website, it looks like it doesn't see it. Not sure if this can still be used?

**Comment by ReenigneArcher** [comment]
Depending on what agent you're using Plex might be using their own database instead of tmdb.

Anyway, is it this one? https://www.themoviedb.org/movie/651342-j-r-r-tolkien-and-the-birth-of-the-lord-of-the-rings-and-the-hobbit

If not, we do need a valid tmdb id in order to add it to our database.

**Comment by jjnether** [comment]
Yeah, this one was a bit of a long shot. No problem at all
