### ISSUE TITLE
[MOVIE]: Decision to Leave (2022)

### ISSUE THREAD

**Issue by roennow** [LizardByte/ThemerrDB#988]
### TheMovieDB URL

https://www.themoviedb.org/movie/705996

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=-zIg52PSGNk

**Comment by jjnether** [comment]
This should work:

https://www.youtube.com/watch?v=PAKzo_k_cp8

**Comment by ReenigneArcher** [comment]
Youtube-dl is broken right now, cannot add anything until they publish a new release.

**Comment by jjnether** [comment]
> Youtube-dl is broken right now, cannot add anything until they publish a new release.

Yep, just saw the link was broken, so I was suggesting a different one.

**Comment by ReenigneArcher** [comment]
@jjnether feel free to submit a new issue with your recommendation if you'd like.

**Comment by ReenigneArcher** [comment]
Resolved by #1034
