### ISSUE TITLE
[MOVIE]: Redline (2010)

### ISSUE THREAD

**Issue by jjnether** [LizardByte/ThemerrDB#993]
### TheMovieDB URL

https://www.themoviedb.org/movie/71883-redline?language=en-US

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=wvgZQx_PWzo&ab_channel=JamesShimoji-Topic

**Comment by ReenigneArcher** [comment]
The suggestion is 10 minutes long so will stick with the existing one.
